/* GENERATED by scripts/build-tailwind.mjs — edit Tabs.manifest.json, not this file. */
export default {
  "component": "Tabs",
  "slots": {
    "root": "flex gap-1 border-b-[length:var(--bw)] border-base-300",
    "tab": "relative px-4 py-2.5 bg-transparent border-none cursor-pointer font-body text-ctl transition-[color] duration-[var(--dur-fast)] ease-out focus-visible:shadow-[0_0_0_var(--focus-width)_var(--gold-soft)]",
    "panel": "block pt-[calc(var(--sp-1)*5.5)]"
  },
  "variants": {
    "selected": {
      "true": {
        "tab": "font-semibold text-base-content shadow-[inset_0_calc(var(--bw-strong)*-1)_0_var(--crimson)]"
      },
      "false": {
        "tab": "font-medium text-base-content/62 shadow-none",
        "panel": "hidden"
      }
    }
  },
  "defaultVariants": {
    "selected": false
  }
} as const;
