/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { useContainerWidth, readBreakpoint } from "../../use-container-width.js";
export function PageHead({ title, subtitle, actions, align = "start" }) {
  if (!title)
    throw new Error("PageHead: `title` is required");
  const [ref, width] = useContainerWidth();
  const narrow = width !== null && width < readBreakpoint("sm");
  return React.createElement("div", {
    ref,
    style: {
      display: "flex",
      flexDirection: narrow ? "column" : "row",
      alignItems: narrow ? "stretch" : align === "center" ? "center" : "flex-start",
      justifyContent: "space-between",
      gap: "calc(var(--sp-1) * 4)"
    }
  }, React.createElement("div", {
    style: { minWidth: 0 }
  }, React.createElement("h1", {
    style: {
      fontFamily: "var(--font-display)",
      fontWeight: "var(--fw-extrabold)",
      fontSize: "var(--fs-h1)",
      lineHeight: "var(--lh-snug)",
      letterSpacing: "var(--ls-tight)",
      color: "var(--bone)",
      margin: 0
    }
  }, title), subtitle && React.createElement("p", {
    style: {
      fontFamily: "var(--font-body)",
      fontSize: "var(--fs-sm)",
      color: "var(--mute)",
      margin: "calc(var(--sp-1) * 0.5) 0 0",
      lineHeight: "var(--lh-body)"
    }
  }, subtitle)), actions && React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      flexWrap: "wrap",
      gap: "calc(var(--sp-1) * 2)",
      flexShrink: 0,
      width: narrow ? "100%" : "auto"
    }
  }, actions));
}
