/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { rowStyle, rowGlyph } from "./side-nav-inject.js";
export function SideNavItem({
  id,
  label,
  icon,
  href,
  depth = 0,
  activeId,
  indentStep = 3,
  onActivate
}) {
  if (!id)
    throw new Error("SideNavItem: `id` is required");
  if (!label)
    throw new Error("SideNavItem: `label` is required");
  const on = id === activeId;
  const shared = {
    "aria-current": on ? "page" : undefined,
    onClick: () => onActivate && onActivate(id),
    style: rowStyle({
      indentStep,
      depth,
      background: on ? "var(--crimson-soft)" : "transparent",
      color: on ? "var(--crimson)" : "var(--mute)",
      textDecoration: "none",
      fontWeight: on ? "var(--fw-semibold)" : "var(--fw-medium)"
    })
  };
  const glyph = rowGlyph(icon);
  return href ? React.createElement("a", {
    href,
    ...shared
  }, glyph, label) : React.createElement("button", {
    type: "button",
    ...shared
  }, glyph, label);
}
