import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  buildPlaygrounds, codecFiles, codecTarget, renderCodec, componentFiles, loadPlaces, placesFor,
  CODEC_BANNER, CODEC_SOURCE, PLAYGROUND_LAYERS,
} from './generate-playgrounds.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';

test('every layer with a playground gets the codec, and nothing else does', () => {
  assert.deepEqual(PLAYGROUND_LAYERS, ['react', 'angular']);
  assert.deepEqual(
    [...codecFiles().keys()],
    PLAYGROUND_LAYERS.map((layer) => codecTarget(layer)),
  );
});

test('the emitted copies are byte-identical, which is the whole reason they are emitted', () => {
  const bodies = new Set(codecFiles().values());
  assert.equal(bodies.size, 1,
    'two copies of decode() that drift render the same URL differently in each layer, and no gate would see it');
});

test('the copy names its generator and its source, so nobody edits the copy', () => {
  const body = [...codecFiles().values()][0];
  assert.ok(body.startsWith(CODEC_BANNER));
  assert.match(body, /generate-playgrounds\.ts/);
  assert.match(body, /frameworks\/demos\/PlaygroundCodec\.ts/);
});

test('the copy carries the source verbatim below the banner', () => {
  const source = readFileSync(join(root, CODEC_SOURCE), 'utf8');
  assert.equal(renderCodec(source).slice(CODEC_BANNER.length), `\n${source}`);
});

test('the target carries the generated infix, or the copy would be read as hand-written', () => {
  for (const layer of PLAYGROUND_LAYERS) {
    assert.match(codecTarget(layer), /\.generated\.ts$/);
    assert.match(codecTarget(layer), new RegExp(`^frameworks/${layer}/playground/`));
  }
});

test('an emit of nothing is a failure rather than a clean pass', () => {
  const { files, problems } = buildPlaygrounds();
  assert.ok(files.size > 0);
  assert.deepEqual(problems, []);
});

test('the pilot emits a page and an entry into both layers, and nothing else', () => {
  const files = [...componentFiles(root, ['ArenaCard']).keys()].sort();
  assert.deepEqual(files, [
    'frameworks/angular/components/display/arena-card/ArenaCard.demo.entry.generated.ts',
    'frameworks/angular/components/display/arena-card/ArenaCard.demo.generated.html',
    'frameworks/react/components/display/arena-card/ArenaCard.demo.entry.generated.tsx',
    'frameworks/react/components/display/arena-card/ArenaCard.demo.generated.html',
  ]);
});

test('a page lands beside the component it draws, so the two URLs differ in one path segment', () => {
  const files = [...componentFiles(root, ['ArenaCard']).keys()];
  const pages = files.filter((f) => f.endsWith('.html')).map((f) => f.replace(/^frameworks\/\w+\//, ''));
  assert.equal(new Set(pages).size, 1, 'the two layers must reach the same path below their own root');
});

test('a component reaching something frameworks/Components.json does not name fails by name', () => {
  const all = loadPlaces(root);
  assert.throws(
    () => placesFor({ component: 'ArenaCard', uses: ['Nope'] }, all),
    /reaches Nope, which frameworks\/Components\.json does not name/,
  );
});

test('every emitted file names its generator, so nobody edits the copy', () => {
  for (const [rel, body] of componentFiles(root, ['ArenaCard'])) {
    assert.match(body, /GENERATED by scripts\/generate\/arena\/generate-playgrounds\.ts/, rel);
  }
});
