import StyleDictionary from 'style-dictionary';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { serialize } from '../../lib/core/serialize-token.ts';
import { serializeScript, scriptName } from '../../lib/core/serialize-script.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { childEntries, isToken } from '../../lib/core/dtcg-shapes.ts';
import type { DtcgNode, DtcgToken } from '../../lib/core/dtcg-shapes.ts';

const HEADER = '/* GENERATED by Style Dictionary — edit contracts/design/, not this file. */';

export const FILES = [
  { out: 'palette.generated.css', blocks: [
    { selector: ':root', source: 'palette.dark.json' },
    { selector: '.arena-light', source: 'palette.light.json' },
  ] },
  { out: 'typography.generated.css', blocks: [
    { selector: ':root', source: 'typography.json' },
  ] },
  { out: 'spacing.generated.css', blocks: [
    { selector: ':root', source: 'spacing.json' },
    { selector: ':root', source: 'icon.json' },
    { selector: ':root', source: 'component.json' },
    { selector: '.arena-compact', source: 'density.compact.json' },
  ] },
  { out: 'effects.generated.css', blocks: [
    { selector: ':root', source: 'effects.json' },
    { selector: ':root', source: 'layering.json' },
    { selector: ':root', source: 'chart.json' },
    { selector: ':root', source: 'behaviour.json' },
  ] },
];

export const RESOLVES_AGAINST = {
  'chart.json': ['spacing.json'],
};

const EXT = 'com.dravensoft.arena';

export const SCRIPT_TARGETS = [
  'frameworks/react/Tokens.generated.js',
  'frameworks/angular/Tokens.generated.ts',
];

export const BREAKPOINT_TARGET = 'frameworks/tailwind/Breakpoints.generated.css';

const BREAKPOINT_HEADER =
  '/* GENERATED by scripts/generate/arena/generate-tokens.ts — edit contracts/design/spacing.json, not this file.\n'
  + ' *\n'
  + ' * Tailwind\'s breakpoint namespace, emitted as LITERALS and not as var() references,\n'
  + ' * because a media query condition holds no var(): Tailwind resolves a --breakpoint-*\n'
  + ' * value at build time to write the variant\'s @media. This is the one place an Arena\n'
  + ' * value is spelled twice, and it is generated so the two cannot drift. Tailwind\'s own\n'
  + ' * defaults are cleared first, the way every namespace in Theme.css clears its own:\n'
  + ' * Arena has three breakpoints, so a consumer gets three variants and no xl. */';

export async function buildBreakpointTheme() {
  const lines = [];
  for (const item of walk(await load('spacing.json'))) {
    if (item.group || !/^bp-/.test(item.token.name)) continue;
    lines.push(`  --breakpoint-${item.token.name.slice(3)}:${serialize(item.token)};`);
  }
  return `${BREAKPOINT_HEADER}\n@theme {\n  --breakpoint-*: initial;\n${lines.join('\n')}\n}\n`;
}

const SCRIPT_HEADER =
  '/* GENERATED by scripts/generate/arena/generate-tokens.ts — edit contracts/design/, not this file.\n'
  + ' *\n'
  + ' * Every export here is a token flagged script-readable in contracts/design/ and\n'
  + ' * emitted as a bare number because JS arithmetic consumes it. Each one also\n'
  + ' * ships as a CSS custom property; scripts/check/arena/check-script-tokens.ts asserts the\n'
  + ' * two carry the same value. A value bound at import time cannot re-theme or\n'
  + ' * re-densify — that is the accepted price of reading it in JS at all. */';

const isScript = (token: DtcgToken) => token.$extensions?.[EXT]?.script === true;

function scriptSources() {
  return [...new Set(FILES.flatMap((f) => f.blocks.map((b) => b.source)))];
}

export async function collectScriptTokens() {
  const out = [];
  for (const source of scriptSources()) {
    for (const item of walk(await load(source))) {
      if (item.group || !isScript(item.token)) continue;
      out.push({
        cssName: item.token.name,
        jsName: scriptName(item.token.name),
        value: serializeScript(item.token),
        $description: item.token.$description,
        groups: item.groups,
      });
    }
  }
  return out;
}

async function catSlotCount() {
  let n = 0;
  for (const item of walk(await load('palette.dark.json'))) {
    if (!item.group && /^color-cat-\d+$/.test(item.token.name)) n += 1;
  }
  return n;
}

export async function buildScriptModules() {
  const tokens = await collectScriptTokens();
  const lines = [SCRIPT_HEADER, ''];
  let emitted = null;
  for (const t of tokens) {
    const groups = (t.groups ?? []).join('\n');
    if (groups && groups !== emitted) {
      if (lines.at(-1) !== '') lines.push('');
      lines.push(...comment(groups).split('\n').map((l) => l.replace(/^ {2}/, '')));
    }
    emitted = groups;
    if (t.$description) lines.push(...comment(t.$description).split('\n').map((l) => l.replace(/^ {2}/, '')));
    lines.push(`export const ${t.jsName} = ${t.value};`);
  }
  lines.push(
    '',
    '/* Derived, not authored: the number of --color-cat-* slots in',
    ' * contracts/design/palette.dark.json. Assigned in order and NEVER cycled -- a 9th',
    ' * series folds to "Other", small multiples, or direct labels. */',
    `export const catSlots = ${await catSlotCount()};`,
  );
  const body = `${lines.join('\n')}\n`;
  return new Map(SCRIPT_TARGETS.map((path) => [path, body]));
}

async function load(source: string) {
  const path = (s: string) => join(root, 'contracts/design', s);
  const sd = new StyleDictionary({
    source: [...((RESOLVES_AGAINST as Record<string, string[]>)[source] ?? []).map(path), path(source)],
    platforms: { css: { transforms: ['name/kebab'] } },
  }, { verbosity: 'silent' });
  const { tokens } = await sd.getPlatformTokens('css');
  return { tokens, from: path(source) };
}

function comment(d: string) {
  if (!d.includes('\n')) return `  /* ${d} */`;
  return ['  /*', ...d.split('\n').map((l: string) => `     ${l}`), '   */'].join('\n');
}

function render(token: DtcgToken) {
  const decl = `  --${token.name}:${serialize(token)};`;
  const d = token.$description;
  if (!d) return decl;
  if (!d.includes('\n')) return `${decl} /* ${d} */`;
  return `${comment(d)}\n${decl}`;
}

function holdsA(node: DtcgNode, from: string): boolean {
  for (const [, child] of childEntries(node)) {
    if (isToken(child) ? child.filePath === from : holdsA(child, from)) return true;
  }
  return false;
}

type Emitted = {
  group: boolean;
  description?: string;
  token?: DtcgToken;
  groups?: string[];
};

function* walk({ tokens, from }: { tokens: any; from: string },
  groups: string[] = []): Generator<Emitted> {
  for (const [, child] of childEntries(tokens)) {
    if (isToken(child)) {
      if (child.filePath === from) yield { group: false, token: child, groups };
      continue;
    }
    if (!child.$description) { yield* walk({ tokens: child, from }, groups); continue; }
    if (!holdsA(child, from)) continue;
    yield { group: true, description: child.$description };
    yield* walk({ tokens: child, from }, [...groups, child.$description]);
  }
}

async function block({ selector, source }: { selector: string; source: string }) {
  const lines = [];
  for (const item of walk(await load(source))) {
    if (!item.group) { lines.push(render(item.token)); continue; }
    if (lines.length) lines.push('');
    lines.push(comment(item.description));
  }
  return `${selector}{\n${lines.join('\n')}\n}`;
}

export async function buildAll() {
  const out = new Map();
  for (const file of FILES) {
    const blocks = [];
    for (const b of file.blocks) blocks.push(await block(b));
    out.set(file.out, `${HEADER}\n${blocks.join('\n')}\n`);
  }
  return out;
}

async function main() {
  const built = await buildAll();
  for (const [name, css] of built) {
    writeFileSync(join(root, 'contracts/design-generated', name), css);
    console.log(`build-tokens: wrote contracts/design-generated/${name}`);
  }
  const modules = await buildScriptModules();
  for (const [path, source] of modules) {
    writeFileSync(join(root, path), source);
    console.log(`build-tokens: wrote ${path}`);
  }
  writeFileSync(join(root, BREAKPOINT_TARGET), await buildBreakpointTheme());
  console.log(`build-tokens: wrote ${BREAKPOINT_TARGET}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
