/* GENERATED-file writer. Emits frameworks/Catalog.generated.md, the one document that
 * answers "which components exist, what does each do, which layers ship it, what does it
 * take" in a single read. Every column is derived, so nothing here is a second copy of a
 * fact: the catalog cannot disagree with the contracts, and check:catalog fails when it
 * drifts. It is tracked because the Claude Code plugin is served from the git tag, where
 * nothing runs a build. */

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { repoRoot as root } from '../../lib/arena/repo-root.mjs';
import { LAYERS, kebab } from '../../lib/arena/layers.mjs';
import { bindingCases } from '../../lib/arena/behaviour-contracts.mjs';

export const CATALOG_TARGET = 'frameworks/Catalog.generated.md';

export const CATALOG_LAYERS = LAYERS.filter((layer) => layer !== 'tailwind');

const HEADER = `<!-- GENERATED by scripts/generate/arena/generate-catalog.mjs. Edit the contracts, not this file. -->

# Arena component catalog

Every component Arena ships, in one read. **This page is an index, not a manual.** It says
what exists and what each one takes; how to use one is its own \`.prompt.md\`, linked in the
last column.

- **Takes** is the members its API contract declares, in contract order. A member marked
  \`*\` is required. Types, defaults and the reason each member exists are in
  \`contracts/api/components/<Name>.json\`.
- **Behaviour** is the accessibility pattern the component binds, from
  \`contracts/behaviour/\`. \`none\` means no pattern applies, which is a claim the binding
  argues rather than an omission.
- **Usage** links each layer's own prompt, and so is also the record of which layers
  implement the component today.

Import every component from its layer's package root: \`@dravensoft/arena-react\` or
\`@dravensoft/arena-angular\`. Icons are Phosphor class-name strings and never elements.
`;

export function loadCategories(base = root) {
  return JSON.parse(readFileSync(join(base, 'frameworks/Components.json'), 'utf8'));
}

export function loadContract(component, base = root) {
  const path = join(base, 'contracts/api/components', `${component}.json`);
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function componentDir(layer, category, component) {
  return join('frameworks', layer, 'components', category, kebab(component));
}

export function layersFor(category, component, base = root) {
  return CATALOG_LAYERS.filter((layer) => existsSync(join(base, componentDir(layer, category, component))));
}

export function promptLink(layer, category, component) {
  const path = `${componentDir(layer, category, component)}/${component}.prompt.md`.split('\\').join('/');
  return `[${layer}](./${path.replace(/^frameworks\//, '')})`;
}

export function memberList(contract) {
  if (!contract) return [];
  return Object.entries(contract.api ?? {}).map(([name, member]) => (member.required ? `${name}*` : name));
}

export function patternsFor(category, component, layers, base = root) {
  const found = new Map();
  for (const layer of layers) {
    const path = join(base, componentDir(layer, category, component), `${component}.behaviour.json`);
    if (!existsSync(path)) continue;
    const binding = JSON.parse(readFileSync(path, 'utf8'));
    for (const one of bindingCases(binding)) {
      if (!found.has(one.pattern)) found.set(one.pattern, new Set());
      found.get(one.pattern).add(layer);
    }
  }
  return found;
}

export function renderPatterns(found, layers) {
  const names = [...found.keys()].sort();
  if (names.length === 0) return '';
  const everywhere = (pattern) => layers.every((layer) => found.get(pattern).has(layer));
  return names
    .map((pattern) => (everywhere(pattern) ? pattern : `${pattern} (${[...found.get(pattern)].sort().join(', ')})`))
    .join(', ');
}

export function escapeCell(text) {
  return String(text).split('|').join('\\|').split('\n').join(' ');
}

export function rowsFor(category, components, base = root) {
  return components.map((component) => {
    const layers = layersFor(category, component, base);
    const contract = loadContract(component, base);
    return {
      component,
      category,
      description: contract?.description ?? '',
      layers,
      members: memberList(contract),
      patterns: renderPatterns(patternsFor(category, component, layers, base), layers),
      prompts: layers.map((layer) => promptLink(layer, category, component)),
    };
  });
}

export function renderRow(row) {
  return `| \`${row.component}\` | ${escapeCell(row.description)} | ${
    row.members.map((m) => `\`${m}\``).join(' ') || '(no members)'
  } | ${row.patterns || '(undeclared)'} | ${row.prompts.join(' · ') || '(no layer)'} |`;
}

export function renderCatalog(base = root) {
  const categories = loadCategories(base);
  const out = [HEADER];
  let count = 0;

  for (const category of Object.keys(categories).sort()) {
    const rows = rowsFor(category, [...categories[category]].sort(), base);
    count += rows.length;
    out.push('');
    out.push(`## ${category}`);
    out.push('');
    out.push('| Component | What it is | Takes | Behaviour | Usage |');
    out.push('|---|---|---|---|---|');
    for (const row of rows) out.push(renderRow(row));
  }

  if (count === 0) throw new Error('renderCatalog: frameworks/Components.json declared no component, and a catalog of nothing indexes nothing');

  out.push('');
  out.push(`${count} components across ${Object.keys(categories).length} categories.`);
  out.push('');
  return out.join('\n');
}

function main() {
  const path = join(root, CATALOG_TARGET);
  writeFileSync(path, renderCatalog());
  console.log(`generate-catalog: wrote ${CATALOG_TARGET}`);
}

if (process.argv[1] && process.argv[1].endsWith('generate-catalog.mjs')) main();
