import StyleDictionary from 'style-dictionary';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { serialize } from '../../lib/serialize-token.mjs';
import { serializeScript, scriptName } from '../../lib/serialize-script.mjs';
import { repoRoot as root } from '../../lib/repo-root.mjs';

const HEADER = '/* GENERATED by Style Dictionary — edit contracts/design/, not this file. */';

export const FILES = [
  { out: 'palette.css', blocks: [
    { selector: ':root', source: 'palette.dark.json' },
    { selector: '.arena-light', source: 'palette.light.json' },
  ] },
  { out: 'typography.css', blocks: [
    { selector: ':root', source: 'typography.json' },
  ] },
  { out: 'spacing.css', blocks: [
    { selector: ':root', source: 'spacing.json' },
    { selector: ':root', source: 'icon.json' },
    { selector: ':root', source: 'component.json' },
    { selector: '.arena-compact', source: 'density.compact.json' },
  ] },
  { out: 'effects.css', blocks: [
    { selector: ':root', source: 'effects.json' },
    { selector: ':root', source: 'layering.json' },
    { selector: ':root', source: 'chart.json' },
    { selector: ':root', source: 'behaviour.json' },
  ] },
];

const EXT = 'com.dravensoft.arena';

export const SCRIPT_TARGETS = [
  'frameworks/react/Tokens.generated.js',
  'frameworks/angular/Tokens.generated.ts',
];

const SCRIPT_HEADER =
  '/* GENERATED by scripts/build-tokens.mjs — edit contracts/design/, not this file.\n'
  + ' *\n'
  + ' * Every export here is a token flagged script-readable in contracts/design/ and\n'
  + ' * emitted as a bare number because JS arithmetic consumes it. Each one also\n'
  + ' * ships as a CSS custom property; scripts/check-script-tokens.mjs asserts the\n'
  + ' * two carry the same value. A value bound at import time cannot re-theme or\n'
  + ' * re-densify — that is the accepted price of reading it in JS at all. */';

const isScript = (token) => token.$extensions?.[EXT]?.script === true;

function scriptSources() {
  return [...new Set(FILES.flatMap((f) => f.blocks.map((b) => b.source)))];
}

export async function collectScriptTokens() {
  const out = [];
  for (const source of scriptSources()) {
    for (const item of walk(await load(source))) {
      if (item.group || !isScript(item.token)) continue;
      out.push({
        cssName: item.token.name,
        jsName: scriptName(item.token.name),
        value: serializeScript(item.token),
        $description: item.token.$description,
      });
    }
  }
  return out;
}

async function catSlotCount() {
  let n = 0;
  for (const item of walk(await load('palette.dark.json'))) {
    if (!item.group && /^color-cat-\d+$/.test(item.token.name)) n += 1;
  }
  return n;
}

export async function buildScriptModules() {
  const tokens = await collectScriptTokens();
  const lines = [SCRIPT_HEADER, ''];
  for (const t of tokens) {
    if (t.$description) lines.push(...comment(t.$description).split('\n').map((l) => l.replace(/^ {2}/, '')));
    lines.push(`export const ${t.jsName} = ${t.value};`);
  }
  lines.push(
    '',
    '/* Derived, not authored: the number of --color-cat-* slots in',
    ' * contracts/design/palette.dark.json. Assigned in order and NEVER cycled -- a 9th',
    ' * series folds to "Other", small multiples, or direct labels. */',
    `export const catSlots = ${await catSlotCount()};`,
  );
  const body = `${lines.join('\n')}\n`;
  return new Map(SCRIPT_TARGETS.map((path) => [path, body]));
}

async function load(source) {
  const sd = new StyleDictionary({
    source: [join(root, 'contracts/design', source)],
    platforms: { css: { transforms: ['name/kebab'] } },
  }, { verbosity: 'silent' });
  const { tokens } = await sd.getPlatformTokens('css');
  return tokens;
}

function comment(d) {
  if (!d.includes('\n')) return `  /* ${d} */`;
  return ['  /*', ...d.split('\n').map((l) => `     ${l}`), '   */'].join('\n');
}

function render(token) {
  const decl = `  --${token.name}:${serialize(token)};`;
  const d = token.$description;
  if (!d) return decl;
  if (!d.includes('\n')) return `${decl} /* ${d} */`;
  return `${comment(d)}\n${decl}`;
}

function* walk(node) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$') || child === null || typeof child !== 'object') continue;
    if (child.$value !== undefined) { yield { group: false, token: child }; continue; }
    if (child.$description) yield { group: true, description: child.$description };
    yield* walk(child);
  }
}

async function block({ selector, source }) {
  const lines = [];
  for (const item of walk(await load(source))) {
    if (!item.group) { lines.push(render(item.token)); continue; }
    if (lines.length) lines.push('');
    lines.push(comment(item.description));
  }
  return `${selector}{\n${lines.join('\n')}\n}`;
}

export async function buildAll() {
  const out = new Map();
  for (const file of FILES) {
    const blocks = [];
    for (const b of file.blocks) blocks.push(await block(b));
    out.set(file.out, `${HEADER}\n${blocks.join('\n')}\n`);
  }
  return out;
}

async function main() {
  const built = await buildAll();
  for (const [name, css] of built) {
    writeFileSync(join(root, 'contracts/design-generated', name), css);
    console.log(`build-tokens: wrote contracts/design-generated/${name}`);
  }
  const modules = await buildScriptModules();
  for (const [path, source] of modules) {
    writeFileSync(join(root, path), source);
    console.log(`build-tokens: wrote ${path}`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
