/* GENERATED by scripts/build/react/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
import { Button } from "../../components/forms/button/Button.js";
import { Input } from "../../components/forms/input/Input.js";
import { AppLogo } from "../../components/brand/app-logo/AppLogo.js";
import { UnauthCard } from "../../components/display/unauth-card/UnauthCard.js";
export function LoginScreen({ onLogin }) {
  const [email, setEmail] = useState("ana@dravensoft.dev");
  const [password, setPassword] = useState("dravensoft");
  return React.createElement("div", {
    style: {
      minHeight: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: "var(--bg)",
      padding: "calc(var(--sp-1) * 6)"
    }
  }, React.createElement(UnauthCard, {
    brand: React.createElement(AppLogo, {
      size: "md",
      mark: React.createElement("img", {
        src: "../../../../assets/rotor-crimson.svg",
        alt: ""
      }),
      name: "Draven",
      dim: "soft"
    }),
    eyebrow: "Delivery console",
    title: "Welcome back",
    footer: "Forgot your password?"
  }, React.createElement("div", {
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 4)" }
  }, React.createElement(Input, {
    label: "Email",
    value: email,
    onChange: setEmail
  }), React.createElement(Input, {
    label: "Password",
    type: "password",
    value: password,
    onChange: setPassword
  }), React.createElement(Button, {
    variant: "primary",
    full: true,
    onClick: onLogin
  }, "Sign in"))));
}
