/* GENERATED by scripts/build-tailwind.mjs — edit ChartCard.manifest.json, not this file. */
export default {
  "component": "ChartCard",
  "slots": {
    "root": "flex flex-col gap-3 bg-base-200 border-[length:var(--bw)] border-base-300 rounded-lg p-5",
    "head": "flex items-center justify-between gap-3",
    "title": "font-mono text-ctl-2xs tracking-label uppercase text-base-content/62",
    "actions": "flex items-center gap-2"
  }
} as const;
