/* frameworks/angular/fonts/fetch-fonts.mjs
   Downloads the latin-subset woff2 binaries for Arena's three families and
   (re)generates fonts.css with local url()s only — no CDN request, CSP-clean.
   The binaries are git-ignored; this script and fonts.css are the source of
   truth. Run: node frameworks/angular/fonts/fetch-fonts.mjs */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/* A modern-browser UA makes Google Fonts serve woff2 (not ttf). */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  { css: 'Archivo',           slug: 'archivo',           weights: [400, 500, 600, 700, 800, 900] },
  { css: 'Familjen Grotesk',  slug: 'familjen-grotesk',  weights: [400, 500, 600, 700] },
  { css: 'Spline Sans Mono',  slug: 'spline-sans-mono',  weights: [400, 500, 600, 700] },
];

async function google(css, weights) {
  const family = `${css.replace(/ /g, '+')}:wght@${weights.join(';')}`;
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`CSS fetch failed for ${css}: ${res.status}`);
  return res.text();
}

/* Pull the latin-subset @font-face blocks: each is preceded by a `/* latin *​/`
   comment and carries a font-weight + a woff2 src url. */
function latinFaces(cssText) {
  const faces = [];
  const re = /\/\*\s*latin\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(cssText)) !== null) {
    const block = m[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const src = /src:\s*url\(([^)]+\.woff2)\)/.exec(block)?.[1];
    if (weight && src) faces.push({ weight: Number(weight), src });
  }
  return faces;
}

async function download(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`binary fetch failed: ${url} ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

const rules = [];
for (const fam of FAMILIES) {
  const cssText = await google(fam.css, fam.weights);
  const faces = latinFaces(cssText);
  for (const face of faces) {
    const file = `${fam.slug}-${face.weight}.woff2`;
    writeFileSync(join(here, file), await download(face.src));
    rules.push(
      `@font-face {\n` +
        `  font-family: '${fam.css}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${face.weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('./${file}') format('woff2');\n` +
        `}`
    );
  }
  console.log(`${fam.css}: ${faces.length} weights`);
}

const header =
  `/* frameworks/angular/fonts/fonts.css — self-hosted, CSP-clean.\n` +
  `   GENERATED by fetch-fonts.mjs; edit that, not this. Families match\n` +
  `   tokens/typography.css (Archivo / Familjen Grotesk / Spline Sans Mono). */\n`;
writeFileSync(join(here, 'fonts.css'), `${header}\n${rules.join('\n\n')}\n`);
console.log('wrote fonts.css');
