/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function Breadcrumbs({ items = [], separator = "/", style }) {
  return React.createElement("nav", {
    "aria-label": "Breadcrumb",
    style: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: "calc(var(--sp-1) * 2)", ...style }
  }, items.map((it, i) => {
    const last = i === items.length - 1;
    const common = { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", letterSpacing: "var(--ls-mono-nav)" };
    return React.createElement(React.Fragment, {
      key: i
    }, last ? React.createElement("span", {
      "aria-current": "page",
      style: { ...common, color: "var(--bone)", fontWeight: "var(--fw-bold)" }
    }, it.label) : React.createElement("a", {
      href: it.href || "#",
      onClick: it.onClick,
      style: { ...common, color: "var(--mute)", textDecoration: "none", cursor: "pointer", transition: "color var(--dur-fast) var(--ease-out)" },
      onMouseEnter: (e) => e.currentTarget.style.color = "var(--bone-dim)",
      onMouseLeave: (e) => e.currentTarget.style.color = "var(--mute)"
    }, it.label), !last && React.createElement("span", {
      "aria-hidden": "true",
      style: { color: "var(--line-strong)", fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)" }
    }, separator));
  }));
}
