/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function BulkActionBar({ count, noun = "items", actions, onRun, onClear, clearable = true }) {
  if (count == null)
    throw new Error("BulkActionBar: `count` is required");
  if (actions == null)
    throw new Error("BulkActionBar: `actions` is required");
  if (!count)
    return null;
  return React.createElement("div", {
    role: "region",
    "aria-label": "Actions on the selection",
    style: {
      display: "flex",
      alignItems: "center",
      gap: "calc(var(--sp-1) * 3.5)",
      minHeight: "calc(var(--sp-1) * 13)",
      padding: "0 calc(var(--sp-1) * 3) 0 calc(var(--sp-1) * 4)",
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--line-strong)",
      borderRadius: "var(--r-md)",
      boxShadow: "var(--shadow-2)"
    }
  }, React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", letterSpacing: "var(--ls-mono-nav)", color: "var(--bone)" }
  }, React.createElement("b", {
    style: { color: "var(--gold)" }
  }, count), " ", noun, " selected"), React.createElement("span", {
    style: { width: "var(--bw)", height: "calc(var(--sp-1) * 5.5)", background: "var(--color-base-300)" }
  }), React.createElement("div", {
    style: { display: "flex", alignItems: "center", gap: "calc(var(--sp-1) * 1.5)", flex: 1, flexWrap: "wrap" }
  }, actions.map((a, i) => React.createElement("button", {
    key: i,
    onClick: () => onRun && onRun(a),
    style: {
      display: "inline-flex",
      alignItems: "center",
      gap: "calc(var(--sp-1) * 2)",
      height: "calc(var(--sp-1) * 8.5)",
      padding: "0 calc(var(--sp-1) * 3)",
      background: "transparent",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-sm)",
      cursor: "pointer",
      fontFamily: "var(--font-body)",
      fontWeight: "var(--fw-semibold)",
      fontSize: "var(--dz-text-md)",
      color: a.destructive ? "var(--danger)" : "var(--bone-dim)",
      transition: "background var(--dur-fast) var(--ease-out)"
    },
    onMouseEnter: (e) => e.currentTarget.style.background = "var(--panel)",
    onMouseLeave: (e) => e.currentTarget.style.background = "transparent"
  }, a.icon && React.createElement("span", {
    style: { fontSize: "var(--icon-md)", display: "inline-flex" }
  }, React.createElement("i", {
    className: a.icon,
    "aria-hidden": "true"
  })), a.label))), clearable && React.createElement("button", {
    onClick: () => onClear && onClear(),
    "aria-label": "Clear selection",
    style: {
      background: "none",
      border: "none",
      cursor: "pointer",
      color: "var(--mute)",
      fontFamily: "var(--font-mono)",
      fontSize: "var(--dz-text-xs)",
      letterSpacing: "var(--ls-badge)",
      textTransform: "uppercase"
    }
  }, "Clear"));
}
