/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { CommandPalette } from "../../components/navigation/CommandPalette.js";
import { Button } from "../../components/forms/Button.js";
const commands = [
  { id: "deploy", label: "Deploy to production", hint: "client portal", icon: React.createElement("i", {
    className: "ph-bold ph-rocket-launch"
  }), shortcut: "⌘D" },
  { id: "logs", label: "View build logs", hint: "build 4821", icon: React.createElement("i", {
    className: "ph-bold ph-terminal-window"
  }) },
  { id: "new", label: "New project", icon: React.createElement("i", {
    className: "ph-bold ph-plus-circle"
  }), shortcut: "⌘N" },
  { id: "invite", label: "Invite teammate", hint: "members settings", icon: React.createElement("i", {
    className: "ph-bold ph-user-plus"
  }) },
  { id: "theme", label: "Toggle theme", icon: React.createElement("i", {
    className: "ph-bold ph-moon"
  }) },
  { id: "docs", label: "Open documentation", hint: "arena design system", icon: React.createElement("i", {
    className: "ph-bold ph-book-open"
  }) }
];
function Demo() {
  const [open, setOpen] = React.useState(true);
  React.useEffect(() => {
    const h = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setOpen(true);
      }
    };
    window.addEventListener("keydown", h);
    return () => window.removeEventListener("keydown", h);
  }, []);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Press Cmd/Ctrl+K · arrows to move · Enter to run · Esc to close"), React.createElement(Button, {
    variant: "secondary",
    size: "sm",
    onClick: () => setOpen(true)
  }, "Open palette"), React.createElement(CommandPalette, {
    open,
    onClose: () => setOpen(false),
    commands
  }));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
