/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState, useRef, useEffect } from "react";
let injected = false;
function useMenuKeyframes() {
  useEffect(() => {
    if (injected || typeof document === "undefined")
      return;
    injected = true;
    const s = document.createElement("style");
    s.setAttribute("data-arena-menu", "");
    s.textContent = "@keyframes arena-menu{from{opacity:0;transform:translateY(calc(var(--sp-1) * -1))}to{opacity:1;transform:none}}" + "@media (prefers-reduced-motion:reduce){@keyframes arena-menu{from{opacity:0}to{opacity:1}}}";
    document.head.appendChild(s);
  }, []);
}
export function Menu({ trigger, items = [], align = "start", style }) {
  useMenuKeyframes();
  const [open, setOpen] = useState(false);
  const ref = useRef(null);
  useEffect(() => {
    if (!open)
      return;
    const onDoc = (e) => {
      if (ref.current && !ref.current.contains(e.target))
        setOpen(false);
    };
    const onKey = (e) => {
      if (e.key === "Escape")
        setOpen(false);
    };
    document.addEventListener("mousedown", onDoc);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDoc);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);
  const run = (it) => {
    if (it.disabled)
      return;
    setOpen(false);
    it.onClick && it.onClick();
  };
  return React.createElement("div", {
    ref,
    style: { position: "relative", display: "inline-flex", ...style }
  }, React.createElement("span", {
    onClick: () => setOpen((v) => !v),
    "aria-haspopup": "menu",
    "aria-expanded": open
  }, trigger), open && React.createElement("div", {
    role: "menu",
    style: {
      position: "absolute",
      top: "calc(100% + calc(var(--sp-1) * 1.5))",
      [align === "end" ? "right" : "left"]: 0,
      zIndex: "var(--z-dropdown)",
      minWidth: "calc(var(--sp-1) * 50)",
      padding: "calc(var(--sp-1) * 1.5)",
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--line-strong)",
      borderRadius: "var(--r-md)",
      boxShadow: "var(--shadow-2)",
      animation: "arena-menu var(--dur-fast) var(--ease-out)"
    }
  }, items.map((it, i) => {
    if (it.divider)
      return React.createElement("div", {
        key: i,
        style: { height: "var(--bw)", background: "var(--color-base-300)", margin: "calc(var(--sp-1) * 1) 0" }
      });
    if (it.header)
      return React.createElement("div", {
        key: i,
        style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-2xs)", letterSpacing: "var(--ls-field-label)", textTransform: "uppercase", color: "var(--mute)", padding: "calc(var(--sp-1) * 2) calc(var(--sp-1) * 2.5) calc(var(--sp-1) * 1)" }
      }, it.header);
    return React.createElement(MenuItem, {
      key: i,
      item: it,
      onRun: () => run(it)
    });
  })));
}
function MenuItem({ item, onRun }) {
  const [hover, setHover] = useState(false);
  const color = item.destructive ? "var(--danger)" : "var(--bone-dim)";
  const bg = hover && !item.disabled ? item.destructive ? "var(--danger-soft)" : "var(--crimson-soft)" : "transparent";
  return React.createElement("button", {
    role: "menuitem",
    onClick: onRun,
    disabled: item.disabled,
    onMouseEnter: () => setHover(true),
    onMouseLeave: () => setHover(false),
    style: {
      display: "flex",
      alignItems: "center",
      gap: "calc(var(--sp-1) * 2.5)",
      width: "100%",
      textAlign: "left",
      padding: "calc(var(--sp-1) * 2) calc(var(--sp-1) * 2.5)",
      border: "none",
      borderRadius: "var(--r-sm)",
      cursor: item.disabled ? "not-allowed" : "pointer",
      background: bg,
      color: item.disabled ? "var(--mute)" : hover && !item.destructive ? "var(--crimson)" : color,
      opacity: item.disabled ? 0.6 : 1,
      fontFamily: "var(--font-body)",
      fontSize: "var(--fs-md)"
    }
  }, item.icon && React.createElement("span", {
    style: { fontSize: "var(--icon-md)", display: "inline-flex" }
  }, item.icon), React.createElement("span", {
    style: { flex: 1 }
  }, item.label), item.shortcut && React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", color: "var(--mute)" }
  }, item.shortcut));
}
