/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Menu } from "../../components/navigation/Menu.js";
import { Pagination } from "../../components/navigation/Pagination.js";
import { IconButton } from "../../components/forms/IconButton.js";
import { Button } from "../../components/forms/Button.js";
function Demo() {
  const [p, setP] = React.useState(3);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub",
    style: { marginBottom: 12 }
  }, "Menu — actions / overflow"), React.createElement("div", {
    className: "row",
    style: { alignItems: "center" }
  }, React.createElement(Menu, {
    trigger: React.createElement(Button, {
      variant: "secondary",
      iconRight: React.createElement("i", {
        className: "ph-bold ph-caret-down"
      })
    }, "Actions"),
    items: [
      { header: "Deployment" },
      { label: "View logs", icon: React.createElement("i", {
        className: "ph-bold ph-scroll"
      }), onClick: () => {} },
      { label: "Duplicate", icon: React.createElement("i", {
        className: "ph-bold ph-copy"
      }), shortcut: "⌘D", onClick: () => {} },
      { divider: true },
      { label: "Delete", icon: React.createElement("i", {
        className: "ph-bold ph-trash"
      }), destructive: true, onClick: () => {} }
    ]
  }), React.createElement(Menu, {
    align: "end",
    trigger: React.createElement(IconButton, {
      label: "More options"
    }, React.createElement("i", {
      className: "ph-bold ph-dots-three-vertical"
    })),
    items: [
      { label: "Rename", icon: React.createElement("i", {
        className: "ph-bold ph-pencil-simple"
      }), onClick: () => {} },
      { label: "Archive", icon: React.createElement("i", {
        className: "ph-bold ph-archive"
      }), onClick: () => {} }
    ]
  })), React.createElement("div", {
    className: "sub",
    style: { marginBottom: 12 }
  }, "Pagination"), React.createElement(Pagination, {
    page: p,
    pageCount: 12,
    onChange: setP
  }));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
