/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Menu } from "../../components/navigation/Menu.js";
import { Pagination } from "../../components/navigation/Pagination.js";
import { IconButton } from "../../components/forms/IconButton.js";
import { Button } from "../../components/forms/Button.js";
function Demo() {
  const [p, setP] = React.useState(3);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub",
    style: { marginBottom: "var(--sp-3)" }
  }, "Menu — actions / overflow"), React.createElement("div", {
    className: "row",
    style: { alignItems: "center" }
  }, React.createElement(Menu, {
    trigger: React.createElement(Button, {
      variant: "secondary",
      iconRight: "ph-bold ph-caret-down"
    }, "Actions"),
    onSelect: () => {},
    items: [
      { header: "Deployment" },
      { label: "View logs", icon: "ph-bold ph-scroll" },
      { label: "Duplicate", icon: "ph-bold ph-copy", shortcut: "⌘D" },
      { divider: true },
      { label: "Delete", icon: "ph-bold ph-trash", destructive: true }
    ]
  }), React.createElement(Menu, {
    align: "end",
    trigger: React.createElement(IconButton, {
      label: "More options",
      icon: "ph-bold ph-dots-three-vertical"
    }),
    onSelect: () => {},
    items: [
      { label: "Rename", icon: "ph-bold ph-pencil-simple" },
      { label: "Archive", icon: "ph-bold ph-archive" }
    ]
  })), React.createElement("div", {
    className: "sub",
    style: { marginBottom: "var(--sp-3)" }
  }, "Pagination"), React.createElement(Pagination, {
    page: p,
    pageCount: 12,
    onChange: setP
  }));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
