/* GENERATED by scripts/build/react/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Tabs } from "./tabs/Tabs.js";
import { Tab } from "./tab/Tab.js";
import { SegmentedControl } from "./segmented-control/SegmentedControl.js";
import { PageHead } from "./page-head/PageHead.js";
import { Breadcrumbs } from "./breadcrumbs/Breadcrumbs.js";
import { SideNav } from "./side-nav/SideNav.js";
import { SideNavItem } from "./side-nav-item/SideNavItem.js";
import { SideNavSection } from "./side-nav-section/SideNavSection.js";
import { SideNavCollapsible } from "./side-nav-collapsible/SideNavCollapsible.js";
import { BulkActionBar } from "./bulk-action-bar/BulkActionBar.js";
import { Button } from "../forms/button/Button.js";
function Demo() {
  const [v, setV] = React.useState("Overview");
  const [range, setRange] = React.useState("7d");
  const [sel, setSel] = React.useState(3);
  return React.createElement("div", null, React.createElement(Tabs, {
    value: v,
    onChange: setV
  }, React.createElement(Tab, {
    value: "Overview",
    label: "Overview"
  }, React.createElement("div", {
    style: { color: "var(--bone-dim)", fontSize: "var(--dz-text)", lineHeight: "var(--lh-body)" }
  }, "Uptime 99.98% · p95 186 ms · 0 open incidents.")), React.createElement(Tab, {
    value: "Deployments",
    label: "Deployments"
  }, React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", color: "var(--mute)" }
  }, "#4821 → Production · CI · main · 3m 41s")), React.createElement(Tab, {
    value: "Activity",
    label: "Activity"
  }, React.createElement("div", {
    style: { color: "var(--bone-dim)", fontSize: "var(--dz-text)", lineHeight: "var(--lh-body)" }
  }, "ana@ approved the release · 2h ago")), React.createElement(Tab, {
    value: "Settings",
    label: "Settings"
  }, React.createElement("div", {
    style: { color: "var(--bone-dim)", fontSize: "var(--dz-text)", lineHeight: "var(--lh-body)" }
  }, "Auto-deploy on approval — enabled."))), React.createElement("div", {
    className: "row",
    style: { marginTop: "calc(var(--sp-1) * 3.5)" }
  }, React.createElement("div", {
    className: "sub"
  }, "SegmentedControl — filters inside the tab, never navigates"), React.createElement(SegmentedControl, {
    ariaLabel: "Time range",
    options: [{ value: "24h", label: "24h" }, { value: "7d", label: "7d" }, { value: "30d", label: "30d" }],
    value: range,
    onChange: setRange
  }), React.createElement("span", {
    style: { color: "var(--mute)", fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)" }
  }, "Active view: ", React.createElement("span", {
    style: { color: "var(--gold)" }
  }, v), " · Range: ", React.createElement("span", {
    style: { color: "var(--gold)" }
  }, range))), React.createElement("div", {
    className: "sub"
  }, "Breadcrumbs — the last item is the current location"), React.createElement("div", {
    className: "row"
  }, React.createElement(Breadcrumbs, {
    ariaLabel: "Project navigation",
    items: [{ label: "Projects", href: "#" }, { label: "Client Portal", href: "#" }, { label: "Deployments" }]
  })), React.createElement("div", {
    className: "sub"
  }, "SideNav — sections group, collapsibles disclose, the active item is aria-current"), React.createElement("div", {
    style: { width: "var(--layout-sidebar)", marginBottom: "var(--sp-4)" }
  }, React.createElement(SideNav, {
    ariaLabel: "Primary",
    active: "prod"
  }, React.createElement(SideNavItem, {
    id: "dashboard",
    icon: "ph-bold ph-squares-four",
    label: "Projects",
    href: "#projects"
  }), React.createElement(SideNavSection, {
    label: "Workspace"
  }, React.createElement(SideNavCollapsible, {
    id: "deploys",
    icon: "ph-bold ph-rocket-launch",
    label: "Deployments"
  }, React.createElement(SideNavItem, {
    id: "prod",
    label: "Production",
    href: "#prod"
  }), React.createElement(SideNavItem, {
    id: "staging",
    label: "Staging",
    href: "#staging"
  })), React.createElement(SideNavItem, {
    id: "settings",
    icon: "ph-bold ph-gear-six",
    label: "Settings"
  })))), React.createElement("div", {
    className: "sub"
  }, "PageHead"), React.createElement("div", {
    style: { marginBottom: "var(--sp-4)" }
  }, React.createElement(PageHead, {
    title: "Client Portal",
    subtitle: "Last published 2 h ago · build #4821",
    actions: React.createElement(React.Fragment, null, React.createElement(Button, {
      variant: "secondary",
      size: "sm"
    }, "View logs"), React.createElement(Button, {
      variant: "primary",
      size: "sm"
    }, "Deploy"))
  })), React.createElement("div", {
    className: "sub"
  }, "BulkActionBar — destructive stays outline, never filled"), React.createElement("div", {
    className: "row",
    style: { width: "100%" }
  }, React.createElement(BulkActionBar, {
    count: sel,
    noun: "deployments",
    onClear: () => setSel(0),
    onRun: () => {},
    actions: [
      { id: "rerun", label: "Re-run", icon: "ph-bold ph-arrow-clockwise" },
      { id: "archive", label: "Archive", icon: "ph-bold ph-archive" },
      { id: "delete", label: "Delete", icon: "ph-bold ph-trash", destructive: true }
    ]
  }), sel === 0 && React.createElement("button", {
    onClick: () => setSel(3),
    style: { background: "none", border: "var(--bw) solid var(--color-base-300)", borderRadius: "var(--r-sm)", color: "var(--mute)", cursor: "pointer", fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-badge)", textTransform: "uppercase", padding: "var(--sp-2) var(--sp-3)" }
  }, "Restore selection")));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
