/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Tabs } from "../../components/navigation/Tabs.js";
import { SegmentedControl } from "../../components/navigation/SegmentedControl.js";
import { PageHead } from "../../components/navigation/PageHead.js";
import { Breadcrumbs } from "../../components/navigation/Breadcrumbs.js";
import { SideNav } from "../../components/navigation/SideNav.js";
import { BulkActionBar } from "../../components/navigation/BulkActionBar.js";
import { Button } from "../../components/forms/Button.js";
function Demo() {
  const [v, setV] = React.useState("Overview");
  const [range, setRange] = React.useState("7d");
  const [sel, setSel] = React.useState(3);
  return React.createElement("div", null, React.createElement(Tabs, {
    tabs: ["Overview", "Deployments", "Activity", "Settings"],
    value: v,
    onChange: setV
  }), React.createElement("div", {
    className: "row",
    style: { marginTop: "calc(var(--sp-1) * 3.5)" }
  }, React.createElement("div", {
    className: "sub"
  }, "SegmentedControl — filters inside the tab, never navigates"), React.createElement(SegmentedControl, {
    ariaLabel: "Time range",
    options: ["24h", "7d", "30d"],
    value: range,
    onChange: setRange
  }), React.createElement("span", {
    style: { color: "var(--mute)", fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)" }
  }, "Active view: ", React.createElement("span", {
    style: { color: "var(--gold)" }
  }, v), " · Range: ", React.createElement("span", {
    style: { color: "var(--gold)" }
  }, range))), React.createElement("div", {
    className: "sub"
  }, "Breadcrumbs — the last item is the current location"), React.createElement("div", {
    className: "row"
  }, React.createElement(Breadcrumbs, {
    items: [{ label: "Projects", href: "#" }, { label: "Client Portal", href: "#" }, { label: "Deployments" }]
  })), React.createElement("div", {
    className: "sub"
  }, "SideNav — anchors navigate, the active item is aria-current"), React.createElement("div", {
    className: "row",
    style: { width: "var(--layout-sidebar)" }
  }, React.createElement(SideNav, {
    ariaLabel: "Primary",
    active: "deploys",
    style: { width: "100%" },
    items: [
      { id: "dashboard", icon: React.createElement("i", {
        className: "ph-bold ph-squares-four"
      }), label: "Projects", href: "#projects" },
      { id: "deploys", icon: React.createElement("i", {
        className: "ph-bold ph-rocket-launch"
      }), label: "Deployments", href: "#deploys" },
      { id: "settings", icon: React.createElement("i", {
        className: "ph-bold ph-gear-six"
      }), label: "Settings" }
    ]
  })), React.createElement("div", {
    className: "sub"
  }, "PageHead"), React.createElement("div", {
    style: { marginBottom: "var(--sp-4)" }
  }, React.createElement(PageHead, {
    title: "Client Portal",
    subtitle: "Last published 2 h ago · build #4821",
    actions: React.createElement(React.Fragment, null, React.createElement(Button, {
      variant: "secondary",
      size: "sm"
    }, "View logs"), React.createElement(Button, {
      variant: "primary",
      size: "sm"
    }, "Deploy"))
  })), React.createElement("div", {
    className: "sub"
  }, "BulkActionBar — destructive stays outline, never filled"), React.createElement("div", {
    className: "row"
  }, React.createElement(BulkActionBar, {
    count: sel,
    noun: "deployments",
    onClear: () => setSel(0),
    style: { width: "100%" },
    actions: [
      { label: "Re-run", icon: React.createElement("i", {
        className: "ph-bold ph-arrow-clockwise"
      }), onClick: () => {} },
      { label: "Archive", icon: React.createElement("i", {
        className: "ph-bold ph-archive"
      }), onClick: () => {} },
      { label: "Delete", icon: React.createElement("i", {
        className: "ph-bold ph-trash"
      }), onClick: () => {}, destructive: true }
    ]
  }), sel === 0 && React.createElement("button", {
    onClick: () => setSel(3),
    style: { background: "none", border: "var(--bw) solid var(--color-base-300)", borderRadius: "var(--r-sm)", color: "var(--mute)", cursor: "pointer", fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-badge)", textTransform: "uppercase", padding: "var(--sp-2) var(--sp-3)" }
  }, "Restore selection")));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
