/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
function pages(current, total) {
  if (total <= 7)
    return Array.from({ length: total }, (_, i) => i + 1);
  const out = [1];
  const from = Math.max(2, current - 1), to = Math.min(total - 1, current + 1);
  if (from > 2)
    out.push("…");
  for (let p = from;p <= to; p++)
    out.push(p);
  if (to < total - 1)
    out.push("…");
  out.push(total);
  return out;
}
export function Pagination({ page = 1, pageCount = 1, onChange, style }) {
  const go = (p) => {
    if (p >= 1 && p <= pageCount && p !== page)
      onChange && onChange(p);
  };
  const nav = (dir, dis) => React.createElement("button", {
    onClick: () => go(page + dir),
    disabled: dis,
    "aria-label": dir < 0 ? "Previous" : "Next",
    style: {
      height: "calc(var(--sp-1) * 8.5)",
      minWidth: "calc(var(--sp-1) * 8.5)",
      padding: "0 calc(var(--sp-1) * 2)",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      background: "transparent",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-sm)",
      color: dis ? "var(--mute-2-disabled)" : "var(--bone-dim)",
      cursor: dis ? "not-allowed" : "pointer",
      fontSize: "var(--icon-md)"
    }
  }, React.createElement("i", {
    className: dir < 0 ? "ph-bold ph-caret-left" : "ph-bold ph-caret-right"
  }));
  return React.createElement("nav", {
    "aria-label": "Pagination",
    style: { display: "inline-flex", alignItems: "center", gap: "calc(var(--sp-1) * 1.5)", ...style }
  }, nav(-1, page <= 1), pages(page, pageCount).map((p, i) => p === "…" ? React.createElement("span", {
    key: "e" + i,
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-md)", color: "var(--mute)", padding: "0 calc(var(--sp-1) * 1)" }
  }, "…") : React.createElement("button", {
    key: p,
    onClick: () => go(p),
    "aria-current": p === page ? "page" : undefined,
    style: {
      height: "calc(var(--sp-1) * 8.5)",
      minWidth: "calc(var(--sp-1) * 8.5)",
      padding: "0 calc(var(--sp-1) * 2)",
      borderRadius: "var(--r-sm)",
      cursor: "pointer",
      fontFamily: "var(--font-mono)",
      fontSize: "var(--dz-text-md)",
      fontWeight: "var(--fw-bold)",
      background: p === page ? "var(--crimson)" : "transparent",
      border: "var(--bw) solid " + (p === page ? "var(--crimson)" : "var(--color-base-300)"),
      color: p === page ? "var(--on-accent)" : "var(--bone-dim)"
    }
  }, p)), nav(1, page >= pageCount));
}
