/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { indentFor } from "./side-nav-inject.js";
export function SideNavItem({
  id,
  label,
  icon,
  href,
  depth = 0,
  activeId,
  indentStep = 3,
  onActivate
}) {
  if (!id)
    throw new Error("SideNavItem: `id` is required");
  if (!label)
    throw new Error("SideNavItem: `label` is required");
  const on = id === activeId;
  const shared = {
    "aria-current": on ? "page" : undefined,
    onClick: () => onActivate && onActivate(id),
    style: {
      display: "flex",
      alignItems: "center",
      gap: "calc(var(--sp-1) * 3)",
      paddingBlock: "calc(var(--sp-1) * 2.5)",
      paddingInlineEnd: "calc(var(--sp-1) * 3)",
      paddingInlineStart: indentFor(indentStep, depth),
      borderRadius: "var(--r-sm)",
      background: on ? "var(--crimson-soft)" : "transparent",
      color: on ? "var(--crimson)" : "var(--mute)",
      border: "none",
      cursor: "pointer",
      textAlign: "left",
      textDecoration: "none",
      fontFamily: "var(--font-body)",
      fontSize: "var(--dz-text)",
      fontWeight: on ? "var(--fw-semibold)" : "var(--fw-medium)"
    }
  };
  const glyph = icon ? React.createElement("i", {
    className: icon,
    "aria-hidden": "true",
    style: { fontSize: "var(--icon-lg)", display: "inline-flex" }
  }) : null;
  return href ? React.createElement("a", {
    href,
    ...shared
  }, glyph, label) : React.createElement("button", {
    type: "button",
    ...shared
  }, glyph, label);
}
