/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect, useState } from "react";
import { injectInto, indentFor } from "./side-nav-inject.js";
import { SideNavItem } from "./SideNavItem.js";
export function subtreeHasItem(children, id) {
  if (!id)
    return false;
  for (const child of React.Children.toArray(children)) {
    if (!React.isValidElement(child))
      continue;
    if (child.type === SideNavItem && child.props.id === id)
      return true;
    if (subtreeHasItem(child.props.children, id))
      return true;
  }
  return false;
}
export function SideNavCollapsible({
  id,
  label,
  icon,
  defaultExpanded = false,
  children,
  onToggle,
  depth = 0,
  activeId,
  indentStep = 3,
  onActivate
}) {
  if (!id)
    throw new Error("SideNavCollapsible: `id` is required");
  if (!label)
    throw new Error("SideNavCollapsible: `label` is required");
  const holdsActive = subtreeHasItem(children, activeId);
  const [expanded, setExpanded] = useState(defaultExpanded || holdsActive);
  useEffect(() => {
    if (holdsActive)
      setExpanded(true);
  }, [holdsActive]);
  const regionId = `${id}-region`;
  const triggerId = `${id}-trigger`;
  const press = () => {
    const next = !expanded;
    setExpanded(next);
    if (onToggle)
      onToggle(next);
  };
  const glyph = icon ? React.createElement("i", {
    className: icon,
    "aria-hidden": "true",
    style: { fontSize: "var(--icon-lg)", display: "inline-flex" }
  }) : null;
  return React.createElement("div", {
    style: { display: "flex", flexDirection: "column", gap: "var(--sp-1)" }
  }, React.createElement("button", {
    id: triggerId,
    type: "button",
    "aria-expanded": expanded,
    "aria-controls": regionId,
    onClick: press,
    style: {
      display: "flex",
      alignItems: "center",
      gap: "calc(var(--sp-1) * 3)",
      paddingBlock: "calc(var(--sp-1) * 2.5)",
      paddingInlineEnd: "calc(var(--sp-1) * 3)",
      paddingInlineStart: indentFor(indentStep, depth),
      borderRadius: "var(--r-sm)",
      background: "transparent",
      color: "var(--mute)",
      border: "none",
      cursor: "pointer",
      textAlign: "left",
      fontFamily: "var(--font-body)",
      fontSize: "var(--dz-text)",
      fontWeight: "var(--fw-medium)"
    }
  }, glyph, React.createElement("span", {
    style: { flex: 1 }
  }, label), React.createElement("i", {
    className: expanded ? "ph-bold ph-caret-down" : "ph-bold ph-caret-right",
    "aria-hidden": "true",
    style: { fontSize: "var(--icon-md)", display: "inline-flex" }
  })), React.createElement("div", {
    id: regionId,
    role: "group",
    "aria-labelledby": triggerId,
    hidden: !expanded,
    style: { display: expanded ? "flex" : "none", flexDirection: "column", gap: "var(--sp-1)" }
  }, injectInto(children, { depth: depth + 1, activeId, indentStep, onActivate })));
}
