/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
export function Tabs({ tabs = [], value, defaultValue, onChange, style }) {
  const [internal, setInternal] = useState(defaultValue ?? (tabs[0] && (tabs[0].value ?? tabs[0])));
  const active = value ?? internal;
  const select = (v) => {
    setInternal(v);
    onChange && onChange(v);
  };
  return React.createElement("div", {
    style: { display: "flex", gap: "calc(var(--sp-1) * 1)", borderBottom: "var(--bw) solid var(--color-base-300)", ...style }
  }, tabs.map((t) => {
    const v = t.value ?? t;
    const label = t.label ?? t;
    const on = v === active;
    return React.createElement("button", {
      key: v,
      onClick: () => select(v),
      style: {
        position: "relative",
        padding: "calc(var(--sp-1) * 2.5) calc(var(--sp-1) * 4)",
        background: "none",
        border: "none",
        cursor: "pointer",
        fontFamily: "var(--font-body)",
        fontWeight: on ? "var(--fw-semibold)" : "var(--fw-medium)",
        fontSize: "var(--dz-text)",
        color: on ? "var(--bone)" : "var(--mute)",
        boxShadow: on ? "inset 0 calc(var(--bw-strong) * -1) 0 var(--crimson)" : "none",
        transition: "color var(--dur-fast) var(--ease-out)"
      }
    }, label);
  }));
}
