/* GENERATED by scripts/build-tailwind.mjs — edit Badge.manifest.json, not this file. */
export default {
  "component": "Badge",
  "slots": {
    "root": "inline-flex items-center gap-1.5 px-2.5 py-1 rounded-pill font-mono text-ctl-xs font-bold tracking-badge uppercase",
    "dot": "size-1.5 rounded-pill bg-current"
  },
  "variants": {
    "tone": {
      "neutral": {
        "root": "bg-base-300 text-base-content/82"
      },
      "accent": {
        "root": "bg-primary/14 text-primary"
      },
      "gold": {
        "root": "bg-secondary/16 text-secondary"
      },
      "success": {
        "root": "bg-success/16 text-success"
      },
      "warning": {
        "root": "bg-warning/18 text-warning"
      },
      "danger": {
        "root": "bg-error/14 text-error"
      },
      "info": {
        "root": "bg-info/16 text-info"
      }
    }
  },
  "defaultVariants": {
    "tone": "neutral"
  }
} as const;
