/* GENERATED by scripts/build-tailwind.mjs — edit BulkActionBar.manifest.json, not this file. */
export default {
  "component": "BulkActionBar",
  "slots": {
    "root": "flex items-center gap-3.5 min-h-13 pl-4 pr-3 bg-base-200 border-[length:var(--bw)] border-neutral rounded-md shadow-2",
    "count": "font-mono text-ctl-sm tracking-mono-nav text-base-content",
    "number": "text-secondary",
    "divider": "w-px h-5.5 bg-base-300",
    "actions": "flex items-center gap-1.5 flex-1 flex-wrap",
    "action": "inline-flex items-center gap-2 h-8.5 px-3 bg-transparent border-[length:var(--bw)] rounded-sm cursor-pointer font-body font-semibold text-ctl-md transition-[background] duration-[var(--dur-fast)] ease-out",
    "actionIcon": "inline-flex text-[length:var(--icon-md)]",
    "clear": "bg-transparent border-none cursor-pointer text-base-content/62 font-mono text-ctl-xs tracking-badge uppercase"
  },
  "variants": {
    "destructive": {
      "true": {
        "action": "border-error text-error hover:bg-error/14"
      },
      "false": {
        "action": "border-base-300 text-base-content/82 hover:bg-base-200"
      }
    },
    "open": {
      "true": {},
      "false": {
        "root": "hidden"
      }
    }
  },
  "defaultVariants": {
    "destructive": false,
    "open": false
  }
} as const;
