/* GENERATED by scripts/build-tailwind.mjs — edit Card.manifest.json, not this file. */
export default {
  "component": "Card",
  "slots": {
    "root": "bg-base-200 border-[length:var(--bw)] rounded-lg overflow-hidden",
    "head": "flex items-start justify-between px-5 pt-4.5",
    "eyebrow": "font-mono text-ctl-xs tracking-label uppercase text-primary mb-1.5",
    "title": "font-display font-extrabold text-h4 text-base-content",
    "body": "p-5"
  },
  "variants": {
    "accent": {
      "true": {
        "root": "border-primary"
      },
      "false": {
        "root": "border-base-300"
      }
    },
    "floating": {
      "true": {
        "root": "shadow-2"
      },
      "false": {
        "root": "shadow-none"
      }
    }
  },
  "defaultVariants": {
    "accent": "false",
    "floating": "false"
  }
} as const;
