/* GENERATED by scripts/build-tailwind.mjs — edit ErrorState.manifest.json, not this file. */
export default {
  "component": "ErrorState",
  "slots": {
    "root": "flex flex-col items-center text-center gap-3 px-8 py-14 bg-error/14 border-[length:var(--bw)] border-error rounded-lg",
    "icon": "text-[length:var(--icon-xl)] text-error leading-ctl",
    "title": "font-display font-extrabold text-h4 text-base-content",
    "message": "font-body text-md text-base-content/82 leading-body max-w-[46ch]",
    "code": "font-mono text-ctl-sm text-base-content/62 bg-base-100/30 px-2.5 py-1 rounded-xs",
    "actions": "flex gap-2.5 mt-1.5",
    "retry": "inline-flex items-center justify-center h-ctl-h px-4.5 rounded-sm border-[length:var(--bw)] border-transparent font-body font-semibold text-ctl cursor-pointer gap-2 transition-[background,transform,box-shadow] duration-[var(--dur-fast)] ease-[var(--ease-out)] bg-primary text-primary-content border-primary hover:shadow-2"
  }
} as const;
