/* GENERATED by scripts/build-tailwind.mjs — edit IconButton.manifest.json, not this file. */
export default {
  "component": "IconButton",
  "slots": {
    "root": "inline-flex items-center justify-center rounded-sm cursor-pointer transition-[background] duration-[var(--dur-fast)] ease-out disabled:opacity-45 disabled:cursor-not-allowed",
    "label": "font-body font-semibold text-ctl leading-ctl"
  },
  "variants": {
    "variant": {
      "ghost": {
        "root": "bg-transparent text-base-content/82 border-[length:var(--bw)] border-base-300 hover:bg-base-200"
      },
      "solid": {
        "root": "bg-primary text-primary-content border-none hover:bg-primary"
      }
    },
    "size": {
      "sm": {
        "root": "h-ctl-h-sm min-w-ctl-h-sm"
      },
      "md": {
        "root": "h-ctl-h min-w-ctl-h"
      },
      "lg": {
        "root": "h-ctl-h-lg min-w-ctl-h-lg"
      }
    },
    "showLabel": {
      "true": {
        "root": "w-auto gap-2 pl-3 pr-3.5"
      },
      "false": {
        "root": "w-ctl-h p-0 gap-0"
      }
    }
  },
  "defaultVariants": {
    "variant": "ghost",
    "size": "md",
    "showLabel": "false"
  }
} as const;
