/* GENERATED by scripts/build-tailwind.mjs — edit Skeleton.manifest.json, not this file. */
export default {
  "component": "Skeleton",
  "slots": {
    "root": "arena-shimmer",
    "stack": "flex flex-col gap-2.5 w-full",
    "line": "arena-shimmer h-3 rounded-xs w-full",
    "lastLine": "arena-shimmer h-3 rounded-xs w-[62%]"
  },
  "variants": {
    "variant": {
      "text": {
        "root": "hidden"
      },
      "line": {
        "root": "h-3 w-full rounded-xs"
      },
      "block": {
        "root": "h-24 w-full rounded-sm"
      },
      "circle": {
        "root": "size-10 rounded-full"
      }
    }
  },
  "defaultVariants": {
    "variant": "block"
  }
} as const;
