/* GENERATED by scripts/build-tailwind.mjs — edit Switch.manifest.json, not this file. */
export default {
  "component": "Switch",
  "slots": {
    "root": "inline-flex items-center gap-2.5",
    "track": "inline-flex items-center w-10 h-5.5 p-0.5 rounded-pill transition-[background] duration-[var(--dur-mid)] ease-out",
    "thumb": "size-4.5 rounded-full bg-primary-content transition-[transform] duration-[var(--dur-mid)] ease-out",
    "label": "inline-flex items-center gap-1.5 font-body text-ctl text-base-content/82",
    "guard": "text-[length:var(--icon-sm)] text-base-content/62",
    "input": "absolute opacity-0 size-0"
  },
  "variants": {
    "checked": {
      "true": {
        "track": "bg-primary",
        "thumb": "translate-x-4.5"
      },
      "false": {
        "track": "bg-neutral",
        "thumb": "translate-x-0"
      }
    },
    "disabled": {
      "true": {
        "root": "opacity-50 cursor-not-allowed"
      },
      "false": {
        "root": "cursor-pointer"
      }
    }
  },
  "defaultVariants": {
    "checked": "false",
    "disabled": "false"
  }
} as const;
