/* GENERATED by scripts/build-tailwind.mjs — edit Textarea.manifest.json, not this file. */
export default {
  "component": "Textarea",
  "slots": {
    "root": "flex flex-col gap-1.5",
    "label": "font-mono text-ctl-xs tracking-field-label uppercase text-base-content/62",
    "required": "text-primary ml-1",
    "field": "w-full px-3 py-2.5 bg-base-300 border-[length:var(--bw)] rounded-sm text-base-content font-body text-ctl leading-body outline-none transition-[border-color,box-shadow] duration-[var(--dur-fast)] ease-out",
    "foot": "flex justify-between gap-3",
    "hint": "font-body text-ctl-sm text-base-content/62",
    "error": "font-body text-ctl-sm text-error",
    "counter": "font-mono text-ctl-xs text-base-content/62",
    "counterNear": "font-mono text-ctl-xs text-warning"
  },
  "variants": {
    "state": {
      "neutral": {
        "field": "border-base-300 focus:border-secondary focus:ring-[length:var(--focus-width)] focus:ring-secondary/16"
      },
      "error": {
        "field": "border-error ring-[length:var(--focus-width)] ring-error/14"
      }
    },
    "resize": {
      "vertical": {
        "field": "resize-y"
      },
      "none": {
        "field": "resize-none"
      }
    },
    "disabled": {
      "true": {
        "root": "opacity-50"
      },
      "false": {}
    }
  },
  "defaultVariants": {
    "state": "neutral",
    "resize": "vertical",
    "disabled": "false"
  }
} as const;
