/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
const SIZES = { xs: "var(--avatar-xs)", sm: "var(--avatar-sm)", md: "var(--avatar-md)", lg: "var(--avatar-lg)" };
const STATUS = { online: "var(--success)", busy: "var(--danger)", away: "var(--warning)", offline: "var(--status-offline)" };
export function Avatar({ src, name = "", size = "md", shape = "circle", status }) {
  const d = SIZES[size] || SIZES.md;
  const radius = shape === "rounded" ? "var(--r-md)" : "50%";
  const initials = name.trim().split(/\s+/).slice(0, 2).map((w) => w[0] || "").join("").toUpperCase();
  return React.createElement("span", {
    style: { position: "relative", display: "inline-flex", width: d, height: d, flexShrink: 0 }
  }, React.createElement("span", {
    style: {
      width: d,
      height: d,
      borderRadius: radius,
      overflow: "hidden",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      background: "var(--color-base-300)",
      border: "var(--bw) solid var(--line-strong)",
      fontFamily: "var(--font-display)",
      fontWeight: "var(--fw-extrabold)",
      fontSize: `calc(${d} * 0.4)`,
      color: "var(--bone-dim)",
      letterSpacing: "var(--ls-normal)"
    }
  }, src ? React.createElement("img", {
    src,
    alt: name,
    style: { width: "100%", height: "100%", objectFit: "cover" }
  }) : initials), status && React.createElement("span", {
    "aria-label": status,
    title: status,
    style: {
      position: "absolute",
      right: 0,
      bottom: 0,
      width: `max(calc(var(--sp-1) * 2), calc(${d} * 0.28))`,
      height: `max(calc(var(--sp-1) * 2), calc(${d} * 0.28))`,
      borderRadius: "50%",
      background: STATUS[status] || STATUS.offline,
      border: "var(--bw-strong) solid var(--surface-card)"
    }
  }));
}
