/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { injectInto, COLUMN } from "./SideNavInject.js";
export function SideNav({ children, active, ariaLabel, indentStep = 3, onNav }) {
  if (!ariaLabel)
    throw new Error("SideNav: `ariaLabel` is required");
  return React.createElement("nav", {
    "aria-label": ariaLabel,
    style: COLUMN
  }, injectInto(children, { depth: 0, activeId: active, indentStep, onActivate: onNav }));
}
