/* GENERATED by scripts/build-api-types.mjs — edit api/types/, not this file.
 *
 * Every declaration here is a predefined object or an enum some Arena API
 * contract names. The same body is emitted into both layers so a component's
 * import never crosses the api/ <-> frameworks/ boundary — the rule
 * tokens.generated.* already carries. scripts/check-api.mjs asserts the
 * committed files match api/types/. See api/README.md for the vocabulary. */

/** One event in a feed: someone did something to something, then. Arena draws every field — a consumer cannot place their own markup inside a row. */
export interface ActivityItem {
  /** A stable identity for the row, so a reordered feed does not re-key by index. */
  id?: string;
  /** Who. Drawn bold in --bone. */
  actor: string;
  /** What they did. Drawn in --bone-dim. */
  action: string;
  /** What they did it to. Drawn monospaced in --gold — it is an identifier. */
  target?: string;
  /** When. Monospaced --mute, pushed to the trailing edge. Preformatted — ActivityFeed never formats. */
  time?: string;
  /** Badge's vocabulary, driving the leading dot. Defaults to accent. */
  tone?: Tone;
}

/** The alert's severity — the colour and default icon/role it takes. */
export type AlertTone = 'info' | 'success' | 'warning' | 'danger' | 'neutral';

/** Circle for a person, rounded for a team or organisation. */
export type AvatarShape = 'circle' | 'rounded';

/** The avatar's diameter, a fixed repertoire: xs a dense table row, sm a comment byline, md the default, lg a profile header. */
export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg';

/** A presence state, drawn as a filled dot in the corner in the state's colour — `offline` is a visible muted dot, not the absence of one. There is no invisible value: to show no presence at all, omit the optional `status` member. */
export type AvatarStatus = 'online' | 'busy' | 'away' | 'offline';

/** One action a BulkActionBar offers for the current selection. A destructive action stays outline in --error — transparent at rest, the soft --danger-soft tint only on hover — never the filled danger surface, which is ConfirmDialog's alone. */
export interface BulkAction {
  /** The button's text. */
  label: string;
  /** A Phosphor class name for the leading glyph Arena draws. */
  icon?: string;
  /** Renders the action outline in --error rather than in --bone-dim. */
  destructive?: boolean;
}

/** One entry in a CommandPalette. `hint` is searched but never shown, so a command can be found by a synonym that never appears in its label. */
export interface Command {
  /** A stable identity for the command, so a host can switch on it rather than on the label. */
  id: string;
  /** What the command is called, and the primary text searched. */
  label: string;
  /** Searched but never shown — a synonym that finds the command. */
  hint?: string;
  /** A Phosphor class name for the leading glyph Arena draws. */
  icon?: string;
  /** The keystroke shown at the row's trailing edge, monospaced. Display only — the palette does not bind it. */
  shortcut?: string;
}

/** One entry in a breadcrumb trail. `href` is omitted for the current page, which is never rendered as a link. */
export interface Crumb {
  /** What the crumb reads. */
  label: string;
  /** Where it goes. Absent on the last entry, the current location. */
  href?: string;
}

/** Whether a change was GOOD. Separate from Direction because revenue down is negative and latency down is positive, and only the product knows which. Every sign renders outline, never filled. */
export type DeltaTone = 'neutral' | 'positive' | 'negative';

/** Which way a number moved. Draws the arrow — nothing else. Deliberately separate from whether that movement was good. */
export type Direction = 'up' | 'down';

/** Both halves of the brand lock-up at once — the mark's slot and the wordmark. A fixed repertoire, not a ratio: sm an application frame, md a signed-out panel, lg the manual's Primary, xl the hero case. */
export type LogoSize = 'sm' | 'md' | 'lg' | 'xl';

/** Whether a component's parts lay out side by side or stacked — which axis it runs along. */
export type Orientation = 'horizontal' | 'vertical';

/** How the actions block aligns against the title in PageHead's wide layout. */
export type PageHeadAlign = 'start' | 'center';

/** The shape the placeholder reserves: a single text line, a stack of lines, a block, or a circle. */
export type SkeletonVariant = 'text' | 'line' | 'block' | 'circle';

/** How a metric moved. Preformatted — StatCard never formats. The pill's colour says whether the change was GOOD, not which way it points, which is why direction and tone are separate fields. */
export interface StatDelta {
  /** Preformatted, e.g. "+12%" or "-340ms". */
  value: string;
  /** Which way the number moved. Draws the arrow — nothing else. */
  direction: Direction;
  /** Whether that movement is GOOD. Defaults to neutral — an unlabelled delta claims nothing. */
  tone?: DeltaTone;
}

/** The switch's overall size, from a dense sm to a prominent 2xl. */
export type SwitchSize = 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** The tag's emphasis colour, per the Badge/Tag tone taxonomy. */
export type TagTone = 'neutral' | 'primary' | 'success' | 'warning' | 'danger';

/** What state a value IS in right now, as against how it moved. Badge's vocabulary, so one set of tone names covers the system rather than a second set that is nearly the same. */
export type Tone = 'neutral' | 'accent' | 'gold' | 'success' | 'warning' | 'danger' | 'info';
