/* GENERATED by scripts/build-api-types.mjs — edit api/types/, not this file.
 *
 * Every declaration here is a predefined object or an enum some Arena API
 * contract names. The same body is emitted into both layers so a component's
 * import never crosses the api/ <-> frameworks/ boundary — the rule
 * tokens.generated.* already carries. scripts/check-api.mjs asserts the
 * committed files match api/types/. See api/README.md for the vocabulary. */

/** Circle for a person, rounded for a team or organisation. */
export type AvatarShape = 'circle' | 'rounded';

/** The avatar's diameter, a fixed repertoire: xs a dense table row, sm a comment byline, md the default, lg a profile header. */
export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg';

/** A presence state, drawn as a filled dot in the corner in the state's colour — `offline` is a visible muted dot, not the absence of one. There is no invisible value: to show no presence at all, omit the optional `status` member. */
export type AvatarStatus = 'online' | 'busy' | 'away' | 'offline';

/** One entry in a breadcrumb trail. `href` is omitted for the current page, which is never rendered as a link. */
export interface Crumb {
  /** What the crumb reads. */
  label: string;
  /** Where it goes. Absent on the last entry, the current location. */
  href?: string;
}

/** Whether a change was GOOD. Separate from Direction because revenue down is negative and latency down is positive, and only the product knows which. Every sign renders outline, never filled. */
export type DeltaTone = 'neutral' | 'positive' | 'negative';

/** Which way a number moved. Draws the arrow — nothing else. Deliberately separate from whether that movement was good. */
export type Direction = 'up' | 'down';

/** Both halves of the brand lock-up at once — the mark's slot and the wordmark. A fixed repertoire, not a ratio: sm an application frame, md a signed-out panel, lg the manual's Primary, xl the hero case. */
export type LogoSize = 'sm' | 'md' | 'lg' | 'xl';

/** Whether a component's parts lay out side by side or stacked — which axis it runs along. */
export type Orientation = 'horizontal' | 'vertical';

/** The shape the placeholder reserves: a single text line, a stack of lines, a block, or a circle. */
export type SkeletonVariant = 'text' | 'line' | 'block' | 'circle';

/** How a metric moved. Preformatted — StatCard never formats. The pill's colour says whether the change was GOOD, not which way it points, which is why direction and tone are separate fields. */
export interface StatDelta {
  /** Preformatted, e.g. "+12%" or "-340ms". */
  value: string;
  /** Which way the number moved. Draws the arrow — nothing else. */
  direction: Direction;
  /** Whether that movement is GOOD. Defaults to neutral — an unlabelled delta claims nothing. */
  tone?: DeltaTone;
}

/** The switch's overall size, from a dense sm to a prominent 2xl. */
export type SwitchSize = 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** The tag's emphasis colour, per the Badge/Tag tone taxonomy. */
export type TagTone = 'neutral' | 'primary' | 'success' | 'warning' | 'danger';

/** What state a value IS in right now, as against how it moved. Badge's vocabulary, so one set of tone names covers the system rather than a second set that is nearly the same. */
export type Tone = 'neutral' | 'accent' | 'gold' | 'success' | 'warning' | 'danger' | 'info';
