/* GENERATED by scripts/build-tokens.mjs — edit tokens/src/, not this file.
 *
 * Every export here is a token flagged script-readable in tokens/src/ and
 * emitted as a bare number because JS arithmetic consumes it. Each one also
 * ships as a CSS custom property; scripts/check-script-tokens.mjs asserts the
 * two carry the same value. A value bound at import time cannot re-theme or
 * re-densify — that is the accepted price of reading it in JS at all. */

/* Script-readable: Onboarding's gap below its anchor is arithmetic on a DOMRect. */
export const sp3 = 12;
/* Script-readable: Onboarding's minimum gutter from either viewport edge, compared against window.innerWidth. */
export const sp4 = 16;
/*
   The pixel height of one hour. Script-readable because
   y = ((min - startMin) / 60) * hour-h is arithmetic, and no CSS expression
   computes a position from a minute-of-day. An orphan before this: --sp-10 is 40
   and --sp-12 is 48, so nothing in the spacing scale was 44.
 */
export const calendarHourH = 44;
/*
   The popover's width. Script-readable because Math.min/Math.max compare it
   against window.innerWidth. This ALSO replaces the calc(var(--sp-1) * 80) the
   component rendered: the value existed twice in two idioms, held in step by a
   comment. One token now, read both ways.
 */
export const onboardingWidth = 320;
/* Plot height before padding. */
export const chartHeight = 280;
/*
   Equals --sp-2. Authored rather than aliased: build-tokens.mjs loads one
   source file per call, so a DTCG reference across files would not resolve.
 */
export const chartPadTop = 8;
/* Equals --sp-2. See pad-top. */
export const chartPadRight = 8;
/*
   Holds the category labels. This is a CONSEQUENCE of the type scale, not a
   chosen dimension: it is enough room for a label at --dz-text-2xs. If the type
   scale moves, revisit it — it will not fail loudly.
 */
export const chartPadBottom = 28;
/* Holds the value labels. A consequence of the type scale, like pad-bottom. */
export const chartPadLeft = 44;
/*
   A bar's data end. Deliberately NOT --r-sm (6px): naming the value Arena
   already renders is free, snapping to the radius scale is a visible 2px design
   change and must be taken as one.
 */
export const chartBarRadius = 4;
/* Surface between bars. Equals --bw-strong, coincidentally. */
export const chartBarGap = 2;
/* A line chart's point at rest. */
export const chartPointR = 4;
/*
   A line chart's point under the pointer. The 1px delta IS the hover
   affordance — the pair only means anything together.
 */
export const chartPointRHover = 5;
/* Doughnut legend, narrowest. */
export const chartLegendMin = 120;
/* Doughnut legend, widest. */
export const chartLegendMax = 180;
/* Between the doughnut plot and its legend. Equals --sp-4. */
export const chartLegendGap = 16;
/* Rest time before a tooltip appears. Long enough that crossing a toolbar reveals nothing. */
export const delayOpen = 400;
/*
   Grace period after the pointer leaves. Short, and much shorter than open:
   it exists so travelling between a trigger and its own tooltip does not dismiss it,
   not to keep the tooltip around.
 */
export const delayClose = 120;
/*
   A toast that only has to be read. This is the value the Delivery Console
   shipped hard-coded before it was a token.
 */
export const dismissDefault = 4200;
/*
   A toast carrying a button. WCAG 2.2.1: it asks the reader to DECIDE, not
   only to read, and 4.2s is enough for the second task only if they were already
   looking. persist (README H1) still overrides both and stays mandatory in
   critical states.
 */
export const dismissActionable = 7000;
/*
   How many page numbers flank the current one before the list elides. The
   window's total width is a CONSEQUENCE and is derived at the point of use, never
   authored: first + last + (2 * siblings + 1) + two ellipses.
 */
export const limitPaginationSiblings = 1;

/* Derived, not authored: the number of --color-cat-* slots in
 * tokens/src/palette.dark.json. Assigned in order and NEVER cycled -- a 9th
 * series folds to "Other", small multiples, or direct labels. */
export const catSlots = 8;
