/* GENERATED by scripts/build-tokens.mjs — edit tokens/src/, not this file.
 *
 * Every export here is a token flagged script-readable in tokens/src/ and
 * emitted as a bare number because JS arithmetic consumes it. Each one also
 * ships as a CSS custom property; scripts/check-script-tokens.mjs asserts the
 * two carry the same value. A value bound at import time cannot re-theme or
 * re-densify — that is the accepted price of reading it in JS at all. */

/* Plot height before padding. */
export const chartHeight = 280;
/*
   Equals --sp-2. Authored rather than aliased: build-tokens.mjs loads one
   source file per call, so a DTCG reference across files would not resolve.
 */
export const chartPadTop = 8;
/* Equals --sp-2. See pad-top. */
export const chartPadRight = 8;
/*
   Holds the category labels. This is a CONSEQUENCE of the type scale, not a
   chosen dimension: it is enough room for a label at --dz-text-2xs. If the type
   scale moves, revisit it — it will not fail loudly.
 */
export const chartPadBottom = 28;
/* Holds the value labels. A consequence of the type scale, like pad-bottom. */
export const chartPadLeft = 44;
/*
   A bar's data end. Deliberately NOT --r-sm (6px): naming the value Arena
   already renders is free, snapping to the radius scale is a visible 2px design
   change and must be taken as one.
 */
export const chartBarRadius = 4;
/* Surface between bars. Equals --bw-strong, coincidentally. */
export const chartBarGap = 2;
/* A line chart's point at rest. */
export const chartPointR = 4;
/*
   A line chart's point under the pointer. The 1px delta IS the hover
   affordance — the pair only means anything together.
 */
export const chartPointRHover = 5;
/* Doughnut legend, narrowest. */
export const chartLegendMin = 120;
/* Doughnut legend, widest. */
export const chartLegendMax = 180;
/* Between the doughnut plot and its legend. Equals --sp-4. */
export const chartLegendGap = 16;

/* Derived, not authored: the number of --color-cat-* slots in
 * tokens/src/palette.dark.json. Assigned in order and NEVER cycled -- a 9th
 * series folds to "Other", small multiples, or direct labels. */
export const catSlots = 8;
