/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
const MARK = { sm: "var(--logo-mark-sm)", md: "var(--logo-mark-md)", lg: "var(--logo-mark-lg)", xl: "var(--logo-mark-xl)" };
const TEXT = { sm: "var(--logo-text-sm)", md: "var(--logo-text-md)", lg: "var(--logo-text-lg)", xl: "var(--logo-text-xl)" };
export function AppLogo({ size = "md", orientation = "horizontal", mark, name, dim }) {
  if (!mark || !name)
    throw new Error("AppLogo: `mark` and `name` are required");
  const vertical = orientation === "vertical";
  const markSize = MARK[size] || MARK.md;
  const textSize = TEXT[size] || TEXT.md;
  const fill = React.isValidElement(mark) ? React.cloneElement(mark, { style: { display: "block", width: "100%", height: "100%", ...mark.props.style } }) : mark;
  return React.createElement("span", {
    style: {
      display: "inline-flex",
      flexDirection: vertical ? "column" : "row",
      alignItems: "center",
      gap: vertical ? "calc(var(--sp-1) * 3)" : "calc(var(--sp-1) * 2.5)"
    }
  }, React.createElement("span", {
    style: { display: "inline-flex", flex: "none", width: markSize, height: markSize }
  }, fill), React.createElement("span", {
    style: {
      fontFamily: "var(--font-display)",
      fontWeight: "var(--fw-black)",
      fontSize: textSize,
      letterSpacing: "var(--ls-tight)",
      textTransform: "uppercase",
      color: "var(--bone)"
    }
  }, name, dim && React.createElement("span", {
    style: { color: "var(--mute)" }
  }, dim)));
}
