/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Rotor } from "../../components/brand/Rotor.js";
import { AppLogo } from "../../components/brand/AppLogo.js";
const CRIMSON = React.createElement("img", {
  src: "../../../../assets/rotor-crimson.svg",
  alt: ""
});
const BONE = React.createElement("img", {
  src: "../../../../assets/rotor-bone.svg",
  alt: ""
});
function Demo() {
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "AppLogo — the four steps of the scale"), React.createElement("div", {
    className: "row"
  }, React.createElement(AppLogo, {
    size: "xl",
    mark: CRIMSON,
    name: "Draven",
    dim: "soft"
  })), React.createElement("div", {
    className: "row"
  }, React.createElement(AppLogo, {
    size: "lg",
    mark: CRIMSON,
    name: "Draven",
    dim: "soft"
  })), React.createElement("div", {
    className: "row"
  }, React.createElement(AppLogo, {
    size: "md",
    mark: CRIMSON,
    name: "Draven",
    dim: "soft"
  })), React.createElement("div", {
    className: "row"
  }, React.createElement(AppLogo, {
    size: "sm",
    mark: CRIMSON,
    name: "Draven",
    dim: "soft"
  })), React.createElement("div", {
    className: "sub"
  }, "Monochrome · single ink — a bone mark, no dim"), React.createElement("div", {
    className: "row"
  }, React.createElement(AppLogo, {
    size: "md",
    mark: BONE,
    name: "Dravensoft"
  })), React.createElement("div", {
    className: "sub"
  }, "Vertical · stacked"), React.createElement("div", {
    className: "row"
  }, React.createElement(AppLogo, {
    size: "md",
    orientation: "vertical",
    mark: CRIMSON,
    name: "Draven",
    dim: "soft"
  })), React.createElement("div", {
    className: "sub"
  }, "Rotor — the animated mark, same scale. Brand, not a UI icon"), React.createElement("div", {
    className: "row",
    style: { gap: "var(--sp-8)" }
  }, React.createElement(Rotor, {
    size: "lg",
    spin: true
  }), React.createElement(Rotor, {
    size: "md"
  }), React.createElement(Rotor, {
    size: "sm",
    color: "var(--bone)"
  })));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
