/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect } from "react";
let injected = false;
function useRotorKeyframes() {
  useEffect(() => {
    if (injected || typeof document === "undefined")
      return;
    injected = true;
    const s = document.createElement("style");
    s.setAttribute("data-arena-rotor", "");
    s.textContent = "@keyframes arena-rotor{to{transform:rotate(360deg)}}" + ".arena-rotor-spin{animation:arena-rotor var(--loop-brand) linear infinite;transform-origin:50% 50%}" + "@media (prefers-reduced-motion:reduce){.arena-rotor-spin{animation-duration:var(--loop-brand-reduced)}}";
    document.head.appendChild(s);
  }, []);
}
const SIZES = { sm: "var(--logo-mark-sm)", md: "var(--logo-mark-md)", lg: "var(--logo-mark-lg)", xl: "var(--logo-mark-xl)" };
export function Rotor({ size = "md", color = "var(--crimson)", spin = false, style, ...rest }) {
  useRotorKeyframes();
  const d = SIZES[size] || SIZES.md;
  const blade = "M50 50 L92 64.3 L75.2 75.2 L64.3 92 Z";
  return React.createElement("span", {
    style: { display: "inline-flex", width: d, height: d, ...style },
    ...rest
  }, React.createElement("svg", {
    viewBox: "0 0 100 100",
    width: "100%",
    height: "100%",
    fill: color,
    className: spin ? "arena-rotor-spin" : undefined
  }, React.createElement("path", {
    d: blade
  }), React.createElement("path", {
    d: blade,
    transform: "rotate(120 50 50)"
  }), React.createElement("path", {
    d: blade,
    transform: "rotate(240 50 50)"
  })));
}
