/* GENERATED by scripts/build/react/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { UnauthCard } from "./UnauthCard.js";
import { AppLogo } from "../../brand/app-logo/AppLogo.js";
import { Input } from "../../forms/input/Input.js";
import { Button } from "../../forms/button/Button.js";
function Demo() {
  const [email, setEmail] = React.useState("ana@dravensoft.dev");
  const [password, setPassword] = React.useState("dravensoft");
  return React.createElement("div", {
    style: { minHeight: "100%", display: "flex", alignItems: "center", justifyContent: "center" }
  }, React.createElement(UnauthCard, {
    brand: React.createElement(AppLogo, {
      size: "md",
      mark: React.createElement("img", {
        src: "../../../../../assets/rotor-crimson.svg",
        alt: ""
      }),
      name: "Draven",
      dim: "soft"
    }),
    eyebrow: "Delivery console",
    title: "Welcome back",
    footer: React.createElement("span", null, "Forgot your password?")
  }, React.createElement("div", {
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 4)" }
  }, React.createElement(Input, {
    label: "Email",
    value: email,
    onChange: setEmail
  }), React.createElement(Input, {
    label: "Password",
    type: "password",
    value: password,
    onChange: setPassword
  }), React.createElement(Button, {
    variant: "primary",
    full: true
  }, "Sign in"))));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
