/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function Checkbox({ checked = false, onChange, label, disabled = false, style, ...rest }) {
  return React.createElement("label", {
    style: { display: "inline-flex", alignItems: "center", gap: "calc(var(--sp-1) * 2.5)", cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.5 : 1, ...style }
  }, React.createElement("span", {
    style: {
      width: "calc(var(--sp-1) * 5)",
      height: "calc(var(--sp-1) * 5)",
      borderRadius: "var(--r-xs)",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      background: checked ? "var(--crimson)" : "var(--surface-input)",
      border: "var(--bw) solid " + (checked ? "var(--crimson)" : "var(--line-strong)"),
      transition: "background var(--dur-fast) var(--ease-out)"
    }
  }, checked && React.createElement("svg", {
    style: { width: "var(--sp-3)", height: "var(--sp-3)" },
    viewBox: "0 0 12 12",
    fill: "none"
  }, React.createElement("path", {
    d: "M2 6l3 3 5-6",
    stroke: "var(--on-accent)",
    style: { strokeWidth: "var(--bw-strong)" },
    strokeLinecap: "round",
    strokeLinejoin: "round"
  }))), label && React.createElement("span", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--dz-text)", color: "var(--bone-dim)" }
  }, label), React.createElement("input", {
    type: "checkbox",
    checked,
    onChange,
    disabled,
    style: { position: "absolute", opacity: 0, width: 0, height: 0 },
    ...rest
  }));
}
