/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Button } from "../../components/forms/Button.js";
import { IconButton } from "../../components/forms/IconButton.js";
import { Input } from "../../components/forms/Input.js";
import { Select } from "../../components/forms/Select.js";
import { Checkbox } from "../../components/forms/Checkbox.js";
import { Switch } from "../../components/forms/Switch.js";
function Demo() {
  const [chk, setChk] = React.useState(true);
  const [sw, setSw] = React.useState(true);
  const [email, setEmail] = React.useState("hello@");
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Button — variants"), React.createElement("div", {
    className: "row"
  }, React.createElement(Button, {
    variant: "primary",
    icon: "ph-bold ph-plus"
  }, "Deploy"), React.createElement(Button, {
    variant: "secondary"
  }, "Roll back"), React.createElement(Button, {
    variant: "ghost"
  }, "Cancel"), React.createElement(Button, {
    variant: "danger"
  }, "Delete"), React.createElement(Button, {
    variant: "primary",
    loading: true
  }, "Deploying"), React.createElement(Button, {
    variant: "primary",
    disabled: true
  }, "Locked")), React.createElement("div", {
    className: "sub"
  }, "Sizes · IconButton"), React.createElement("div", {
    className: "row"
  }, React.createElement(Button, {
    size: "sm",
    variant: "secondary"
  }, "sm"), React.createElement(Button, {
    size: "md",
    variant: "secondary"
  }, "md"), React.createElement(Button, {
    size: "lg",
    variant: "secondary"
  }, "lg"), React.createElement(IconButton, {
    label: "New",
    variant: "solid",
    icon: "ph-bold ph-plus"
  }), React.createElement(IconButton, {
    label: "New",
    icon: "ph-bold ph-plus"
  })), React.createElement("div", {
    className: "sub"
  }, "Input · Select"), React.createElement("div", {
    className: "row",
    style: { alignItems: "flex-start" }
  }, React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 55)" }
  }, React.createElement(Input, {
    label: "Repository",
    prefix: "git@",
    placeholder: "org/project"
  })), React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 50)" }
  }, React.createElement(Input, {
    label: "Email",
    error: "Invalid format",
    value: email,
    onChange: setEmail
  })), React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 45)" }
  }, React.createElement(Select, {
    label: "Environment",
    options: [{ value: "Production", label: "Production" }, { value: "Staging", label: "Staging" }, { value: "QA", label: "QA" }]
  }))), React.createElement("div", {
    className: "sub"
  }, "Input — native date and time"), React.createElement("div", {
    className: "row",
    style: { alignItems: "flex-start" }
  }, React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 50)" }
  }, React.createElement(Input, {
    label: "Deploy date",
    type: "date",
    required: true
  })), React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 50)" }
  }, React.createElement(Input, {
    label: "Window start",
    type: "time",
    hint: "Local time"
  })), React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 60)" }
  }, React.createElement(Input, {
    label: "Cutover",
    type: "datetime-local"
  })), React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 50)" }
  }, React.createElement(Input, {
    label: "Deadline",
    type: "date",
    error: "Pick a date in the future"
  }))), React.createElement("div", {
    className: "sub"
  }, "Checkbox · Switch"), React.createElement("div", {
    className: "row"
  }, React.createElement(Checkbox, {
    checked: chk,
    onChange: setChk,
    label: "Notify on approval"
  }), React.createElement(Switch, {
    state: sw,
    onFuncOn: () => setSw(true),
    onFuncOff: () => setSw(false),
    label: "Automatic deployment"
  })));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
