/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Button } from "../../components/forms/Button.js";
import { IconButton } from "../../components/forms/IconButton.js";
import { Input } from "../../components/forms/Input.js";
import { Select } from "../../components/forms/Select.js";
import { Checkbox } from "../../components/forms/Checkbox.js";
import { Switch } from "../../components/forms/Switch.js";
import { ThemeToggle } from "../../components/forms/ThemeToggle.js";
const plus = React.createElement("i", {
  className: "ph-bold ph-plus",
  style: { fontSize: "var(--icon-md)", lineHeight: "var(--dz-lh)" }
});
function Demo() {
  const [chk, setChk] = React.useState(true);
  const [sw, setSw] = React.useState(true);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Button — variants"), React.createElement("div", {
    className: "row"
  }, React.createElement(Button, {
    variant: "primary",
    icon: plus
  }, "Deploy"), React.createElement(Button, {
    variant: "secondary"
  }, "Roll back"), React.createElement(Button, {
    variant: "ghost"
  }, "Cancel"), React.createElement(Button, {
    variant: "danger"
  }, "Delete"), React.createElement(Button, {
    variant: "primary",
    loading: true
  }, "Deploying"), React.createElement(Button, {
    variant: "primary",
    disabled: true
  }, "Locked")), React.createElement("div", {
    className: "sub"
  }, "Sizes · IconButton"), React.createElement("div", {
    className: "row"
  }, React.createElement(Button, {
    size: "sm",
    variant: "secondary"
  }, "sm"), React.createElement(Button, {
    size: "md",
    variant: "secondary"
  }, "md"), React.createElement(Button, {
    size: "lg",
    variant: "secondary"
  }, "lg"), React.createElement(IconButton, {
    label: "New",
    variant: "solid"
  }, plus), React.createElement(IconButton, {
    label: "New"
  }, plus)), React.createElement("div", {
    className: "sub"
  }, "Input · Select"), React.createElement("div", {
    className: "row",
    style: { alignItems: "flex-start" }
  }, React.createElement(Input, {
    label: "Repository",
    prefix: "git@",
    placeholder: "org/project",
    style: { width: "calc(var(--sp-1) * 55)" }
  }), React.createElement(Input, {
    label: "Email",
    error: "Invalid format",
    defaultValue: "hello@",
    style: { width: "calc(var(--sp-1) * 50)" }
  }), React.createElement(Select, {
    label: "Environment",
    options: ["Production", "Staging", "QA"],
    style: { width: "calc(var(--sp-1) * 45)" }
  })), React.createElement("div", {
    className: "sub"
  }, "Input — native date and time"), React.createElement("div", {
    className: "row",
    style: { alignItems: "flex-start" }
  }, React.createElement(Input, {
    label: "Deploy date",
    type: "date",
    required: true,
    style: { width: "calc(var(--sp-1) * 50)" }
  }), React.createElement(Input, {
    label: "Window start",
    type: "time",
    hint: "Local time",
    style: { width: "calc(var(--sp-1) * 50)" }
  }), React.createElement(Input, {
    label: "Cutover",
    type: "datetime-local",
    style: { width: "calc(var(--sp-1) * 60)" }
  }), React.createElement(Input, {
    label: "Deadline",
    type: "date",
    error: "Pick a date in the future",
    style: { width: "calc(var(--sp-1) * 50)" }
  })), React.createElement("div", {
    className: "sub"
  }, "Checkbox · Switch"), React.createElement("div", {
    className: "row"
  }, React.createElement(Checkbox, {
    checked: chk,
    onChange: (e) => setChk(e.target.checked),
    label: "Notify on approval"
  }), React.createElement(Switch, {
    state: sw,
    onFuncOn: () => setSw(true),
    onFuncOff: () => setSw(false),
    label: "Automatic deployment"
  })), React.createElement("div", {
    className: "sub"
  }, "ThemeToggle"), React.createElement("div", {
    className: "row"
  }, React.createElement(ThemeToggle, null), React.createElement("span", {
    style: { fontSize: "var(--dz-text-md)", color: "var(--mute)" }
  }, "Flips the whole page — every component re-themes from tokens alone.")));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
