/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
const SZ = { sm: "var(--dz-ctl-h-sm)", md: "var(--dz-ctl-h)", lg: "var(--dz-ctl-h-lg)" };
export function IconButton({ children, size = "md", variant = "ghost", label, showLabel = false, disabled = false, style, ...rest }) {
  const [hover, setHover] = useState(false);
  const d = SZ[size] || SZ.md;
  const bg = variant === "solid" ? hover ? "var(--crimson-strong)" : "var(--crimson)" : hover ? "var(--panel)" : "transparent";
  const color = variant === "solid" ? "var(--on-accent)" : "var(--bone-dim)";
  return React.createElement("button", {
    "aria-label": label,
    title: showLabel ? undefined : label,
    disabled,
    onMouseEnter: () => setHover(true),
    onMouseLeave: () => setHover(false),
    style: {
      height: d,
      width: showLabel ? "auto" : d,
      minWidth: d,
      padding: showLabel ? "0 calc(var(--sp-1) * 3.5) 0 var(--sp-3)" : 0,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: showLabel ? "var(--sp-2)" : 0,
      background: bg,
      color,
      border: variant === "solid" ? "none" : "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-sm)",
      cursor: disabled ? "not-allowed" : "pointer",
      opacity: disabled ? 0.45 : 1,
      transition: "background var(--dur-fast) var(--ease-out)",
      ...style
    },
    ...rest
  }, children, showLabel && React.createElement("span", {
    style: { fontFamily: "var(--font-body)", fontWeight: "var(--fw-semibold)", fontSize: "var(--dz-text)", lineHeight: "var(--dz-lh)" }
  }, label));
}
