/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { RadioGroup, Radio } from "../../components/forms/Radio.js";
import { Textarea } from "../../components/forms/Textarea.js";
function Demo() {
  const [env, setEnv] = React.useState("staging");
  const [notes, setNotes] = React.useState("");
  return React.createElement("div", {
    className: "row",
    style: { gap: 40 }
  }, React.createElement("div", {
    style: { width: 280 }
  }, React.createElement("div", {
    className: "sub",
    style: { marginBottom: 12 }
  }, "RadioGroup"), React.createElement(RadioGroup, {
    value: env,
    onChange: setEnv
  }, React.createElement(Radio, {
    value: "prod",
    label: "Production",
    hint: "Real users — requires approval"
  }), React.createElement(Radio, {
    value: "staging",
    label: "Staging"
  }), React.createElement(Radio, {
    value: "qa",
    label: "QA"
  }))), React.createElement("div", {
    style: { width: 320 }
  }, React.createElement(Textarea, {
    label: "Deployment notes",
    rows: 5,
    maxLength: 280,
    counter: true,
    value: notes,
    onChange: (e) => setNotes(e.target.value),
    hint: "Attached to the delivery log."
  })));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
