/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function RadioGroup({ value, onChange, name, children, style, ...rest }) {
  const gname = name || "rg-" + Math.random().toString(36).slice(2, 7);
  const items = React.Children.map(children, (child) => React.isValidElement(child) ? React.cloneElement(child, { name: gname, checked: child.props.value === value, onSelect: onChange }) : child);
  return React.createElement("div", {
    role: "radiogroup",
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 3)", ...style },
    ...rest
  }, items);
}
export function Radio({ value, label, hint, name, checked = false, onSelect, disabled = false, style, ...rest }) {
  return React.createElement("label", {
    style: { display: "inline-flex", alignItems: "flex-start", gap: "calc(var(--sp-1) * 2.5)", cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.5 : 1, ...style }
  }, React.createElement("span", {
    style: {
      width: "calc(var(--sp-1) * 5)",
      height: "calc(var(--sp-1) * 5)",
      borderRadius: "50%",
      flexShrink: 0,
      marginTop: 0,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      background: "var(--surface-input)",
      border: "var(--bw) solid " + (checked ? "var(--crimson)" : "var(--line-strong)"),
      transition: "border-color var(--dur-fast) var(--ease-out)"
    }
  }, checked && React.createElement("span", {
    style: { width: "calc(var(--sp-1) * 2.5)", height: "calc(var(--sp-1) * 2.5)", borderRadius: "50%", background: "var(--crimson)" }
  })), React.createElement("span", {
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 0.5)" }
  }, label && React.createElement("span", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--dz-text)", color: "var(--bone-dim)", lineHeight: "var(--lh-snug)" }
  }, label), hint && React.createElement("span", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--dz-text-sm)", color: "var(--mute)", lineHeight: "var(--lh-body)" }
  }, hint)), React.createElement("input", {
    type: "radio",
    name,
    value,
    checked,
    disabled,
    onChange: () => onSelect && onSelect(value),
    style: { position: "absolute", opacity: 0, width: 0, height: 0 },
    ...rest
  }));
}
