/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function Switch({ checked = false, onChange, onRequestChange, confirm = false, label, disabled = false, style, ...rest }) {
  const guarded = confirm && typeof onRequestChange === "function";
  const attempt = (e) => {
    if (disabled)
      return;
    if (guarded) {
      e.preventDefault();
      onRequestChange(!checked);
    }
  };
  return React.createElement("label", {
    onClick: attempt,
    style: { display: "inline-flex", alignItems: "center", gap: "calc(var(--sp-1) * 2.5)", cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.5 : 1, ...style }
  }, React.createElement("span", {
    style: {
      width: "calc(var(--sp-1) * 10)",
      height: "calc(var(--sp-1) * 5.5)",
      borderRadius: "var(--r-pill)",
      padding: "calc(var(--sp-1) * 0.5)",
      display: "inline-flex",
      alignItems: "center",
      background: checked ? "var(--crimson)" : "var(--line-strong)",
      transition: "background var(--dur-mid) var(--ease-out)"
    }
  }, React.createElement("span", {
    style: {
      width: "calc(var(--sp-1) * 4.5)",
      height: "calc(var(--sp-1) * 4.5)",
      borderRadius: "50%",
      background: "var(--on-accent)",
      transform: checked ? "translateX(calc(var(--sp-1) * 4.5))" : "translateX(0)",
      transition: "transform var(--dur-mid) var(--ease-out)"
    }
  })), label && React.createElement("span", {
    style: { display: "inline-flex", alignItems: "center", gap: "calc(var(--sp-1) * 1.5)", fontFamily: "var(--font-body)", fontSize: "var(--dz-text)", color: "var(--bone-dim)" }
  }, label, confirm && React.createElement("i", {
    className: "ph-bold ph-shield-check",
    title: "Requires confirmation",
    style: { fontSize: "var(--icon-sm)", color: "var(--mute)" }
  })), React.createElement("input", {
    type: "checkbox",
    role: "switch",
    checked,
    "aria-checked": checked,
    onChange: guarded ? undefined : onChange,
    disabled,
    style: { position: "absolute", opacity: 0, width: 0, height: 0 },
    ...rest
  }));
}
