/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect, useState } from "react";
import { IconButton } from "./IconButton.js";
const STORAGE_KEY = "draven-theme";
const isDarkNow = () => typeof document !== "undefined" && !document.documentElement.classList.contains("arena-light");
export function ThemeToggle({ label, ...rest }) {
  const [dark, setDark] = useState(true);
  useEffect(() => {
    setDark(isDarkNow());
    const mo = new MutationObserver(() => setDark(isDarkNow()));
    mo.observe(document.documentElement, { attributes: true, attributeFilter: ["class"] });
    return () => mo.disconnect();
  }, []);
  const toggle = () => {
    if (typeof window !== "undefined" && typeof window.__toggleTheme === "function") {
      window.__toggleTheme();
      return;
    }
    const goingLight = isDarkNow();
    document.documentElement.classList.toggle("arena-light", goingLight);
    try {
      localStorage.setItem(STORAGE_KEY, goingLight ? "light" : "dark");
    } catch (_) {}
  };
  const name = label ? label(dark) : dark ? "Switch to light theme" : "Switch to dark theme";
  return React.createElement(IconButton, {
    label: name,
    "aria-pressed": dark,
    onClick: toggle,
    ...rest
  }, React.createElement("i", {
    className: dark ? "ph-bold ph-sun" : "ph-bold ph-moon",
    "aria-hidden": "true"
  }));
}
