/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function EmptyState({ icon, title, message, action }) {
  if (!title)
    throw new Error("EmptyState: `title` is required");
  return React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
      gap: "calc(var(--sp-1) * 3)",
      padding: "calc(var(--sp-1) * 14) calc(var(--sp-1) * 8)",
      border: "var(--bw) dashed var(--line-strong)",
      borderRadius: "var(--r-lg)",
      background: "var(--surface-card)"
    }
  }, icon && React.createElement("div", {
    style: { fontSize: "var(--icon-xl)", color: "var(--mute)", lineHeight: "var(--dz-lh)" }
  }, React.createElement("i", {
    className: icon,
    "aria-hidden": "true"
  })), title && React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-extrabold)", fontSize: "var(--fs-h4)", color: "var(--bone)" }
  }, title), message && React.createElement("div", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--fs-md)", color: "var(--mute)", maxWidth: "42ch", lineHeight: "var(--lh-body)" }
  }, message), action && React.createElement("div", {
    style: { marginTop: "calc(var(--sp-1) * 1.5)" }
  }, action));
}
