/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function ChartCard({ title, actions, children }) {
  return React.createElement("div", {
    style: {
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      padding: "calc(var(--sp-1) * 5)",
      display: "flex",
      flexDirection: "column",
      gap: "calc(var(--sp-1) * 3)"
    }
  }, (title || actions) && React.createElement("div", {
    style: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "calc(var(--sp-1) * 3)" }
  }, title && React.createElement("span", {
    style: {
      fontFamily: "var(--font-mono)",
      fontSize: "var(--dz-text-2xs)",
      letterSpacing: "var(--ls-label)",
      textTransform: "uppercase",
      color: "var(--mute)"
    }
  }, title), actions && React.createElement("div", {
    style: { display: "flex", alignItems: "center", gap: "calc(var(--sp-1) * 2)" }
  }, actions)), children);
}
