/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { ConfirmDialog } from "../../components/feedback/ConfirmDialog.js";
import { Button } from "../../components/forms/Button.js";
function Demo() {
  const [hard, setHard] = React.useState(true);
  const [soft, setSoft] = React.useState(false);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "The trigger stays outline · only the final confirmation is filled"), React.createElement("div", {
    className: "row"
  }, React.createElement(Button, {
    variant: "danger",
    onClick: () => setHard(true)
  }, "Delete project…"), React.createElement(Button, {
    variant: "secondary",
    onClick: () => setSoft(true)
  }, "Enable auto-deploy…")), React.createElement("div", {
    className: "sub"
  }, "requireText makes the irreversible one deliberate — no click-outside either"), React.createElement(ConfirmDialog, {
    open: hard,
    destructive: true,
    requireText: "DELETE",
    title: "Delete project",
    confirmLabel: "Delete permanently",
    onCancel: () => setHard(false),
    onConfirm: () => setHard(false)
  }, "This action cannot be undone. 4 deployments and their history will be deleted."), React.createElement(ConfirmDialog, {
    open: soft,
    title: "Enable automatic deployment",
    confirmLabel: "Enable",
    onCancel: () => setSoft(false),
    onConfirm: () => setSoft(false)
  }, "Every approved commit will be deployed to production without manual review."));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
