/* GENERATED by scripts/build-tailwind.mjs — edit Tag.manifest.json, not this file. */
export default {
  "component": "Tag",
  "slots": {
    "root": "inline-flex items-center gap-1.5 rounded-pill border-[length:var(--bw)] px-2 py-0.5 text-ctl-xs font-semibold",
    "dot": "size-1.5 rounded-pill bg-current",
    "close": "inline-flex items-center bg-transparent border-none cursor-pointer p-0 text-base-content/62 text-[length:var(--icon-sm)] leading-ctl"
  },
  "variants": {
    "tone": {
      "neutral": {
        "root": "border-base-300 text-base-content/70"
      },
      "primary": {
        "root": "border-primary text-primary"
      },
      "success": {
        "root": "border-success text-success"
      },
      "warning": {
        "root": "border-warning text-warning"
      },
      "danger": {
        "root": "border-error text-error"
      }
    }
  },
  "defaultVariants": {
    "tone": "neutral"
  }
} as const;
