/* GENERATED by scripts/build-tailwind.mjs — edit Pagination.manifest.json, not this file. */
export default {
  "component": "Pagination",
  "slots": {
    "root": "inline-flex items-center gap-1.5",
    "nav": "inline-flex items-center justify-center h-8.5 min-w-8.5 px-2 bg-transparent border-[length:var(--bw)] border-base-300 rounded-sm text-[length:var(--icon-md)] cursor-pointer text-base-content/82 disabled:text-base-content/40 disabled:cursor-not-allowed",
    "page": "inline-flex items-center justify-center h-8.5 min-w-8.5 px-2 rounded-sm border-[length:var(--bw)] cursor-pointer font-mono text-ctl-md font-bold",
    "pageCurrent": "bg-primary border-primary text-primary-content",
    "pageOther": "bg-transparent border-base-300 text-base-content/82",
    "ellipsis": "px-1 font-mono text-ctl-md text-base-content/62"
  }
} as const;
