/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { ActivityFeed } from "../../components/display/ActivityFeed.js";
import { Card } from "../../components/display/Card.js";
const ITEMS = [
  { id: "1", actor: "ana@", action: "approved the release", target: "build #4821", time: "2h ago", tone: "success" },
  { id: "2", actor: "CI", action: "deployed to production", target: "build #4821", time: "2h ago" },
  { id: "3", actor: "diego@", action: "opened incident", target: "checkout latency", time: "3h ago", tone: "danger" },
  { id: "4", actor: "nora@", action: "merged", target: "PR #338 · session cache", time: "5h ago", tone: "info" }
];
function Demo() {
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Inside a Card — the feed renders no surface of its own"), React.createElement(Card, null, React.createElement(ActivityFeed, {
    items: ITEMS
  })));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
