/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { IconButton } from "../forms/IconButton.js";
export const CalendarEvent = React.forwardRef(function CalendarEvent({
  id,
  title,
  start,
  end,
  colorId,
  onClick,
  actionsEnabled = false,
  actions,
  box,
  color,
  timeLabel,
  dateLabel,
  showTime,
  tabIndex,
  defaultPanelOpen
}, ref) {
  if (!id)
    throw new Error("CalendarEvent: `id` is required");
  if (!title)
    throw new Error("CalendarEvent: `title` is required");
  if (!start)
    throw new Error("CalendarEvent: `start` is required");
  if (!end)
    throw new Error("CalendarEvent: `end` is required");
  const hasPanel = actionsEnabled && Boolean(actions);
  const Tag = onClick && !hasPanel ? "button" : "div";
  const [panelOpen, setPanelOpen] = React.useState(Boolean(defaultPanelOpen));
  const body = React.createElement(React.Fragment, null, React.createElement("span", {
    style: {
      fontSize: "var(--dz-text-sm)",
      fontWeight: "var(--fw-semibold)",
      color: "var(--text-strong)",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis"
    }
  }, title), showTime && React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-2xs)", color: "var(--mute)" }
  }, timeLabel));
  return React.createElement(Tag, {
    ref,
    type: onClick && !hasPanel ? "button" : undefined,
    tabIndex: hasPanel ? undefined : tabIndex,
    onClick: onClick && !hasPanel ? (e) => {
      e.stopPropagation();
      onClick();
    } : undefined,
    "aria-label": onClick && !hasPanel ? `${title}, ${dateLabel}, ${timeLabel}` : undefined,
    onKeyDown: hasPanel ? (e) => {
      if (e.key === "Escape" && panelOpen) {
        e.stopPropagation();
        setPanelOpen(false);
      }
    } : undefined,
    style: {
      position: "absolute",
      ...box,
      display: "flex",
      flexDirection: "column",
      gap: 0,
      overflow: "hidden",
      textAlign: "left",
      padding: "calc(var(--sp-1) * 1) calc(var(--sp-1) * 1.5)",
      background: `color-mix(in oklab, ${color} 16%, var(--surface-card))`,
      borderLeft: `var(--bw-strong) solid ${color}`,
      borderTop: "none",
      borderRight: "none",
      borderBottom: "none",
      borderRadius: "var(--r-sm)",
      cursor: onClick ? "pointer" : "default",
      font: "inherit"
    }
  }, hasPanel ? React.createElement(React.Fragment, null, onClick ? React.createElement("button", {
    type: "button",
    tabIndex,
    onClick: (e) => {
      e.stopPropagation();
      onClick();
    },
    "aria-label": `${title}, ${dateLabel}, ${timeLabel}`,
    style: {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 0,
      background: "none",
      border: "none",
      padding: 0,
      margin: 0,
      font: "inherit",
      color: "inherit",
      textAlign: "left",
      cursor: "pointer"
    }
  }, body) : body, React.createElement("span", {
    style: { position: "absolute", top: 0, right: 0 }
  }, React.createElement(IconButton, {
    icon: "ph-bold ph-dots-three-vertical",
    label: "Actions",
    size: "sm",
    tabStop: false,
    onClick: () => setPanelOpen((o) => !o)
  }), panelOpen && React.createElement("span", {
    style: {
      position: "absolute",
      top: "100%",
      right: 0,
      zIndex: 1,
      display: "flex",
      gap: "var(--sp-2)",
      padding: "var(--sp-2)",
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-sm)",
      boxShadow: "var(--shadow-2)"
    }
  }, actions))) : body);
});
