/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export const CalendarEvent = React.forwardRef(function CalendarEvent({
  id,
  title,
  start,
  end,
  colorId,
  onClick,
  box,
  color,
  timeLabel,
  dateLabel,
  showTime,
  tabIndex
}, ref) {
  if (!id)
    throw new Error("CalendarEvent: `id` is required");
  if (!title)
    throw new Error("CalendarEvent: `title` is required");
  if (!start)
    throw new Error("CalendarEvent: `start` is required");
  if (!end)
    throw new Error("CalendarEvent: `end` is required");
  const Tag = onClick ? "button" : "div";
  return React.createElement(Tag, {
    type: onClick ? "button" : undefined,
    tabIndex,
    onClick: onClick ? (e) => {
      e.stopPropagation();
      onClick();
    } : undefined,
    "aria-label": onClick ? `${title}, ${dateLabel}, ${timeLabel}` : undefined,
    style: {
      position: "absolute",
      ...box,
      display: "flex",
      flexDirection: "column",
      gap: 0,
      overflow: "hidden",
      textAlign: "left",
      padding: "calc(var(--sp-1) * 1) calc(var(--sp-1) * 1.5)",
      background: `color-mix(in oklab, ${color} 16%, var(--surface-card))`,
      borderLeft: `var(--bw-strong) solid ${color}`,
      borderTop: "none",
      borderRight: "none",
      borderBottom: "none",
      borderRadius: "var(--r-sm)",
      cursor: onClick ? "pointer" : "default",
      font: "inherit"
    }
  }, React.createElement("span", {
    style: {
      fontSize: "var(--dz-text-sm)",
      fontWeight: "var(--fw-semibold)",
      color: "var(--text-strong)",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis"
    }
  }, title), showTime && React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-2xs)", color: "var(--mute)" }
  }, timeLabel));
});
