/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Calendar } from "../../components/display/Calendar.js";
import { Button } from "../../components/forms/Button.js";
const zone = Intl.DateTimeFormat().resolvedOptions().timeZone;
const now = new Date;
const monday = new Date(now);
monday.setDate(now.getDate() - (now.getDay() + 6) % 7);
const at = (day, h, m) => {
  const d = new Date(monday);
  d.setDate(monday.getDate() + day);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
};
const events = [
  { id: "s1", title: "Standup", start: at(0, 9, 0), end: at(0, 9, 30), slot: 1 },
  { id: "m1", title: "Client review — Northwind", start: at(0, 10, 0), end: at(0, 11, 30), slot: 2 },
  { id: "m2", title: "Design critique", start: at(0, 11, 0), end: at(0, 12, 0), slot: 3 },
  { id: "s2", title: "Standup", start: at(1, 9, 0), end: at(1, 9, 30), slot: 1 },
  { id: "m3", title: "Migration planning", start: at(1, 13, 0), end: at(1, 14, 30), slot: 4 },
  { id: "s3", title: "Standup", start: at(2, 9, 0), end: at(2, 9, 30), slot: 1 },
  { id: "m4", title: "Onsite — Acme", start: at(2, 10, 0), end: at(2, 12, 0), slot: 5 },
  { id: "m5", title: "Security sync", start: at(2, 10, 30), end: at(2, 11, 0), slot: 6 },
  { id: "m6", title: "Retro", start: at(2, 11, 30), end: at(2, 12, 30), slot: 7 },
  { id: "s4", title: "Standup", start: at(3, 9, 0), end: at(3, 9, 30), slot: 1 },
  { id: "m7", title: "Release window", start: at(3, 15, 0), end: at(3, 16, 30), slot: 8 },
  { id: "s5", title: "Standup", start: at(4, 9, 0), end: at(4, 9, 30), slot: 1 },
  { id: "m8", title: "Demo day", start: at(4, 12, 0), end: at(4, 13, 0), slot: 2 },
  { id: "m9", title: "On-call handover", start: at(5, 11, 0), end: at(5, 12, 0), slot: 3 }
];
function Demo() {
  const [picked, setPicked] = React.useState(null);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Wednesday shows three overlapping events sharing the width · Sunday is hidden until something lands on it", picked && React.createElement(React.Fragment, null, " · picked: ", picked)), React.createElement(Calendar, {
    timeZone: zone,
    events,
    onEventClick: (e) => setPicked(e.title),
    actions: React.createElement(Button, {
      size: "sm",
      variant: "secondary",
      icon: React.createElement("i", {
        className: "ph-bold ph-plus"
      })
    }, "New event"),
    dayEnd: "18:00"
  }));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
