/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function Card({ children, title, eyebrow, action, floating = false, accent = false, style, ...rest }) {
  return React.createElement("div", {
    style: {
      background: "var(--surface-card)",
      border: "var(--bw) solid " + (accent ? "var(--crimson)" : "var(--color-base-300)"),
      borderRadius: "var(--r-lg)",
      boxShadow: floating ? "var(--shadow-2)" : "none",
      overflow: "hidden",
      ...style
    },
    ...rest
  }, (title || eyebrow || action) && React.createElement("div", {
    style: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", padding: "calc(var(--sp-1) * 4.5) calc(var(--sp-1) * 5) 0" }
  }, React.createElement("div", null, eyebrow && React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-label)", textTransform: "uppercase", color: "var(--crimson)", marginBottom: "calc(var(--sp-1) * 1.5)" }
  }, eyebrow), title && React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-extrabold)", fontSize: "var(--fs-h4)", color: "var(--bone)" }
  }, title)), action), React.createElement("div", {
    style: { padding: "calc(var(--sp-1) * 5)" }
  }, children));
}
