/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Card } from "../../components/display/Card.js";
import { Badge } from "../../components/display/Badge.js";
import { Tag } from "../../components/display/Tag.js";
import { StatCard } from "../../components/display/StatCard.js";
function Demo() {
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Badge — tones"), React.createElement("div", {
    className: "row"
  }, React.createElement(Badge, {
    tone: "success",
    dot: true
  }, "Deployed"), React.createElement(Badge, {
    tone: "warning"
  }, "In review"), React.createElement(Badge, {
    tone: "danger",
    dot: true
  }, "Down"), React.createElement(Badge, {
    tone: "accent"
  }, "New"), React.createElement(Badge, {
    tone: "gold"
  }, "Priority"), React.createElement(Badge, {
    tone: "info"
  }, "v2.4"), React.createElement(Badge, null, "Draft")), React.createElement("div", {
    className: "sub"
  }, "Tag"), React.createElement("div", {
    className: "row"
  }, React.createElement(Tag, null, "TypeScript"), React.createElement(Tag, null, "PostgreSQL"), React.createElement(Tag, {
    onRemove: () => {}
  }, "React")), React.createElement("div", {
    className: "sub"
  }, "Card"), React.createElement("div", {
    className: "row",
    style: { alignItems: "stretch" }
  }, React.createElement(Card, {
    eyebrow: "Delivery",
    title: "Client Portal",
    action: React.createElement(Badge, {
      tone: "success",
      dot: true
    }, "Deployed"),
    style: { width: "calc(var(--sp-1) * 75)" }
  }, React.createElement("div", {
    style: { color: "var(--mute)", fontSize: "var(--dz-text)", lineHeight: "var(--lh-body)" }
  }, "Last published 2 h ago · build #4821")), React.createElement(Card, {
    accent: true,
    floating: true,
    title: "Latency alert",
    style: { width: "calc(var(--sp-1) * 70)" }
  }, React.createElement("div", {
    style: { color: "var(--mute)", fontSize: "var(--dz-text)", lineHeight: "var(--lh-body)" }
  }, "p95 rose to 340 ms on checkout."))), React.createElement("div", {
    className: "sub"
  }, "StatCard — the value says what IS, the pill says how it MOVED"), React.createElement("div", {
    className: "row",
    style: { alignItems: "stretch" }
  }, React.createElement("div", {
    style: { flex: 1 }
  }, React.createElement(StatCard, {
    label: "Deploys",
    value: "128",
    delta: { value: "+12%", direction: "up", tone: "positive" },
    sub: "vs last week"
  })), React.createElement("div", {
    style: { flex: 1 }
  }, React.createElement(StatCard, {
    label: "p95 latency",
    value: "340 ms",
    delta: { value: "-18%", direction: "down", tone: "positive" },
    sub: "vs last week"
  })), React.createElement("div", {
    style: { flex: 1 }
  }, React.createElement(StatCard, {
    label: "Open incidents",
    value: "3",
    tone: "danger",
    delta: { value: "-2", direction: "down", tone: "positive" },
    sub: "2 acknowledged"
  })), React.createElement("div", {
    style: { flex: 1 }
  }, React.createElement(StatCard, {
    label: "Build time",
    value: "4m 12s",
    delta: { value: "+3s", direction: "up" }
  }))));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
