/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect } from "react";
let injected = false;
function useShimmer() {
  useEffect(() => {
    if (injected || typeof document === "undefined")
      return;
    injected = true;
    const s = document.createElement("style");
    s.setAttribute("data-arena-skeleton", "");
    s.textContent = "@keyframes arena-shimmer{0%{background-position:-140% 0}100%{background-position:140% 0}}" + ".arena-skeleton{background-image:linear-gradient(100deg,var(--panel) 30%,var(--color-base-300) 50%,var(--panel) 70%);" + "background-size:220% 100%;animation:arena-shimmer var(--loop-shimmer) var(--ease-in-out) infinite}" + "@media (prefers-reduced-motion:reduce){.arena-skeleton{animation:none;background:var(--panel)}}";
    document.head.appendChild(s);
  }, []);
}
export function Skeleton({ variant = "block", width, height, lines = 3, radius, style }) {
  useShimmer();
  const base = { borderRadius: radius || "var(--r-sm)" };
  if (variant === "circle") {
    const d = height || width || "var(--sp-10)";
    return React.createElement("div", {
      className: "arena-skeleton",
      "aria-hidden": "true",
      style: { width: d, height: d, borderRadius: "50%", ...style }
    });
  }
  if (variant === "text" || variant === "line") {
    if (variant === "text" && lines > 1) {
      return React.createElement("div", {
        role: "status",
        "aria-label": "Loading",
        style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 2.5)", width: width || "100%", ...style }
      }, Array.from({ length: lines }).map((_, i) => React.createElement("div", {
        key: i,
        className: "arena-skeleton",
        style: { height: "calc(var(--sp-1) * 3)", borderRadius: "var(--r-xs)", width: i === lines - 1 ? "62%" : "100%" }
      })));
    }
    return React.createElement("div", {
      className: "arena-skeleton",
      role: "status",
      "aria-label": "Loading",
      style: { height: height || "var(--sp-3)", width: width || "100%", borderRadius: "var(--r-xs)", ...style }
    });
  }
  return React.createElement("div", {
    className: "arena-skeleton",
    role: "status",
    "aria-label": "Loading",
    style: { width: width || "100%", height: height || "var(--sp-24)", ...base, ...style }
  });
}
