/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Skeleton } from "../../components/display/Skeleton.js";
import { Card } from "../../components/display/Card.js";
function Demo() {
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Variants"), React.createElement("div", {
    className: "row",
    style: { alignItems: "flex-start" }
  }, React.createElement("div", {
    style: { width: 200 }
  }, React.createElement(Skeleton, {
    variant: "text",
    lines: 3
  })), React.createElement(Skeleton, {
    variant: "line",
    width: 160
  }), React.createElement(Skeleton, {
    variant: "block",
    width: 120,
    height: 72
  }), React.createElement(Skeleton, {
    variant: "circle",
    width: 48
  })), React.createElement("div", {
    className: "sub"
  }, "In place — the placeholder matches the shape of what is loading"), React.createElement("div", {
    className: "row",
    style: { alignItems: "stretch" }
  }, React.createElement(Card, {
    eyebrow: "Delivery",
    title: "Client Portal",
    style: { width: 300 }
  }, React.createElement("div", {
    style: { display: "flex", gap: 12, alignItems: "center" }
  }, React.createElement(Skeleton, {
    variant: "circle",
    width: 40
  }), React.createElement("div", {
    style: { flex: 1 }
  }, React.createElement(Skeleton, {
    variant: "text",
    lines: 2
  })))), React.createElement(Card, {
    style: { width: 280 }
  }, React.createElement(Skeleton, {
    variant: "line",
    width: "45%",
    height: 11,
    style: { marginBottom: 12 }
  }), React.createElement(Skeleton, {
    variant: "block",
    height: 90
  }))));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
