/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
const DELTA_TONES = {
  neutral: { border: "var(--border-strong)", color: "var(--text-muted)" },
  positive: { border: "var(--success)", color: "var(--success)" },
  negative: { border: "var(--danger)", color: "var(--danger)" }
};
const VALUE_TONES = {
  neutral: "var(--bone)",
  accent: "var(--crimson)",
  gold: "var(--gold)",
  success: "var(--success)",
  warning: "var(--warning)",
  danger: "var(--danger)",
  info: "var(--info)"
};
export function StatCard({ label, value, tone = "neutral", delta, sub, icon, style, ...rest }) {
  const t = delta ? DELTA_TONES[delta.tone] || DELTA_TONES.neutral : null;
  const valueColor = VALUE_TONES[tone] || VALUE_TONES.neutral;
  return React.createElement("div", {
    style: {
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      padding: "calc(var(--sp-1) * 5)",
      minHeight: "calc(var(--sp-1) * 30)",
      display: "flex",
      flexDirection: "column",
      gap: "calc(var(--sp-1) * 2)",
      ...style
    },
    ...rest
  }, React.createElement("div", {
    style: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "calc(var(--sp-1) * 3)" }
  }, React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-2xs)", letterSpacing: "var(--ls-label)", textTransform: "uppercase", color: "var(--mute)" }
  }, label), icon && React.createElement("span", {
    "aria-hidden": "true",
    style: { display: "inline-flex", fontSize: "var(--icon-sm)", color: "var(--mute)", opacity: 0.6 }
  }, icon)), React.createElement("div", {
    style: {
      fontFamily: "var(--font-display)",
      fontWeight: "var(--fw-extrabold)",
      fontSize: "var(--fs-h2)",
      lineHeight: "var(--lh-snug)",
      color: valueColor,
      fontVariantNumeric: "tabular-nums",
      margin: 0
    }
  }, value), delta && React.createElement("span", {
    style: {
      alignSelf: "flex-start",
      display: "inline-flex",
      alignItems: "center",
      gap: "calc(var(--sp-1) * 1)",
      borderRadius: "var(--r-pill)",
      padding: "calc(var(--sp-1) * 0.5) calc(var(--sp-1) * 2)",
      fontFamily: "var(--font-body)",
      fontSize: "var(--dz-text-sm)",
      fontWeight: "var(--fw-semibold)",
      background: "transparent",
      border: "var(--bw) solid " + t.border,
      color: t.color
    }
  }, React.createElement("i", {
    className: delta.direction === "down" ? "ph-bold ph-arrow-down" : "ph-bold ph-arrow-up",
    "aria-hidden": "true"
  }), delta.value), sub && React.createElement("span", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--dz-text-sm)", color: "var(--mute)" }
  }, sub));
}
