/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect, useMemo, useRef, useState } from "react";
import { useContainerWidth, readBreakpoint } from "../../use-container-width.js";
export function Table({
  columns = [],
  rows = [],
  getRowKey,
  onRowClick,
  empty = "No data.",
  responsive = true,
  label,
  style
}) {
  if (!label)
    throw new Error("Table: `label` is required");
  const [ref, width] = useContainerWidth();
  const narrow = responsive && width !== null && width < readBreakpoint("md");
  const cellBase = { padding: "var(--dz-row-py) var(--dz-row-px)", fontSize: "var(--dz-text)", textAlign: "left", verticalAlign: "middle" };
  const headerLabel = {
    fontFamily: "var(--font-mono)",
    fontSize: "var(--dz-text-2xs)",
    letterSpacing: "var(--ls-column-header)",
    textTransform: "uppercase",
    color: "var(--mute)",
    fontWeight: "var(--fw-bold)"
  };
  const valueStyle = (c) => ({
    fontFamily: c.mono ? "var(--font-mono)" : "var(--font-body)",
    color: c.mono ? "var(--gold)" : "var(--bone-dim)"
  });
  const cellValue = (c, row) => c.render ? c.render(row[c.key], row) : row[c.key];
  const keyOf = (row, ri) => getRowKey ? getRowKey(row, ri) : ri;
  const gridRef = useRef(null);
  const [gridFocused, setGridFocused] = useState(false);
  const [cursor, setCursor] = useState({ row: 0, col: 0 });
  const rowLens = useMemo(() => [
    columns.length,
    ...rows.length === 0 ? [1] : rows.map(() => columns.length)
  ], [columns.length, rows.length]);
  const curRow = Math.min(Math.max(cursor.row, 0), Math.max(rowLens.length - 1, 0));
  const curCol = Math.min(Math.max(cursor.col, 0), Math.max((rowLens[curRow] || 0) - 1, 0));
  useEffect(() => {
    const g = gridRef.current;
    if (!g)
      return;
    const active = g.ownerDocument.activeElement;
    if (!active || !g.contains(active))
      return;
    const cell = g.querySelector('[role="gridcell"][tabindex="0"], [role="columnheader"][tabindex="0"]');
    if (cell && cell !== active)
      cell.focus();
  }, [curRow, curCol]);
  const onGridKeyDown = (e) => {
    const t = e.target;
    if (!t || typeof t.getAttribute !== "function")
      return;
    const role = t.getAttribute("role");
    if (role !== "gridcell" && role !== "columnheader")
      return;
    let row = curRow;
    let col = curCol;
    if (e.key === "ArrowUp")
      row = Math.max(0, row - 1);
    else if (e.key === "ArrowDown")
      row = Math.min(rowLens.length - 1, row + 1);
    else if (e.key === "ArrowLeft")
      col = Math.max(0, col - 1);
    else if (e.key === "ArrowRight")
      col = Math.min(Math.max((rowLens[row] || 1) - 1, 0), col + 1);
    else if (e.key === "Home")
      col = 0;
    else if (e.key === "End")
      col = Math.max((rowLens[row] || 1) - 1, 0);
    else if (e.key === "Enter") {
      e.preventDefault();
      if (onRowClick && curRow > 0 && rows.length > 0)
        onRowClick(rows[curRow - 1], curRow - 1);
      return;
    } else
      return;
    col = Math.min(col, Math.max((rowLens[row] || 1) - 1, 0));
    e.preventDefault();
    if (row !== curRow || col !== curCol)
      setCursor({ row, col });
  };
  const cellNav = (ri, ci) => ({
    tabIndex: ri === curRow && ci === curCol ? 0 : -1,
    onFocus: () => {
      if (ri !== curRow || ci !== curCol)
        setCursor({ row: ri, col: ci });
    }
  });
  const cellRing = (ri, ci) => ({
    outline: "none",
    boxShadow: ri === curRow && ci === curCol && gridFocused ? "inset 0 0 0 var(--focus-width) var(--focus-ring)" : undefined
  });
  return React.createElement("div", {
    ref,
    style: { width: "100%", ...style }
  }, narrow ? React.createElement("div", {
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 4)" }
  }, rows.length === 0 && React.createElement("div", {
    style: {
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      padding: "calc(var(--sp-1) * 8) calc(var(--sp-1) * 4)",
      textAlign: "center",
      color: "var(--mute)",
      fontSize: "var(--dz-text)"
    }
  }, empty), rows.map((row, ri) => React.createElement("div", {
    key: keyOf(row, ri),
    onClick: onRowClick ? () => onRowClick(row, ri) : undefined,
    style: {
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      padding: "var(--dz-row-px)",
      display: "flex",
      flexDirection: "column",
      gap: "var(--dz-stack)",
      cursor: onRowClick ? "pointer" : "default"
    }
  }, columns.map((c) => c.mobileLayout === "block" ? React.createElement("div", {
    key: c.key,
    style: {
      width: "100%",
      display: "flex",
      justifyContent: "flex-end",
      gap: "calc(var(--sp-1) * 2)",
      borderTop: "var(--bw) solid var(--color-base-300)",
      paddingTop: "calc(var(--sp-1) * 2)"
    }
  }, cellValue(c, row)) : React.createElement("div", {
    key: c.key,
    style: { display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "calc(var(--sp-1) * 3)" }
  }, React.createElement("span", {
    style: headerLabel
  }, c.header), React.createElement("span", {
    style: { ...valueStyle(c), minWidth: 0, textAlign: "right", fontSize: "var(--dz-text)" }
  }, cellValue(c, row))))))) : React.createElement("div", {
    style: {
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      overflow: "hidden",
      background: "var(--surface-card)"
    }
  }, React.createElement("table", {
    role: "grid",
    "aria-label": label,
    ref: gridRef,
    onKeyDown: onGridKeyDown,
    onFocus: () => setGridFocused(true),
    onBlur: (e) => {
      if (!e.currentTarget.contains(e.relatedTarget))
        setGridFocused(false);
    },
    style: { width: "100%", borderCollapse: "collapse", fontFamily: "var(--font-body)" }
  }, React.createElement("thead", null, React.createElement("tr", {
    role: "row",
    style: { background: "var(--panel)" }
  }, columns.map((c, ci) => React.createElement("th", {
    key: c.key,
    role: "columnheader",
    ...cellNav(0, ci),
    style: {
      ...cellBase,
      ...headerLabel,
      textAlign: c.align || "left",
      width: c.width,
      borderBottom: "var(--bw) solid var(--color-base-300)",
      ...cellRing(0, ci)
    }
  }, c.header)))), React.createElement("tbody", null, rows.length === 0 && React.createElement("tr", {
    role: "row"
  }, React.createElement("td", {
    role: "gridcell",
    colSpan: columns.length,
    ...cellNav(1, 0),
    style: {
      ...cellBase,
      textAlign: "center",
      color: "var(--mute)",
      padding: "calc(var(--sp-1) * 8) calc(var(--sp-1) * 4)",
      ...cellRing(1, 0)
    }
  }, empty)), rows.map((row, ri) => React.createElement("tr", {
    key: keyOf(row, ri),
    role: "row",
    onClick: onRowClick ? () => onRowClick(row, ri) : undefined,
    style: {
      borderTop: ri === 0 ? "none" : "var(--bw) solid var(--color-base-300)",
      cursor: onRowClick ? "pointer" : "default",
      transition: "background var(--dur-fast) var(--ease-out)"
    },
    onMouseEnter: onRowClick ? (e) => e.currentTarget.style.background = "var(--panel)" : undefined,
    onMouseLeave: onRowClick ? (e) => e.currentTarget.style.background = "transparent" : undefined
  }, columns.map((c, ci) => React.createElement("td", {
    key: c.key,
    role: "gridcell",
    ...cellNav(ri + 1, ci),
    style: { ...cellBase, ...valueStyle(c), textAlign: c.align || "left", ...cellRing(ri + 1, ci) }
  }, cellValue(c, row)))))))));
}
