/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { useContainerWidth, readBreakpoint } from "../../use-container-width.js";
export function Table({
  columns = [],
  rows = [],
  getRowKey,
  onRowClick,
  empty = "No data.",
  responsive = true,
  style
}) {
  const [ref, width] = useContainerWidth();
  const narrow = responsive && width !== null && width < readBreakpoint("md");
  const cellBase = { padding: "var(--dz-row-py) var(--dz-row-px)", fontSize: "var(--dz-text)", textAlign: "left", verticalAlign: "middle" };
  const headerLabel = {
    fontFamily: "var(--font-mono)",
    fontSize: "var(--dz-text-2xs)",
    letterSpacing: "var(--ls-column-header)",
    textTransform: "uppercase",
    color: "var(--mute)",
    fontWeight: "var(--fw-bold)"
  };
  const valueStyle = (c) => ({
    fontFamily: c.mono ? "var(--font-mono)" : "var(--font-body)",
    color: c.mono ? "var(--gold)" : "var(--bone-dim)"
  });
  const cellValue = (c, row) => c.render ? c.render(row[c.key], row) : row[c.key];
  const keyOf = (row, ri) => getRowKey ? getRowKey(row, ri) : ri;
  return React.createElement("div", {
    ref,
    style: { width: "100%", ...style }
  }, narrow ? React.createElement("div", {
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 4)" }
  }, rows.length === 0 && React.createElement("div", {
    style: {
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      padding: "calc(var(--sp-1) * 8) calc(var(--sp-1) * 4)",
      textAlign: "center",
      color: "var(--mute)",
      fontSize: "var(--dz-text)"
    }
  }, empty), rows.map((row, ri) => React.createElement("div", {
    key: keyOf(row, ri),
    onClick: onRowClick ? () => onRowClick(row, ri) : undefined,
    style: {
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      padding: "var(--dz-row-px)",
      display: "flex",
      flexDirection: "column",
      gap: "var(--dz-stack)",
      cursor: onRowClick ? "pointer" : "default"
    }
  }, columns.map((c) => c.mobileLayout === "block" ? React.createElement("div", {
    key: c.key,
    style: {
      width: "100%",
      display: "flex",
      justifyContent: "flex-end",
      gap: "calc(var(--sp-1) * 2)",
      borderTop: "var(--bw) solid var(--color-base-300)",
      paddingTop: "calc(var(--sp-1) * 2)"
    }
  }, cellValue(c, row)) : React.createElement("div", {
    key: c.key,
    style: { display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "calc(var(--sp-1) * 3)" }
  }, React.createElement("span", {
    style: headerLabel
  }, c.header), React.createElement("span", {
    style: { ...valueStyle(c), minWidth: 0, textAlign: "right", fontSize: "var(--dz-text)" }
  }, cellValue(c, row))))))) : React.createElement("div", {
    style: {
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-lg)",
      overflow: "hidden",
      background: "var(--surface-card)"
    }
  }, React.createElement("table", {
    style: { width: "100%", borderCollapse: "collapse", fontFamily: "var(--font-body)" }
  }, React.createElement("thead", null, React.createElement("tr", {
    style: { background: "var(--panel)" }
  }, columns.map((c) => React.createElement("th", {
    key: c.key,
    style: {
      ...cellBase,
      ...headerLabel,
      textAlign: c.align || "left",
      width: c.width,
      borderBottom: "var(--bw) solid var(--color-base-300)"
    }
  }, c.header)))), React.createElement("tbody", null, rows.length === 0 && React.createElement("tr", null, React.createElement("td", {
    colSpan: columns.length,
    style: { ...cellBase, textAlign: "center", color: "var(--mute)", padding: "calc(var(--sp-1) * 8) calc(var(--sp-1) * 4)" }
  }, empty)), rows.map((row, ri) => React.createElement("tr", {
    key: keyOf(row, ri),
    onClick: onRowClick ? () => onRowClick(row, ri) : undefined,
    style: {
      borderTop: ri === 0 ? "none" : "var(--bw) solid var(--color-base-300)",
      cursor: onRowClick ? "pointer" : "default",
      transition: "background var(--dur-fast) var(--ease-out)"
    },
    onMouseEnter: onRowClick ? (e) => e.currentTarget.style.background = "var(--panel)" : undefined,
    onMouseLeave: onRowClick ? (e) => e.currentTarget.style.background = "transparent" : undefined
  }, columns.map((c) => React.createElement("td", {
    key: c.key,
    style: { ...cellBase, ...valueStyle(c), textAlign: c.align || "left" }
  }, cellValue(c, row)))))))));
}
