/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Table } from "../../components/display/Table.js";
import { Avatar } from "../../components/display/Avatar.js";
import { Badge } from "../../components/display/Badge.js";
function Demo() {
  const rows = [
    { build: "#4821", project: "Client Portal", status: "ok", p95: "128 ms" },
    { build: "#4820", project: "Payment Gateway", status: "fail", p95: "340 ms" },
    { build: "#4819", project: "Internal Dashboard", status: "ok", p95: "96 ms" }
  ];
  const columns = [
    { key: "build", header: "Build", mono: true, width: "calc(var(--sp-1) * 22.5)" },
    { key: "project", header: "Project" },
    { key: "status", header: "Status", render: (v) => React.createElement(Badge, {
      tone: v === "ok" ? "success" : "danger",
      dot: true
    }, v === "ok" ? "Deployed" : "Down") },
    { key: "p95", header: "p95", align: "right", mono: true }
  ];
  return React.createElement("div", null, React.createElement("div", {
    className: "sub",
    style: { marginBottom: "var(--sp-3)" }
  }, "Avatar — person · entity · presence"), React.createElement("div", {
    className: "row",
    style: { alignItems: "center" }
  }, React.createElement(Avatar, {
    name: "Lucy Fernandez",
    status: "online"
  }), React.createElement(Avatar, {
    name: "Marco Ruiz",
    size: "lg",
    status: "busy"
  }), React.createElement(Avatar, {
    name: "Aurora Bank",
    shape: "rounded"
  }), React.createElement(Avatar, {
    name: "QA Bot",
    size: "sm",
    status: "offline"
  })), React.createElement("div", {
    className: "sub",
    style: { marginBottom: "var(--sp-3)" }
  }, "Table — with Badge in a cell"), React.createElement(Table, {
    columns,
    rows,
    getRowKey: (r) => r.build,
    onRowClick: () => {}
  }), React.createElement("div", {
    className: "sub",
    style: { marginTop: "var(--sp-5)", marginBottom: "var(--sp-3)" }
  }, "Card mode — the SAME table in a 340px container"), React.createElement("div", {
    style: { width: "calc(var(--sp-1) * 85)", border: "var(--bw) dashed var(--border-strong)", borderRadius: "var(--r-lg)", padding: "var(--sp-3)" }
  }, React.createElement(Table, {
    columns,
    rows
  })));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
