/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function Tag({ children, onRemove, style, ...rest }) {
  return React.createElement("span", {
    style: {
      display: "inline-flex",
      alignItems: "center",
      gap: "calc(var(--sp-1) * 1.5)",
      padding: "calc(var(--sp-1) * 1) calc(var(--sp-1) * 2.5)",
      background: "var(--panel)",
      color: "var(--bone-dim)",
      border: "var(--bw) solid var(--color-base-300)",
      borderRadius: "var(--r-sm)",
      fontFamily: "var(--font-body)",
      fontSize: "var(--dz-text-md)",
      ...style
    },
    ...rest
  }, children, onRemove && React.createElement("button", {
    onClick: onRemove,
    "aria-label": "Remove",
    style: { display: "inline-flex", alignItems: "center", background: "none", border: "none", color: "var(--mute)", cursor: "pointer", padding: 0, fontSize: "var(--icon-sm)", lineHeight: "var(--dz-lh)" }
  }, React.createElement("i", {
    className: "ph-bold ph-x"
  })));
}
