/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { Card } from "./Card.js";
export function UnauthCard({ brand, eyebrow, title, footer, children, style, ...rest }) {
  return React.createElement("div", {
    style: { width: "100%", maxWidth: "calc(var(--sp-1) * 95 + var(--sp-1) * 18 + var(--bw) * 2)", ...style },
    ...rest
  }, React.createElement(Card, {
    style: { boxShadow: "var(--shadow-3)" }
  }, React.createElement("div", {
    style: { padding: "calc(var(--sp-1) * 4)" }
  }, brand && React.createElement("div", {
    style: { display: "flex", marginBottom: "calc(var(--sp-1) * 7)" }
  }, brand), eyebrow && React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-label)", textTransform: "uppercase", color: "var(--crimson)", marginBottom: "calc(var(--sp-1) * 1.5)" }
  }, eyebrow), title && React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-extrabold)", fontSize: "var(--fs-h3)", color: "var(--bone)", marginBottom: "calc(var(--sp-1) * 6)" }
  }, title), children, footer && React.createElement("div", {
    style: { marginTop: "calc(var(--sp-1) * 5)", textAlign: "center", fontFamily: "var(--font-body)", fontSize: "var(--dz-text-md)", color: "var(--mute)" }
  }, footer))));
}
