/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
const TONES = {
  info: { color: "var(--info)", soft: "var(--info-soft)", icon: "ph-fill ph-info" },
  success: { color: "var(--success)", soft: "var(--success-soft)", icon: "ph-fill ph-check-circle" },
  warning: { color: "var(--warning)", soft: "var(--warning-soft)", icon: "ph-fill ph-warning" },
  danger: { color: "var(--danger)", soft: "var(--danger-soft)", icon: "ph-fill ph-warning-octagon" },
  neutral: { color: "var(--line-strong)", soft: "var(--panel)", icon: "ph-fill ph-note" }
};
export function Alert({ tone = "info", title, children, icon, action, onClose, style }) {
  const t = TONES[tone] || TONES.info;
  return React.createElement("div", {
    role: tone === "danger" ? "alert" : "status",
    style: {
      display: "flex",
      gap: "calc(var(--sp-1) * 3)",
      alignItems: "flex-start",
      padding: "calc(var(--sp-1) * 3.5) calc(var(--sp-1) * 4)",
      background: t.soft,
      border: "var(--bw) solid " + t.color,
      borderRadius: "var(--r-md)",
      ...style
    }
  }, React.createElement("i", {
    className: icon || t.icon,
    style: { color: t.color, fontSize: "var(--icon-lg)", lineHeight: "var(--dz-lh)", flexShrink: 0, marginTop: 0 }
  }), React.createElement("div", {
    style: { flex: 1 }
  }, title && React.createElement("div", {
    style: { fontFamily: "var(--font-body)", fontWeight: "var(--fw-semibold)", fontSize: "var(--dz-text)", color: "var(--bone)" }
  }, title), children && React.createElement("div", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--fs-sm)", color: "var(--bone-dim)", lineHeight: "var(--lh-body)", marginTop: title ? "var(--sp-1)" : 0 }
  }, children), action && React.createElement("button", {
    onClick: action.onClick,
    style: {
      marginTop: "calc(var(--sp-1) * 2.5)",
      background: "none",
      border: "none",
      padding: 0,
      cursor: "pointer",
      fontFamily: "var(--font-mono)",
      fontSize: "var(--dz-text-sm)",
      fontWeight: "var(--fw-bold)",
      letterSpacing: "var(--ls-uppercase-status)",
      textTransform: "uppercase",
      color: t.color
    }
  }, action.label)), onClose && React.createElement("button", {
    onClick: onClose,
    "aria-label": "Dismiss",
    style: { display: "inline-flex", alignItems: "center", background: "none", border: "none", color: "var(--mute)", cursor: "pointer", fontSize: "var(--icon-md)", lineHeight: "var(--dz-lh)" }
  }, React.createElement("i", {
    className: "ph-bold ph-x"
  })));
}
