/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Alert } from "../../components/feedback/Alert.js";
function Demo() {
  return React.createElement("div", {
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 3.5)", maxWidth: "calc(var(--sp-1) * 130)" }
  }, React.createElement(Alert, {
    tone: "info",
    title: "New version available"
  }, "Arena 1.0 includes Radio, Table, Menu, and Alert."), React.createElement(Alert, {
    tone: "success",
    title: "Deployment completed"
  }, "build #4821 in production."), React.createElement(Alert, {
    tone: "warning",
    title: "Staging environment",
    action: { label: "Go to production", onClick: () => {} }
  }, "Changes here don't affect real users."), React.createElement(Alert, {
    tone: "danger",
    title: "Certificate expired",
    onClose: () => {}
  }, "Renew the TLS within 48 h to avoid outages."));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
