/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
import { Button } from "../forms/Button.js";
export function ConfirmDialog({
  open = false,
  onCancel,
  onConfirm,
  title,
  eyebrow = "Confirm",
  children,
  confirmLabel = "Confirm",
  cancelLabel = "Cancel",
  destructive = false,
  requireText
}) {
  const [typed, setTyped] = useState("");
  if (!open)
    return null;
  const locked = requireText ? typed.trim() !== requireText : false;
  return React.createElement("div", {
    style: {
      position: "fixed",
      inset: 0,
      zIndex: "var(--z-modal-nested)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: "var(--scrim)",
      backdropFilter: "blur(var(--scrim-blur))",
      WebkitBackdropFilter: "blur(var(--scrim-blur))"
    }
  }, React.createElement("div", {
    role: "alertdialog",
    "aria-modal": "true",
    style: {
      width: "calc(var(--sp-1) * 115)",
      maxWidth: "92vw",
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--line-strong)",
      borderRadius: "var(--r-lg)",
      boxShadow: "var(--shadow-3)",
      overflow: "hidden"
    }
  }, React.createElement("div", {
    style: { padding: "calc(var(--sp-1) * 5.5) calc(var(--sp-1) * 6) 0" }
  }, React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-label)", textTransform: "uppercase", color: destructive ? "var(--danger)" : "var(--crimson)", marginBottom: "calc(var(--sp-1) * 2)" }
  }, eyebrow), title && React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-extrabold)", fontSize: "var(--fs-h3)", color: "var(--bone)", letterSpacing: "var(--ls-tight)" }
  }, title)), React.createElement("div", {
    style: { padding: "calc(var(--sp-1) * 4) calc(var(--sp-1) * 6)", color: "var(--bone-dim)", fontFamily: "var(--font-body)", fontSize: "var(--fs-md)", lineHeight: "var(--lh-body)" }
  }, children, requireText && React.createElement("div", {
    style: { marginTop: "calc(var(--sp-1) * 3.5)" }
  }, React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-field-label)", textTransform: "uppercase", color: "var(--mute)", marginBottom: "calc(var(--sp-1) * 1.5)" }
  }, 'Type "', requireText, '" to confirm'), React.createElement("input", {
    value: typed,
    onChange: (e) => setTyped(e.target.value),
    autoFocus: true,
    style: {
      width: "100%",
      height: "var(--dz-ctl-h)",
      boxSizing: "border-box",
      padding: "0 calc(var(--sp-1) * 3)",
      background: "var(--surface-input)",
      border: "var(--bw) solid " + (locked && typed ? "var(--danger)" : "var(--color-base-300)"),
      borderRadius: "var(--r-sm)",
      color: "var(--bone)",
      fontFamily: "var(--font-mono)",
      fontSize: "var(--dz-text)",
      outline: "none"
    }
  }))), React.createElement("div", {
    style: { display: "flex", justifyContent: "flex-end", gap: "calc(var(--sp-1) * 2.5)", padding: "0 calc(var(--sp-1) * 6) calc(var(--sp-1) * 5.5)" }
  }, React.createElement(Button, {
    variant: "ghost",
    onClick: onCancel
  }, cancelLabel), React.createElement(Button, {
    variant: "primary",
    onClick: onConfirm,
    disabled: locked,
    style: destructive ? { background: "var(--danger-fill)", color: "var(--color-error-content)" } : undefined
  }, confirmLabel))));
}
