/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect } from "react";
let injected = false;
function usePopKeyframes() {
  useEffect(() => {
    if (injected || typeof document === "undefined")
      return;
    injected = true;
    const s = document.createElement("style");
    s.setAttribute("data-arena-dialog", "");
    s.textContent = "@keyframes arena-pop{from{opacity:0;transform:translateY(var(--sp-2)) scale(.98)}to{opacity:1;transform:none}}" + "@media (prefers-reduced-motion:reduce){@keyframes arena-pop{from{opacity:0}to{opacity:1}}}";
    document.head.appendChild(s);
  }, []);
}
export function Dialog({ open, onClose, title, eyebrow, children, footer, width = "calc(var(--sp-1) * 120)" }) {
  usePopKeyframes();
  if (!open)
    return null;
  return React.createElement("div", {
    onClick: onClose,
    style: {
      position: "fixed",
      inset: 0,
      zIndex: "var(--z-modal)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: "var(--scrim)",
      backdropFilter: "blur(var(--scrim-blur))",
      WebkitBackdropFilter: "blur(var(--scrim-blur))"
    }
  }, React.createElement("div", {
    onClick: (e) => e.stopPropagation(),
    role: "dialog",
    "aria-modal": "true",
    style: {
      width,
      maxWidth: "92vw",
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--line-strong)",
      borderRadius: "var(--r-lg)",
      boxShadow: "var(--shadow-3)",
      overflow: "hidden",
      animation: "arena-pop var(--dur-mid) var(--ease-emphatic)"
    }
  }, React.createElement("div", {
    style: { padding: "calc(var(--sp-1) * 5.5) calc(var(--sp-1) * 6) 0" }
  }, eyebrow && React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-label)", textTransform: "uppercase", color: "var(--crimson)", marginBottom: "calc(var(--sp-1) * 2)" }
  }, eyebrow), title && React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-extrabold)", fontSize: "var(--fs-h3)", color: "var(--bone)", letterSpacing: "var(--ls-tight)" }
  }, title)), React.createElement("div", {
    style: { padding: "calc(var(--sp-1) * 4) calc(var(--sp-1) * 6)", color: "var(--bone-dim)", fontFamily: "var(--font-body)", fontSize: "var(--fs-md)", lineHeight: "var(--lh-body)" }
  }, children), footer && React.createElement("div", {
    style: { display: "flex", justifyContent: "flex-end", gap: "calc(var(--sp-1) * 2.5)", padding: "0 calc(var(--sp-1) * 6) calc(var(--sp-1) * 5.5)" }
  }, footer)));
}
