/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { EmptyState } from "../../components/feedback/EmptyState.js";
import { ErrorState } from "../../components/feedback/ErrorState.js";
import { Button } from "../../components/forms/Button.js";
function Demo() {
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Neither state is a dead end — each one names the way out"), React.createElement("div", {
    className: "row"
  }, React.createElement(EmptyState, {
    style: { flex: "1 1 0", minWidth: 0, boxSizing: "border-box" },
    icon: React.createElement("i", {
      className: "ph-duotone ph-folder-open"
    }),
    title: "No projects yet",
    message: "Create your first project to start deploying.",
    action: React.createElement(Button, null, "New project")
  }), React.createElement(ErrorState, {
    style: { flex: "1 1 0", minWidth: 0, boxSizing: "border-box" },
    icon: React.createElement("i", {
      className: "ph-fill ph-warning-octagon"
    }),
    title: "Couldn't load the panel",
    message: "No connection to the metrics service.",
    code: "ERR_UPSTREAM_504",
    onRetry: () => {},
    secondaryAction: React.createElement(Button, {
      variant: "secondary"
    }, "View logs")
  })), React.createElement("div", {
    className: "sub"
  }, "EmptyState invites the first action · ErrorState retries and exposes the code"));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
