/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Dialog } from "../../components/feedback/Dialog.js";
import { Toast } from "../../components/feedback/Toast.js";
import { Tooltip } from "../../components/feedback/Tooltip.js";
import { ProgressBar } from "../../components/feedback/ProgressBar.js";
import { Spinner } from "../../components/feedback/Spinner.js";
import { Button } from "../../components/forms/Button.js";
function Demo() {
  const [o, setO] = React.useState(false);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Toast"), React.createElement("div", {
    className: "row",
    style: { alignItems: "flex-start" }
  }, React.createElement(Toast, {
    tone: "success",
    title: "Deployment completed",
    message: "build #4821 in production",
    onClose: () => {}
  }), React.createElement(Toast, {
    tone: "danger",
    title: "Pipeline failed",
    message: "e2e tests in checkout",
    onClose: () => {}
  })), React.createElement("div", {
    className: "sub"
  }, "Tooltip · Dialog"), React.createElement("div", {
    className: "row"
  }, React.createElement(Tooltip, {
    content: "Roll back to the previous build"
  }, React.createElement(Button, {
    variant: "secondary"
  }, "Hover here")), React.createElement(Button, {
    variant: "primary",
    onClick: () => setO(true)
  }, "Open dialog")), React.createElement("div", {
    className: "sub"
  }, "ProgressBar"), React.createElement("div", {
    className: "row",
    style: { flexDirection: "column", alignItems: "stretch", gap: 14 }
  }, React.createElement(ProgressBar, {
    label: "Deploying build #4821",
    value: 64
  }), React.createElement(ProgressBar, {
    tone: "success",
    label: "Published",
    value: 100
  }), React.createElement(ProgressBar, {
    indeterminate: true,
    label: "Connecting…"
  })), React.createElement("div", {
    className: "sub"
  }, "Spinner — sizes and tones"), React.createElement("div", {
    className: "row"
  }, React.createElement(Spinner, {
    size: "sm",
    label: "Loading"
  }), React.createElement(Spinner, {
    size: "md",
    label: "Loading projects"
  }), React.createElement(Spinner, {
    size: "lg",
    tone: "gold",
    label: "Connecting"
  }), React.createElement(Spinner, {
    tone: "neutral",
    label: "Loading"
  }), React.createElement("span", {
    style: { display: "inline-flex", alignItems: "center", gap: 8, background: "var(--crimson)", color: "var(--on-accent)", borderRadius: "var(--r-sm)", padding: "0 14px", height: 40, fontFamily: "var(--font-body)", fontWeight: 600, fontSize: 14 }
  }, React.createElement(Spinner, {
    size: "sm",
    tone: "on-accent",
    label: "Deploying"
  }), "Deploying")), React.createElement(Dialog, {
    open: o,
    onClose: () => setO(false),
    eyebrow: "Confirm",
    title: "Deploy to production",
    footer: React.createElement(React.Fragment, null, React.createElement(Button, {
      variant: "ghost",
      onClick: () => setO(false)
    }, "Cancel"), React.createElement(Button, {
      onClick: () => setO(false)
    }, "Deploy"))
  }, "This action publishes build #4821 for all users. It can be rolled back at any time."));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
