/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
export function Onboarding({ open, steps = [], index = 0, onNext, onBack, onSkip, onDone, anchorRect }) {
  if (!open || !steps.length)
    return null;
  const step = steps[index] || {};
  const last = index === steps.length - 1;
  const W = 320;
  const EDGE = 16;
  let pos = { position: "fixed", right: "calc(var(--sp-1) * 6)", bottom: "calc(var(--sp-1) * 6)", zIndex: "var(--z-onboarding)" };
  if (anchorRect) {
    const top = Math.min(anchorRect.bottom + 12, (typeof window !== "undefined" ? window.innerHeight : 900) - 220);
    let left = anchorRect.left;
    if (typeof window !== "undefined")
      left = Math.min(left, window.innerWidth - W - EDGE);
    pos = { position: "fixed", top, left: Math.max(EDGE, left), zIndex: "var(--z-onboarding)" };
  }
  const foot = { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-uppercase-status)" };
  return React.createElement(React.Fragment, null, React.createElement("div", {
    onClick: onSkip,
    style: { position: "fixed", inset: 0, zIndex: "calc(var(--z-onboarding) - 10)", background: "var(--scrim)" }
  }), React.createElement("div", {
    role: "dialog",
    "aria-modal": "true",
    "aria-label": step.title,
    style: {
      ...pos,
      width: "calc(var(--sp-1) * 80)",
      maxWidth: "92vw",
      background: "var(--surface-card)",
      border: "var(--bw) solid var(--line-strong)",
      borderRadius: "var(--r-lg)",
      boxShadow: "var(--shadow-3)",
      padding: "calc(var(--sp-1) * 5)"
    }
  }, step.eyebrow && React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-label)", textTransform: "uppercase", color: "var(--crimson)", marginBottom: "calc(var(--sp-1) * 2)" }
  }, step.eyebrow), step.title && React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-extrabold)", fontSize: "var(--fs-h4)", color: "var(--bone)", letterSpacing: "var(--ls-tight)" }
  }, step.title), step.body && React.createElement("div", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--fs-md)", lineHeight: "var(--lh-body)", color: "var(--bone-dim)", marginTop: "calc(var(--sp-1) * 2)" }
  }, step.body), React.createElement("div", {
    style: { display: "flex", alignItems: "center", gap: "calc(var(--sp-1) * 1.5)", marginTop: "calc(var(--sp-1) * 4.5)" }
  }, React.createElement("div", {
    style: { display: "flex", gap: "calc(var(--sp-1) * 1.5)", flex: 1 },
    "aria-label": "Step " + (index + 1) + " of " + steps.length
  }, steps.map((_, i) => React.createElement("span", {
    key: i,
    style: { width: i === index ? "calc(var(--sp-1) * 4.5)" : "var(--sp-2)", height: "calc(var(--sp-1) * 2)", borderRadius: "var(--r-pill)", background: i === index ? "var(--crimson)" : "var(--line-strong)", transition: "width var(--dur-mid) var(--ease-out)" }
  }))), index > 0 && React.createElement("button", {
    onClick: onBack,
    style: { ...foot, background: "none", border: "none", cursor: "pointer", color: "var(--mute)", fontWeight: "var(--fw-bold)", textTransform: "uppercase" }
  }, "Back"), !last && React.createElement("button", {
    onClick: onSkip,
    style: { ...foot, background: "none", border: "none", cursor: "pointer", color: "var(--mute)", fontWeight: "var(--fw-bold)", textTransform: "uppercase" }
  }, "Skip"), React.createElement("button", {
    onClick: last ? onDone : onNext,
    style: {
      height: "calc(var(--sp-1) * 8.5)",
      padding: "0 calc(var(--sp-1) * 4)",
      background: "var(--crimson)",
      color: "var(--on-accent)",
      border: "none",
      borderRadius: "var(--r-sm)",
      fontFamily: "var(--font-body)",
      fontWeight: "var(--fw-semibold)",
      fontSize: "var(--dz-text-md)",
      cursor: "pointer"
    }
  }, last ? "Got it" : "Next"))));
}
