/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { Onboarding } from "../../components/feedback/Onboarding.js";
import { Button } from "../../components/forms/Button.js";
const steps = [
  { eyebrow: "Welcome", title: "Your first deployment", body: "From here you will deploy and roll back with one click." },
  { title: "Command palette", body: "Press Cmd/Ctrl+K to run any action without the mouse." },
  { title: "All set", body: "You can reopen this guide from Help anytime." }
];
function Demo() {
  const [open, setOpen] = React.useState(true);
  const [step, setStep] = React.useState(0);
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Skip is offered on every step — a tour is never a trap"), React.createElement("div", {
    className: "row"
  }, React.createElement(Button, {
    variant: "secondary",
    size: "sm",
    onClick: () => {
      setStep(0);
      setOpen(true);
    }
  }, "Start tour"), React.createElement("span", {
    style: { color: "var(--mute)", fontFamily: "var(--font-mono)", fontSize: 12 }
  }, "Step ", React.createElement("span", {
    style: { color: "var(--gold)" }
  }, Math.min(step + 1, steps.length)), " of ", steps.length, !open && " · dismissed")), React.createElement(Onboarding, {
    open,
    index: step,
    steps,
    onNext: () => setStep((s) => s + 1),
    onBack: () => setStep((s) => s - 1),
    onSkip: () => setOpen(false),
    onDone: () => setOpen(false)
  }));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
