/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect } from "react";
let injected = false;
function useSpinKeyframes() {
  useEffect(() => {
    if (injected || typeof document === "undefined")
      return;
    injected = true;
    const s = document.createElement("style");
    s.setAttribute("data-arena-spinner", "");
    s.textContent = "@keyframes arena-spinner{to{transform:rotate(360deg)}}" + ".arena-spinner{animation:arena-spinner var(--loop-spin) linear infinite}" + "@media (prefers-reduced-motion:reduce){.arena-spinner{animation-duration:var(--loop-reduced)}}";
    document.head.appendChild(s);
  }, []);
}
const SIZES = { sm: "var(--icon-sm)", md: "var(--sp-5)", lg: "var(--sp-8)" };
const TONES = {
  accent: "var(--crimson)",
  gold: "var(--gold)",
  neutral: "var(--mute)",
  "on-accent": "var(--on-accent)"
};
export function Spinner({ size = "md", tone = "accent", label = "Loading", style, ...rest }) {
  useSpinKeyframes();
  const d = SIZES[size] || SIZES.md;
  const color = TONES[tone] || TONES.accent;
  return React.createElement("span", {
    role: "status",
    "aria-label": label,
    style: { display: "inline-flex", color, ...style },
    ...rest
  }, React.createElement("span", {
    className: "arena-spinner",
    "aria-hidden": "true",
    style: {
      width: d,
      height: d,
      boxSizing: "border-box",
      border: "var(--bw-strong) solid currentColor",
      borderTopColor: "transparent",
      borderRadius: "50%",
      display: "inline-block"
    }
  }));
}
