/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect, useId, useRef, useState } from "react";
import { delayOpen, delayClose } from "../../tokens.generated.js";
let injected = false;
function useFadeKeyframes() {
  useEffect(() => {
    if (injected || typeof document === "undefined")
      return;
    injected = true;
    const s = document.createElement("style");
    s.setAttribute("data-arena-tooltip", "");
    s.textContent = "@keyframes arena-fade{from{opacity:0}to{opacity:1}}";
    document.head.appendChild(s);
  }, []);
}
export function Tooltip({ children, label }) {
  if (!label)
    throw new Error("Tooltip: `label` is required");
  useFadeKeyframes();
  const [show, setShow] = useState(false);
  const bubbleId = `tooltip-${useId().replace(/:/g, "")}`;
  const timer = useRef(null);
  const clear = () => {
    if (timer.current !== null) {
      clearTimeout(timer.current);
      timer.current = null;
    }
  };
  const schedule = (next, ms) => {
    clear();
    timer.current = setTimeout(() => setShow(next), ms);
  };
  const now = (next) => {
    clear();
    setShow(next);
  };
  useEffect(() => () => clear(), []);
  const described = React.isValidElement(children) ? React.cloneElement(children, { "aria-describedby": show ? bubbleId : undefined }) : children;
  return React.createElement("span", {
    style: { position: "relative", display: "inline-flex" },
    onMouseEnter: () => schedule(true, delayOpen),
    onMouseLeave: () => schedule(false, delayClose),
    onFocus: () => now(true),
    onBlur: () => now(false),
    onKeyDown: (e) => {
      if (e.key === "Escape")
        now(false);
    }
  }, described, show && React.createElement("span", {
    role: "tooltip",
    id: bubbleId,
    style: {
      position: "absolute",
      bottom: "100%",
      left: "50%",
      transform: "translateX(-50%) translateY(calc(var(--sp-2) * -1))",
      whiteSpace: "nowrap",
      padding: "calc(var(--sp-1) * 1.5) calc(var(--sp-1) * 2.5)",
      background: "var(--bone)",
      color: "var(--ink)",
      fontFamily: "var(--font-mono)",
      fontSize: "var(--dz-text-xs)",
      borderRadius: "var(--r-sm)",
      boxShadow: "var(--shadow-2)",
      zIndex: "var(--z-tooltip)",
      animation: "arena-fade var(--dur-fast) var(--ease-out)"
    }
  }, label));
}
