/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useEffect, useRef, useState } from "react";
import { delayOpen, delayClose } from "../../tokens.generated.js";
let injected = false;
function useFadeKeyframes() {
  useEffect(() => {
    if (injected || typeof document === "undefined")
      return;
    injected = true;
    const s = document.createElement("style");
    s.setAttribute("data-arena-tooltip", "");
    s.textContent = "@keyframes arena-fade{from{opacity:0}to{opacity:1}}";
    document.head.appendChild(s);
  }, []);
}
export function Tooltip({ children, content, style }) {
  useFadeKeyframes();
  const [show, setShow] = useState(false);
  const timer = useRef(null);
  const schedule = (next, ms) => {
    if (timer.current !== null)
      clearTimeout(timer.current);
    timer.current = setTimeout(() => setShow(next), ms);
  };
  useEffect(() => () => {
    if (timer.current !== null)
      clearTimeout(timer.current);
  }, []);
  return React.createElement("span", {
    style: { position: "relative", display: "inline-flex", ...style },
    onMouseEnter: () => schedule(true, delayOpen),
    onMouseLeave: () => schedule(false, delayClose)
  }, children, show && React.createElement("span", {
    role: "tooltip",
    style: {
      position: "absolute",
      bottom: "100%",
      left: "50%",
      transform: "translateX(-50%) translateY(calc(var(--sp-2) * -1))",
      whiteSpace: "nowrap",
      padding: "calc(var(--sp-1) * 1.5) calc(var(--sp-1) * 2.5)",
      background: "var(--bone)",
      color: "var(--ink)",
      fontFamily: "var(--font-mono)",
      fontSize: "var(--dz-text-xs)",
      borderRadius: "var(--r-sm)",
      boxShadow: "var(--shadow-2)",
      zIndex: "var(--z-tooltip)",
      animation: "arena-fade var(--dur-fast) var(--ease-out)"
    }
  }, content));
}
