/* Writes frameworks/react/vendor/*.js. React 18 is CommonJS-only, so this bundles it
 * to ESM for the demo pages' importmap, appending named exports Bun's static
 * detection misses and keeping `react` external so it stays a singleton.
 * See DOUBTS.md section 5 before changing any of that. */

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');
const req = createRequire(import.meta.url);

export const BANNER =
  '/* GENERATED by scripts/build-vendor.mjs — edit that, not this.\n'
  + ' * A CommonJS->ESM bundle of React 18, which ships no ESM build of its own,\n'
  + ' * for the demo pages\' <script type="importmap">. NODE_ENV is baked in as\n'
  + ' * "development". See build-vendor.mjs for the full rationale. */\n';

export const ENTRIES = [
  { entry: 'react/index.js', specifier: 'react', out: 'React.js', real: 'react', external: [] },
  { entry: 'react/jsx-runtime.js', specifier: 'react/jsx-runtime', out: 'ReactJsxRuntime.js', real: 'react/jsx-runtime.js', external: ['react'] },
  { entry: 'react-dom/client.js', specifier: 'react-dom/client', out: 'ReactDomClient.js', real: 'react-dom/client.js', external: ['react'] },
];

function realExportNames(root, real) {
  return Object.keys(req(join(root, 'node_modules', real)));
}

export function withNamedExports(code, names) {
  return code.replace(/export default (.+);\s*$/, (_m, expr) => {
    const named = names.map((n) => `export const ${n} = __arenaDefault.${n};`).join('\n');
    return `const __arenaDefault = ${expr};\nexport default __arenaDefault;\n${named}\n`;
  });
}

export async function buildVendor(opts = {}) {
  const root = opts.root ?? repoRoot;
  const files = new Map();
  for (const e of ENTRIES) {
    const result = await Bun.build({
      entrypoints: [join(root, 'node_modules', e.entry)],
      format: 'esm',
      target: 'browser',
      define: { 'process.env.NODE_ENV': '"development"' },
      external: e.external,
    });
    if (!result.success) {
      const messages = result.logs.map((l) => l.message).join('\n');
      throw new Error(`build-vendor: ${e.entry} failed to bundle\n${messages}`);
    }
    const raw = await result.outputs[0].text();
    const names = realExportNames(root, e.real);
    files.set(e.out, BANNER + withNamedExports(raw, names));
  }
  return files;
}

async function main() {
  const files = await buildVendor();
  const dir = join(repoRoot, 'frameworks/react/vendor');
  for (const [name, content] of files) {
    writeFileSync(join(dir, name), content);
    console.log(`wrote frameworks/react/vendor/${name}`);
  }
}

if (import.meta.main) await main();
