/* frameworks/react/vendor/*.js — GENERATED by this script. Edit here, not there.
 *
 * React 18.3.1 ships CommonJS only — its `exports` map has no ESM condition
 * and no `.mjs` — but a demo page's `<script type="importmap">` needs real
 * ES modules to point a bare specifier at. Bun's bundler (`Bun.build`,
 * `--format=esm`) converts CJS to ESM, but its static export detection only
 * sees a module's `exports.x = y` assignments when they sit at the CJS
 * wrapper's top level. React's assignments sit one level deeper, inside an
 * IIFE the source uses to scope its DevTools-hook variables — so the raw
 * Bun output for all three entries below is `export default <cjsExports>;`
 * and nothing else: every `import { useState } from 'react'` a demo page
 * makes would resolve to undefined.
 *
 * withNamedExports fixes that by appending one `export const <name> =
 * <default>.<name>;` per key the installed package actually exports — read
 * with `createRequire`, not hand-listed, so the export list can never drift
 * from whatever version is pinned in package.json. Every added line is a
 * genuine static ESM export, so both the default-import and named-import
 * forms a component might use resolve correctly.
 *
 * react-dom/client (and react/jsx-runtime) are bundled with `react` left
 * external: React must stay a singleton. Inlining a second copy into each
 * bundle would give the page two independent React instances sharing no
 * internal state, which breaks hooks and context in ways that are silent
 * until they are not.
 *
 * NODE_ENV is baked in as "development" via `define`, which also erases the
 * production branch entirely — no bare `process.env` reference reaches the
 * browser, which has no such global. These are demo/specimen pages, never
 * shipped to a real user, so development React's extra warnings (missing
 * `key`, effect dependency mistakes, `act()` reminders) are worth more here
 * than the size and speed a production build would save.
 *
 *   bun scripts/build-vendor.mjs   -> writes frameworks/react/vendor/*.js
 *   bun run build:vendor           -> same, via package.json
 */
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');
const req = createRequire(import.meta.url);

export const BANNER =
  '/* GENERATED by scripts/build-vendor.mjs — edit that, not this.\n'
  + ' * A CommonJS->ESM bundle of React 18, which ships no ESM build of its own,\n'
  + ' * for the demo pages\' <script type="importmap">. NODE_ENV is baked in as\n'
  + ' * "development". See build-vendor.mjs for the full rationale. */\n';

/** One vendor entry: the npm file Bun bundles, the bare specifier a demo
 *  page's importmap resolves to it (documentation only — nothing here reads
 *  it), the output filename under frameworks/react/vendor/, the real
 *  package entry `require`d to read its exact named exports, and which bare
 *  specifiers must stay external so React remains a singleton across the
 *  three bundles.
 *  @type {{entry: string, specifier: string, out: string, real: string, external: string[]}[]} */
export const ENTRIES = [
  { entry: 'react/index.js', specifier: 'react', out: 'react.js', real: 'react', external: [] },
  { entry: 'react/jsx-runtime.js', specifier: 'react/jsx-runtime', out: 'react-jsx-runtime.js', real: 'react/jsx-runtime.js', external: ['react'] },
  { entry: 'react-dom/client.js', specifier: 'react-dom/client', out: 'react-dom-client.js', real: 'react-dom/client.js', external: ['react'] },
];

/** @param {string} root @param {string} real @returns {string[]} every
 *  own-enumerable key the installed CJS package exports. */
function realExportNames(root, real) {
  return Object.keys(req(join(root, 'node_modules', real)));
}

/** Turns a Bun ESM bundle's trailing `export default <expr>;` into that same
 *  default plus one named export per real key — see the file banner for why
 *  Bun's own conversion stops at the default.
 *  @param {string} code @param {string[]} names @returns {string} */
export function withNamedExports(code, names) {
  return code.replace(/export default (.+);\s*$/, (_m, expr) => {
    const named = names.map((n) => `export const ${n} = __arenaDefault.${n};`).join('\n');
    return `const __arenaDefault = ${expr};\nexport default __arenaDefault;\n${named}\n`;
  });
}

/** Bundles every ENTRIES member and shims its named exports.
 *  @param {{root?: string}} [opts]
 *  @returns {Promise<Map<string, string>>} output filename -> full file
 *  content (banner + shimmed bundle), in ENTRIES order. */
export async function buildVendor(opts = {}) {
  const root = opts.root ?? repoRoot;
  const files = new Map();
  for (const e of ENTRIES) {
    const result = await Bun.build({
      entrypoints: [join(root, 'node_modules', e.entry)],
      format: 'esm',
      target: 'browser',
      define: { 'process.env.NODE_ENV': '"development"' },
      external: e.external,
    });
    if (!result.success) {
      const messages = result.logs.map((l) => l.message).join('\n');
      throw new Error(`build-vendor: ${e.entry} failed to bundle\n${messages}`);
    }
    const raw = await result.outputs[0].text();
    const names = realExportNames(root, e.real);
    files.set(e.out, BANNER + withNamedExports(raw, names));
  }
  return files;
}

async function main() {
  const files = await buildVendor();
  const dir = join(repoRoot, 'frameworks/react/vendor');
  for (const [name, content] of files) {
    writeFileSync(join(dir, name), content);
    console.log(`wrote frameworks/react/vendor/${name}`);
  }
}

if (import.meta.main) await main();
