/* The renderer is a pure function of the declared types, so this suite hands it
 * type objects directly rather than reading api/types/ -- the same shape
 * serialize-token.test.mjs and serialize-script.test.mjs use, and the reason
 * they run identically under bun and plain node. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { renderApiModule, docComment, fieldType, API_TARGETS, buildApiModules } from './build-api-types.mjs';

test('an enum renders as a string-literal union', () => {
  const out = renderApiModule([{ name: 'Direction', kind: 'enum', values: ['up', 'down'] }]);
  assert.match(out, /export type Direction = 'up' \| 'down';/);
});

/* An enum's values are rendered as TypeScript literals, and a NUMBER is not a
 * string. Every enum in api/types/ was a string set until CatSlot, so the
 * emitter quoted unconditionally and nothing noticed. A quoted numeric set is
 * worse than a build error: it emits a union of strings that compiles, and the
 * layer's own `1 | 2 | 3` then disagrees with it in a way only check:api sees. */
test('renderApiModule emits a numeric enum unquoted', () => {
  const out = renderApiModule([{ name: 'CatSlot', kind: 'enum', description: 'x', values: [1, 2, 3] }]);
  assert.match(out, /export type CatSlot = 1 \| 2 \| 3;/);
});

test('renderApiModule still quotes a string enum', () => {
  const out = renderApiModule([{ name: 'Dir', kind: 'enum', description: 'x', values: ['up', 'down'] }]);
  assert.match(out, /export type Dir = 'up' \| 'down';/);
});

test('an object renders as an interface, with optional fields marked optional', () => {
  const out = renderApiModule([{
    name: 'Crumb', kind: 'object',
    fields: {
      label: { form: 'primitive', type: 'string', required: true },
      href: { form: 'primitive', type: 'string' },
    },
  }]);
  assert.match(out, /export interface Crumb \{/);
  assert.match(out, /^ {2}label: string;$/m);
  assert.match(out, /^ {2}href\?: string;$/m);
});

test('an enum-typed field renders as the enum name, not as a re-inlined union', () => {
  const out = renderApiModule([{
    name: 'StatDelta', kind: 'object',
    fields: { direction: { form: 'enum', type: 'Direction', required: true } },
  }]);
  assert.match(out, /^ {2}direction: Direction;$/m);
});

test('a description becomes a doc comment on the type and on the field', () => {
  const out = renderApiModule([{
    name: 'Crumb', kind: 'object', description: 'One entry in a trail.',
    fields: { label: { form: 'primitive', type: 'string', required: true, description: 'What the crumb reads.' } },
  }]);
  assert.match(out, /\/\*\* One entry in a trail\. \*\/\nexport interface Crumb \{/);
  assert.match(out, /^ {2}\/\*\* What the crumb reads\. \*\/$/m);
});

test('a multi-line description becomes a block comment, so no prose is lost', () => {
  const out = docComment('first line\nsecond line');
  assert.equal(out, '/**\n *  first line\n *  second line\n */');
});

test('the header names the generator and forbids editing the output', () => {
  const out = renderApiModule([]);
  assert.match(out, /GENERATED by scripts\/build-api-types\.mjs/);
  assert.match(out, /edit api\/types\/, not this file/);
});

test('a field that is a slot or an event is refused -- R1, a predefined object is pure data', () => {
  assert.throws(() => fieldType({ form: 'slot' }), /R1/);
  assert.throws(() => fieldType({ form: 'event' }), /R1/);
  assert.throws(() => fieldType({ form: 'array', of: 'string' }), /R1/);
});

test('an unknown kind is refused rather than silently skipped', () => {
  assert.throws(() => renderApiModule([{ name: 'X', kind: 'mapped' }]), /unknown kind "mapped"/);
});

test('both layers receive the identical body -- one contract, two import paths', () => {
  const modules = buildApiModules();
  assert.deepEqual([...modules.keys()], API_TARGETS);
  const [a, b] = [...modules.values()];
  assert.equal(a, b);
});

test('API_TARGETS names one file per layer, and neither lives under api/', () => {
  assert.deepEqual(API_TARGETS, [
    'frameworks/react/Api.generated.d.ts',
    'frameworks/angular/Api.generated.ts',
  ]);
});
