/* Generates tokens/{palette,typography,spacing,effects}.css from the DTCG
 * source in tokens/src/.
 *
 * Style Dictionary is used strictly as a loader, reference resolver and name
 * transformer — never as a value transformer. Its built-in CSS transforms
 * predate DTCG 2025.10 and would corrupt structured colors and {value,unit}
 * dimensions, so the only transform applied is name/kebab and every value is
 * rendered by scripts/lib/serialize-token.mjs.
 *
 *   bun scripts/build-tokens.mjs      -> writes the four files
 */
import StyleDictionary from 'style-dictionary';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { serialize } from './lib/serialize-token.mjs';
import { serializeScript, scriptName } from './lib/serialize-script.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const HEADER = '/* GENERATED by Style Dictionary — edit tokens/src/, not this file. */';

/** Each output file is one or more selector blocks, each fed by one source file.
 *  Exported so scripts/token-preview.test.mjs can derive its source-to-output
 *  assertions from this array instead of re-declaring the mapping by hand. */
export const FILES = [
  { out: 'palette.css', blocks: [
    { selector: ':root', source: 'palette.dark.json' },
    { selector: '.arena-light', source: 'palette.light.json' },
  ] },
  { out: 'typography.css', blocks: [
    { selector: ':root', source: 'typography.json' },
  ] },
  { out: 'spacing.css', blocks: [
    { selector: ':root', source: 'spacing.json' },
    { selector: ':root', source: 'icon.json' },
    { selector: '.arena-compact', source: 'density.compact.json' },
  ] },
  { out: 'effects.css', blocks: [
    { selector: ':root', source: 'effects.json' },
    { selector: ':root', source: 'layering.json' },
    { selector: ':root', source: 'chart.json' },
  ] },
];

const EXT = 'com.dravensoft.arena';

/** The generated JS modules, one per framework layer. Emission is per-layer
 *  rather than once into tokens/ so that a component's import never crosses the
 *  tokens/ <-> frameworks/ boundary: the import is intra-layer, the same shape
 *  as the ../charts/chart-internals.js that Calendar already carries, and the
 *  copy-in kit gains one entry in README.md's dependency list rather than a new
 *  concept. Both files carry identical bodies; only the extension differs,
 *  because React does not compile TypeScript and Angular needs a .ts to
 *  typecheck the import. */
export const SCRIPT_TARGETS = [
  'frameworks/react/tokens.generated.js',
  'frameworks/angular/tokens.generated.ts',
];

const SCRIPT_HEADER =
  '/* GENERATED by scripts/build-tokens.mjs — edit tokens/src/, not this file.\n'
  + ' *\n'
  + ' * Every export here is a token flagged script-readable in tokens/src/ and\n'
  + ' * emitted as a bare number because JS arithmetic consumes it. Each one also\n'
  + ' * ships as a CSS custom property; scripts/check-script-tokens.mjs asserts the\n'
  + ' * two carry the same value. A value bound at import time cannot re-theme or\n'
  + ' * re-densify — that is the accepted price of reading it in JS at all. */';

/** True when a resolved token opted into the JS target. */
const isScript = (token) => token.$extensions?.[EXT]?.script === true;

/** Every source file the CSS build reads, de-duplicated and in declaration
 *  order. Scanning FILES rather than a second list is what keeps the two
 *  targets from disagreeing about which sources exist. */
function scriptSources() {
  return [...new Set(FILES.flatMap((f) => f.blocks.map((b) => b.source)))];
}

/** Flagged tokens, in source order. Carries BOTH names: the kebab one the CSS
 *  custom property uses and the camel one the module exports. The gate needs
 *  both, and deriving one from the other is not safe in either direction —
 *  scriptName('sp-4') is 'sp4', but camel-to-kebab on 'sp4' yields 'sp4', not
 *  'sp-4', because there is no case change to split on. Carry, never re-derive.
 *  @returns {Promise<Array<{cssName: string, jsName: string, value: number, $description?: string}>>} */
export async function collectScriptTokens() {
  const out = [];
  for (const source of scriptSources()) {
    for (const item of walk(await load(source))) {
      if (item.group || !isScript(item.token)) continue;
      out.push({
        cssName: item.token.name,
        jsName: scriptName(item.token.name),
        value: serializeScript(item.token),
        $description: item.token.$description,
      });
    }
  }
  return out;
}

/** @returns {Promise<Map<string,string>>} repo-relative path -> module source */
export async function buildScriptModules() {
  const tokens = await collectScriptTokens();
  const lines = [SCRIPT_HEADER, ''];
  for (const t of tokens) {
    if (t.$description) lines.push(...comment(t.$description).split('\n').map((l) => l.replace(/^ {2}/, '')));
    lines.push(`export const ${t.jsName} = ${t.value};`);
  }
  const body = `${lines.join('\n')}\n`;
  return new Map(SCRIPT_TARGETS.map((path) => [path, body]));
}

/** Resolves one source file to its named, ordered token tree. */
async function load(source) {
  const sd = new StyleDictionary({
    source: [join(root, 'tokens/src', source)],
    platforms: { css: { transforms: ['name/kebab'] } },
  }, { verbosity: 'silent' });
  const { tokens } = await sd.getPlatformTokens('css');
  return tokens;
}

/** A single-line description is one `/* … *​/`; a multi-line one is a block. */
function comment(d) {
  if (!d.includes('\n')) return `  /* ${d} */`;
  return ['  /*', ...d.split('\n').map((l) => `     ${l}`), '   */'].join('\n');
}

/** A single-line $description becomes a trailing comment; a multi-line one
 *  becomes a block comment above the declaration, so no prose is lost. */
function render(token) {
  const decl = `  --${token.name}:${serialize(token)};`;
  const d = token.$description;
  if (!d) return decl;
  if (!d.includes('\n')) return `${decl} /* ${d} */`;
  return `${comment(d)}\n${decl}`;
}

/* Walks the resolved tree in source order, yielding group headings alongside
 * leaves. Group $descriptions are the section headings today's hand-written
 * files carry ("Radius", "Elevation", "Motion"), and they live on group nodes,
 * which never appear in allTokens — walking the tree is what keeps them. */
function* walk(node) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$') || child === null || typeof child !== 'object') continue;
    if (child.$value !== undefined) { yield { group: false, token: child }; continue; }
    if (child.$description) yield { group: true, description: child.$description };
    yield* walk(child);
  }
}

async function block({ selector, source }) {
  const lines = [];
  for (const item of walk(await load(source))) {
    if (!item.group) { lines.push(render(item.token)); continue; }
    if (lines.length) lines.push('');
    lines.push(comment(item.description));
  }
  return `${selector}{\n${lines.join('\n')}\n}`;
}

/** @returns {Promise<Map<string,string>>} output filename -> generated CSS */
export async function buildAll() {
  const out = new Map();
  for (const file of FILES) {
    const blocks = [];
    for (const b of file.blocks) blocks.push(await block(b));
    out.set(file.out, `${HEADER}\n${blocks.join('\n')}\n`);
  }
  return out;
}

async function main() {
  const built = await buildAll();
  for (const [name, css] of built) {
    writeFileSync(join(root, 'tokens', name), css);
    console.log(`build-tokens: wrote tokens/${name}`);
  }
  const modules = await buildScriptModules();
  for (const [path, source] of modules) {
    writeFileSync(join(root, path), source);
    console.log(`build-tokens: wrote ${path}`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
