/* Generates tokens/{palette,typography,spacing,effects}.css from the DTCG
 * source in tokens/src/.
 *
 * Style Dictionary is used strictly as a loader, reference resolver and name
 * transformer — never as a value transformer. Its built-in CSS transforms
 * predate DTCG 2025.10 and would corrupt structured colors and {value,unit}
 * dimensions, so the only transform applied is name/kebab and every value is
 * rendered by scripts/lib/serialize-token.mjs.
 *
 *   bun scripts/build-tokens.mjs      -> writes the four files
 */
import StyleDictionary from 'style-dictionary';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { serialize } from './lib/serialize-token.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const HEADER = '/* GENERATED by Style Dictionary — edit tokens/src/, not this file. */';

/** Each output file is one or more selector blocks, each fed by one source file. */
const FILES = [
  { out: 'palette.css', blocks: [
    { selector: ':root', source: 'palette.dark.json' },
    { selector: '.arena-light', source: 'palette.light.json' },
  ] },
  { out: 'typography.css', blocks: [
    { selector: ':root', source: 'typography.json' },
  ] },
  { out: 'spacing.css', blocks: [
    { selector: ':root', source: 'spacing.json' },
    { selector: ':root', source: 'icon.json' },
    { selector: '.arena-compact', source: 'density.compact.json' },
  ] },
  { out: 'effects.css', blocks: [
    { selector: ':root', source: 'effects.json' },
    { selector: ':root', source: 'layering.json' },
  ] },
];

/** Resolves one source file to its named, ordered token tree. */
async function load(source) {
  const sd = new StyleDictionary({
    source: [join(root, 'tokens/src', source)],
    platforms: { css: { transforms: ['name/kebab'] } },
  }, { verbosity: 'silent' });
  const { tokens } = await sd.getPlatformTokens('css');
  return tokens;
}

/** A single-line description is one `/* … *​/`; a multi-line one is a block. */
function comment(d) {
  if (!d.includes('\n')) return `  /* ${d} */`;
  return ['  /*', ...d.split('\n').map((l) => `     ${l}`), '   */'].join('\n');
}

/** A single-line $description becomes a trailing comment; a multi-line one
 *  becomes a block comment above the declaration, so no prose is lost. */
function render(token) {
  const decl = `  --${token.name}:${serialize(token)};`;
  const d = token.$description;
  if (!d) return decl;
  if (!d.includes('\n')) return `${decl} /* ${d} */`;
  return `${comment(d)}\n${decl}`;
}

/* Walks the resolved tree in source order, yielding group headings alongside
 * leaves. Group $descriptions are the section headings today's hand-written
 * files carry ("Radius", "Elevation", "Motion"), and they live on group nodes,
 * which never appear in allTokens — walking the tree is what keeps them. */
function* walk(node) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$') || child === null || typeof child !== 'object') continue;
    if (child.$value !== undefined) { yield { group: false, token: child }; continue; }
    if (child.$description) yield { group: true, description: child.$description };
    yield* walk(child);
  }
}

async function block({ selector, source }) {
  const lines = [];
  for (const item of walk(await load(source))) {
    if (!item.group) { lines.push(render(item.token)); continue; }
    if (lines.length) lines.push('');
    lines.push(comment(item.description));
  }
  return `${selector}{\n${lines.join('\n')}\n}`;
}

/** @returns {Promise<Map<string,string>>} output filename -> generated CSS */
export async function buildAll() {
  const out = new Map();
  for (const file of FILES) {
    const blocks = [];
    for (const b of file.blocks) blocks.push(await block(b));
    out.set(file.out, `${HEADER}\n${blocks.join('\n')}\n`);
  }
  return out;
}

async function main() {
  const built = await buildAll();
  for (const [name, css] of built) {
    writeFileSync(join(root, 'tokens', name), css);
    console.log(`build-tokens: wrote tokens/${name}`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
