/* Every compiled .js sibling under frameworks/react/components/ and
 * frameworks/react/ui_kits/console/ (every one with a .jsx of the same name
 * next to it) — GENERATED by this script. Edit the .jsx, not the .js next
 * to it.
 *
 * Every demo and specimen page used to ship an inline
 * <script type="text/babel" data-type="module" data-presets="react"> block,
 * loaded @babel/standalone (a 2.4MB bundle) over a plain <script> tag, and
 * called jsx-loader.js's window.arenaImport() to fetch, transpile and
 * recursively blob-URL every *.jsx it touched — component sources included,
 * re-transpiled from scratch by every page that imported them. Correct, and
 * the reason check:cards (45 pages, 18 of them JSX) spent roughly 14 of its
 * ~33s doing the same JSX-to-JS work over and over in a headless browser.
 *
 * This script does that work once, at build time, with Bun's own transpiler
 * — the same tool this repo already builds and tests with, so it introduces
 * no new toolchain. A demo page's inline script became a real sibling source
 * file (`<page>.entry.jsx`, extracted verbatim, its `await arenaImport(...)`
 * calls turned into ordinary static imports since there is no longer a
 * runtime loader to call), and every `<page>.entry.jsx` plus every component
 * `*.jsx` under the two trees below compiles to a `*.js` sibling: same
 * directory, same basename, so every relative import between them keeps
 * working unchanged except for one mechanical edit — `.jsx` becomes `.js` in
 * the specifier, because the browser now loads the compiled sibling, never
 * the JSX source. A plain `.js` helper a component imports (`chart-
 * internals.js`, `calendar-internals.js`, `use-container-width.js`) needs no
 * such rewrite: it already contains no JSX and is not part of this build's
 * output, so a component that imports one keeps pointing at the original.
 *
 * The transform itself uses classic mode (`React.createElement`, not the
 * automatic `react/jsx-runtime` import), matching what @babel/standalone's
 * default 'react' preset was already doing and what every one of these files
 * already assumes: all 49 components and all 19 entries import `React` by
 * name and rely on it being in scope, which only the classic transform
 * guarantees. Bun.Transpiler has no direct "classic" switch — the option
 * exists in its types but is inert (verified by hand: passing it changed
 * nothing) — so classic mode is reached the way Bun's own docs point at for
 * this exact case, through a tsconfig's `compilerOptions.jsx: "react"`.
 *
 *   bun scripts/build-demos.mjs   -> writes every *.js sibling of a *.jsx
 *                                    under frameworks/react/components/ and
 *                                    frameworks/react/ui_kits/console/
 *   bun run build:demos           -> same, via package.json
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, sep } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');

export const BANNER =
  '/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.\n'
  + ' * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs\n'
  + ' * for the full rationale. */\n';

/** The two source trees this build compiles every *.jsx under, recursively.
 *  Both hold component/entry sources whose relative imports resolve within
 *  the same tree (components/** imports only from components/**;
 *  ui_kits/console/** imports from both itself and components/**), so one
 *  discovery pass across both is enough for every import to resolve to a
 *  sibling *.js this same build also writes.
 *  @type {string[]} */
export const ROOTS = ['frameworks/react/components', 'frameworks/react/ui_kits/console'];

/** @param {string} dir @returns {string[]} absolute paths of every *.jsx
 *  under dir, recursive, sorted. */
function findJsxFiles(dir) {
  const found = [];
  const walk = (d) => {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const path = join(d, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.name.endsWith('.jsx')) found.push(path);
    }
  };
  walk(dir);
  return found.sort();
}

/** Rewrites a relative import/export specifier's `.jsx` extension to `.js`
 *  — the one edit a compiled sibling needs beyond the JSX transform itself,
 *  since the browser loads the compiled `.js`, never the `.jsx` it came
 *  from. Bun's transpiler normalizes quotes to double quotes on the way out,
 *  so matching only `"` here (not `'`) is enough for anything this script
 *  itself produces; verified against a real transpile rather than assumed.
 *  A specifier already ending in plain `.js` (a helper module with no JSX of
 *  its own — use-container-width.js, chart-internals.js, calendar-
 *  internals.js) is untouched, because no `.js` sibling of file with that
 *  extension exists — it already IS the file to import.
 *  @param {string} code @returns {string} */
export function rewriteRelativeJsxImports(code) {
  return code.replace(/(from\s*")(\.\.?\/[^"]+?)\.jsx"/g, '$1$2.js"');
}

/** @param {{root?: string}} [opts]
 *  @returns {Promise<Map<string, string>>} repo-relative output path (posix,
 *  `.js`) -> full file content (banner + compiled code), sorted by input
 *  path. */
export async function buildDemos(opts = {}) {
  const root = opts.root ?? repoRoot;
  const transpiler = new Bun.Transpiler({
    loader: 'jsx',
    tsconfig: JSON.stringify({ compilerOptions: { jsx: 'react' } }),
  });

  const files = new Map();
  for (const treeRoot of ROOTS) {
    for (const absPath of findJsxFiles(join(root, treeRoot))) {
      const source = readFileSync(absPath, 'utf8');
      const compiled = transpiler.transformSync(source);
      const rewritten = rewriteRelativeJsxImports(compiled);
      const outRel = relative(root, absPath).replace(/\.jsx$/, '.js').split(sep).join('/');
      files.set(outRel, BANNER + rewritten);
    }
  }
  return files;
}

async function main() {
  const files = await buildDemos();
  for (const [outRel, content] of files) {
    writeFileSync(join(repoRoot, outRel), content);
    console.log(`wrote ${outRel}`);
  }
  console.log(`build-demos: ${files.size} file(s) compiled`);
}

if (import.meta.main) await main();
