/* scripts/fetch-fonts.mjs
   Downloads the latin-subset woff2 binaries for Arena's three families into
   assets/fonts/ and (re)generates contracts/design-generated/fonts.css with
   local url()s only — no CDN request, CSP-clean. assets/fonts/ is the single
   source of truth, shared by every framework layer. Run: bun scripts/fetch-fonts.mjs */
import { writeFileSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const fontsDir = join(root, 'assets', 'fonts');
const cssPath = join(root, 'contracts', 'design-generated', 'fonts.css');

/* A modern-browser UA makes Google Fonts serve woff2 (not ttf). */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

/* The family list is derived from contracts/design/typography.json, not
 * declared here. When it was declared here, a variant author who changed
 * font.display to "Inter" got --font-display: Inter with no @font-face for
 * Inter, and fell through to system-ui with no error at all -- the worst
 * shape a broken promise can take. The weights stop being declared twice for
 * the same reason: FAMILIES.weights and the fw tokens agreed by discipline,
 * which is not a mechanism. */
export function families(root) {
  const src = JSON.parse(readFileSync(join(root, 'contracts/design/typography.json'), 'utf8'));
  const weights = Object.entries(src.fw)
    .filter(([k]) => !k.startsWith('$'))
    .map(([, t]) => t.$value)
    .sort((a, b) => a - b);
  return Object.entries(src.font)
    .filter(([k]) => !k.startsWith('$'))
    .map(([, token]) => {
      const css = token.$value[0];
      return { css, slug: css.toLowerCase().replace(/\s+/g, '-'), weights };
    });
}

async function google(css, weights) {
  const family = `${css.replace(/ /g, '+')}:wght@${weights.join(';')}`;
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`CSS fetch failed for ${css}: ${res.status}`);
  return res.text();
}

/* Pull the latin-subset @font-face blocks: each carries a font-weight and a
   woff2 src url and is tagged by Google Fonts with a "latin" subset comment. */
function latinFaces(cssText) {
  const faces = [];
  const re = /\/\*\s*latin\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(cssText)) !== null) {
    const block = m[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const src = /src:\s*url\(([^)]+\.woff2)\)/.exec(block)?.[1];
    if (weight && src) faces.push({ weight: Number(weight), src });
  }
  return faces;
}

async function download(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`binary fetch failed: ${url} ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

/** The whole emitted file, from an ordered face list. Pure: no network, no
 *  filesystem. The url() is two hops because fonts.css lives in
 *  contracts/design-generated/ and the binaries stay in assets/ at the root --
 *  the design level moved under contracts/, the binaries did not. */
export function fontsCss(faces) {
  const header =
    `/* contracts/design-generated/fonts.css — self-hosted, CSP-clean webfonts.\n` +
    `   GENERATED by scripts/fetch-fonts.mjs; edit that, not this. Binaries live in\n` +
    `   assets/fonts/. Families match contracts/design-generated/typography.css\n` +
    `   (Archivo / Familjen Grotesk / Spline Sans Mono). */\n`;
  const rules = faces.map(({ family, weight, file }) =>
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: normal;\n` +
    `  font-weight: ${weight};\n` +
    `  font-display: swap;\n` +
    `  src: url('../../assets/fonts/${file}') format('woff2');\n` +
    `}`);
  return `${header}\n${rules.join('\n\n')}\n`;
}

/** The face list derived from what is on disk, for regenerating the CSS without
 *  re-downloading anything.
 *
 *  A declared weight with no binary is SKIPPED rather than refused, because
 *  families() hands every family the same weight list -- every fw-* token --
 *  and Google Fonts does not serve every weight for every family. Archivo has
 *  400-900; Familjen Grotesk and Spline Sans Mono have 400-700, and
 *  familjen-grotesk-800.woff2 has never existed. Demanding one would refuse the
 *  tree as it has always stood.
 *
 *  A family with NO face is a different matter and does throw: that is the
 *  silent-failure shape check:fonts exists to catch -- a --font-display naming
 *  a family with no @font-face behind it, falling through to system-ui with no
 *  error at all. */
export function facesFromDisk(root) {
  const present = new Set(readdirSync(join(root, 'assets', 'fonts')));
  const faces = [];
  for (const fam of families(root)) {
    const before = faces.length;
    for (const weight of fam.weights) {
      const file = `${fam.slug}-${weight}.woff2`;
      if (present.has(file)) faces.push({ family: fam.css, weight, file });
    }
    if (faces.length === before)
      throw new Error(`no assets/fonts/${fam.slug}-*.woff2 for "${fam.css}" — run bun scripts/fetch-fonts.mjs without --css-only`);
  }
  return faces;
}

async function main() {
  mkdirSync(fontsDir, { recursive: true });
  const faces = [];
  for (const fam of families(root)) {
    const cssText = await google(fam.css, fam.weights);
    const googleFaces = latinFaces(cssText);
    for (const face of googleFaces) {
      const file = `${fam.slug}-${face.weight}.woff2`;
      writeFileSync(join(fontsDir, file), await download(face.src));
      faces.push({ family: fam.css, weight: face.weight, file });
    }
    console.log(`${fam.css}: ${googleFaces.length} weights`);
  }

  writeFileSync(cssPath, fontsCss(faces));
  console.log('wrote contracts/design-generated/fonts.css');
}

if (import.meta.main) {
  if (process.argv.includes('--css-only')) {
    writeFileSync(cssPath, fontsCss(facesFromDisk(root)));
    console.log('wrote contracts/design-generated/fonts.css (no download)');
  } else {
    await main();
  }
}
