/* GENERATED by scripts/build-api-types.mjs — edit api/types/, not this file.
 *
 * Every declaration here is a predefined object or an enum some Arena API
 * contract names. The same body is emitted into both layers so a component's
 * import never crosses the api/ <-> frameworks/ boundary — the rule
 * tokens.generated.* already carries. scripts/check-api.mjs asserts the
 * committed files match api/types/. See api/README.md for the vocabulary. */

/** One entry in a breadcrumb trail. `href` is omitted for the current page, which is never rendered as a link. */
export interface Crumb {
  /** What the crumb reads. */
  label: string;
  /** Where it goes. Absent on the last entry, the current location. */
  href?: string;
}

/** Whether a change was GOOD. Separate from Direction because revenue down is negative and latency down is positive, and only the product knows which. Every sign renders outline, never filled. */
export type DeltaTone = 'neutral' | 'positive' | 'negative';

/** Which way a number moved. Draws the arrow — nothing else. Deliberately separate from whether that movement was good. */
export type Direction = 'up' | 'down';

/** Both halves of the brand lock-up at once — the mark's slot and the wordmark. A fixed repertoire, not a ratio: sm an application frame, md a signed-out panel, lg the manual's Primary, xl the hero case. */
export type LogoSize = 'sm' | 'md' | 'lg' | 'xl';

/** Whether the parts sit side by side or stacked. */
export type Orientation = 'horizontal' | 'vertical';

/** How a metric moved. Preformatted — StatCard never formats. The pill's colour says whether the change was GOOD, not which way it points, which is why direction and tone are separate fields. */
export interface StatDelta {
  /** Preformatted, e.g. "+12%" or "-340ms". */
  value: string;
  /** Which way the number moved. Draws the arrow — nothing else. */
  direction: Direction;
  /** Whether that movement is GOOD. Defaults to neutral — an unlabelled delta claims nothing. */
  tone?: DeltaTone;
}

/** What state a value IS in right now, as against how it moved. Badge's vocabulary, so one set of tone names covers the system rather than a second set that is nearly the same. */
export type Tone = 'neutral' | 'accent' | 'gold' | 'success' | 'warning' | 'danger' | 'info';
