/* GENERATED by scripts/generate/arena/generate-api-types.mjs — edit contracts/api/types/, not this file.
 *
 * Every declaration here is a predefined object or an enum some Arena API
 * contract names. The same body is emitted into both layers so a component's
 * import never crosses the contracts/api/ <-> frameworks/ boundary — the rule
 * tokens.generated.* already carries. scripts/check/arena/check-api.mjs asserts the
 * committed files match contracts/api/types/. See contracts/api/README.md for the vocabulary. */

/** One event in a feed: someone did something to something, then. Arena draws every field — a consumer cannot place their own markup inside a row. */
export interface ActivityItem {
  /** A stable identity for the row, so a reordered feed does not re-key by index. */
  id?: string;
  /** Who. Drawn bold in --bone. */
  actor: string;
  /** What they did. Drawn in --bone-dim. */
  action: string;
  /** What they did it to. Drawn monospaced in --gold — it is an identifier. */
  target?: string;
  /** When. Monospaced --mute, pushed to the trailing edge. Preformatted — ActivityFeed never formats. */
  time?: string;
  /** Badge's vocabulary, driving the leading dot. Defaults to accent. */
  tone?: Tone;
}

/** The alert's severity — the colour and default icon/role it takes. */
export type AlertTone = 'info' | 'success' | 'warning' | 'danger' | 'neutral';

/** Circle for a person, rounded for a team or organisation. */
export type AvatarShape = 'circle' | 'rounded';

/** The avatar's diameter, a fixed repertoire: xs a dense table row, sm a comment byline, md the default, lg a profile header. */
export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg';

/** A presence state, drawn as a filled dot in the corner in the state's colour — `offline` is a visible muted dot, not the absence of one. There is no invisible value: to show no presence at all, omit the optional `status` member. */
export type AvatarStatus = 'online' | 'busy' | 'away' | 'offline';

/** One action a BulkActionBar offers for the current selection. A destructive action stays outline in --error — transparent at rest, the soft --danger-soft tint only on hover — never the filled danger surface, which is ConfirmDialog's alone. */
export interface BulkAction {
  /** A stable identity for the action, so a host can switch on it rather than on the label. */
  id: string;
  /** The button's text. */
  label: string;
  /** A Phosphor class name for the leading glyph Arena draws. */
  icon?: string;
  /** Renders the action outline in --error rather than in --bone-dim. */
  destructive?: boolean;
}

/** The native button behaviour. 'button' does nothing on its own and is the right default outside a form; 'submit' is what a bare <button> silently defaults to inside one, which is the footgun this member exists to make explicit. */
export type ButtonType = 'button' | 'submit' | 'reset';

/** Primary for the one main action in a view; secondary for neutral actions; ghost for tertiary ones; danger for destructive ones. Danger is outline and never filled — Arena's only filled danger surface is the final confirmation inside ConfirmDialog. */
export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';

/** How much of the schedule is on screen at once: a whole week of columns, or one day. Omitted on the component, it is derived from the container width rather than chosen. */
export type CalendarView = 'week' | 'day';

/** A slot in the categorical ramp, in fixed order and never cycled. Colour here means which thing, never what state. The same ramp the charts use — identity is one system across Arena, not one per component — but typed as an enum only here: BarChart.slot, BarChart.slots, LineChart.slot and DoughnutChart.slots still declare a bare number, which their runtime clamp (catColor()) makes safe rather than correct, and narrowing them is an open contract change and not a fact this type states. The bound is not authored here either: it is the count of --color-cat-* slots in contracts/design/palette.dark.json, and check:script-tokens fails if this set stops matching it. */
export type CatSlot = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

/** How a Table column's cells align. Checked against every enum already declared here before it was added; PageHeadAlign is the near miss and is a different set — start/center on a flex axis, with no `right`, and a right-aligned column of figures is precisely what this exists for. */
export type CellAlign = 'left' | 'center' | 'right';

/** One entry in a CommandPalette. `hint` is searched but never shown, so a command can be found by a synonym that never appears in its label. */
export interface Command {
  /** A stable identity for the command, so a host can switch on it rather than on the label. */
  id: string;
  /** What the command is called, and the primary text searched. */
  label: string;
  /** Searched but never shown — a synonym that finds the command. */
  hint?: string;
  /** A Phosphor class name for the leading glyph Arena draws. */
  icon?: string;
  /** The keystroke shown at the row's trailing edge, monospaced. Display only — the palette does not bind it. */
  shortcut?: string;
}

/** The three-step size scale shared by Arena's controls. Heights come from the density tokens, so a control inside .arena-compact re-densifies with the rows around it. */
export type ControlSize = 'sm' | 'md' | 'lg';

/** One entry in a breadcrumb trail. `href` is omitted for the current page, which is never rendered as a link. */
export interface Crumb {
  /** What the crumb reads. */
  label: string;
  /** Where it goes. Absent on the last entry, the current location. */
  href?: string;
}

/** Whether a change was GOOD. Separate from Direction because revenue down is negative and latency down is positive, and only the product knows which. Every sign renders outline, never filled. */
export type DeltaTone = 'neutral' | 'positive' | 'negative';

/** Which way a number moved. Draws the arrow — nothing else. Deliberately separate from whether that movement was good. */
export type Direction = 'up' | 'down';

/** 'ghost' sits on a surface and shows its hairline border; 'solid' is the filled accent treatment. Danger is not among them — Arena's danger convention is outline, and an icon-only danger control has no room to say what it destroys. */
export type IconButtonVariant = 'ghost' | 'solid';

/** The native input types Arena styles. Date/time use the native control -- Arena ships no DatePicker. */
export type InputType = 'text' | 'email' | 'password' | 'search' | 'tel' | 'url' | 'number' | 'date' | 'time' | 'datetime-local';

/** Both halves of the brand lock-up at once — the mark's slot and the wordmark. A fixed repertoire, not a ratio: sm an application frame, md a signed-out panel, lg the manual's Primary, xl the hero case. */
export type LogoSize = 'sm' | 'md' | 'lg' | 'xl';

/** Which edge of the trigger the dropdown panel lines its own edge up with. Checked against every enum already declared here before it was added; nothing carries this pair. PageHeadAlign is the near miss and is a different set -- start/center on a flex axis, with no `end`, where a panel hanging off a trigger has two edges to anchor to and no centre. */
export type MenuAlign = 'start' | 'end';

/** One entry in a Menu, and it is one of three shapes: an entry carrying `divider` draws a hairline rule, one carrying `header` draws a group label, and every other entry draws an activatable row. Every field is optional because of that -- no field is common to all three -- and there is no `id`, because a divider and a header have nothing to identify and `select` carries the whole item rather than a key into the list. */
export interface MenuItem {
  /** What the row reads. */
  label?: string;
  /** A Phosphor class name drawn before the label -- Arena draws the <i>, the consumer names the glyph. */
  icon?: string;
  /** The keyboard hint drawn right-aligned in the mono face. Display only: Menu binds no key for it. */
  shortcut?: string;
  /** Draws the row in the danger ink. Destructive entries go last. */
  destructive?: boolean;
  /** The row is drawn muted and reports no `select`. */
  disabled?: boolean;
  /** Draws a hairline rule in place of a row. Carries no other field. */
  divider?: boolean;
  /** Draws a group label in place of a row. Carries no other field. */
  header?: string;
}

/** Where the coachmark attaches: the two viewport coordinates it positions from. A DOMRect is structurally assignable to it, so a consumer passes getBoundingClientRect() directly. Declared as its own object rather than taken as a DOMRect because a platform type is none of the nine forms (R4), and because these are the only two fields Onboarding reads. */
export interface OnboardingAnchor {
  /** The anchored element's left edge, in viewport pixels. Clamped inside the viewport before use. */
  left: number;
  /** The anchored element's bottom edge, in viewport pixels. The coachmark sits below it. */
  bottom: number;
}

/** One step of a guided tour. All three fields are optional so a step can carry only the ones it needs; Arena renders each conditionally. */
export interface OnboardingStep {
  /** Mono crimson microlabel above the title. */
  eyebrow?: string;
  /** The step's headline, and the coachmark's accessible name. */
  title?: string;
  /** A sentence or two explaining the feature this step presents. */
  body?: string;
}

/** Whether a component's parts lay out side by side or stacked — which axis it runs along. */
export type Orientation = 'horizontal' | 'vertical';

/** How the actions block aligns against the title in PageHead's wide layout. */
export type PageHeadAlign = 'start' | 'center';

/** The bar's colour. No neutral and no warning: a progress bar reports work, and work is either running, done or failed. */
export type ProgressTone = 'accent' | 'gold' | 'success' | 'danger' | 'info';

/** One option in a SegmentedControl. */
export interface SegmentOption {
  /** What the option selects, and what `change` carries. */
  value: string;
  /** What the option reads. One word — the track stops being compact past that. */
  label: string;
}

/** Compact or default. Both sit below Button on purpose — a filter never outweighs an action. Distinct from ControlSize, which offers a large step this control does not. */
export type SegmentedControlSize = 'sm' | 'md';

/** One option in a Select. */
export interface SelectOption {
  /** What the option submits, and what Select's `value` is matched against. */
  value: string;
  /** What the option reads. Free to differ from the value. */
  label: string;
}

/** For a series that IS a state (error rate, pass/fail) rather than an identity. A chart carries identity or meaning, never both — passing tone alongside slot/slots warns in development and tone wins. */
export type SeriesTone = 'success' | 'warning' | 'danger' | 'info';

/** The shape the placeholder reserves: a single text line, a stack of lines, a block, or a circle. */
export type SkeletonVariant = 'text' | 'line' | 'block' | 'circle';

/** Colour for an indeterminate wait. 'accent' on a page surface, 'on-accent' inside a filled button. There is deliberately no success/warning/danger: a wait has no state to report, and a spinner tinted --danger would read as a failure that has not happened. */
export type SpinnerTone = 'accent' | 'gold' | 'neutral' | 'on-accent';

/** How a metric moved. Preformatted — StatCard never formats. The pill's colour says whether the change was GOOD, not which way it points, which is why direction and tone are separate fields. */
export interface StatDelta {
  /** Preformatted, e.g. "+12%" or "-340ms". */
  value: string;
  /** Which way the number moved. Draws the arrow — nothing else. */
  direction: Direction;
  /** Whether that movement is GOOD. Defaults to neutral — an unlabelled delta claims nothing. */
  tone?: DeltaTone;
}

/** The switch's overall size, from a dense sm to a prominent 2xl. */
export type SwitchSize = 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** How a Table column's cells render in card mode: `row` is a label/value pair, `block` is full width with no label. Checked against every enum already declared here; nothing carries this pair. SkeletonVariant is the only other declaration containing the value `block`, and it names a shape of placeholder rather than a layout. */
export type TableCellLayout = 'row' | 'block';

/** One column's configuration. A column says how its cells are headed and set, never what markup goes in them -- the consumer writes a TableCell per cell. */
export interface TableColumn {
  /** The column's label, drawn in the header row. */
  header: string;
  /** How this column's cells align. */
  align?: CellAlign;
  /** A CSS width for the column. Omit to let the table distribute. */
  width?: string;
  /** Draw this column's cells in the mono face and the gold ink -- for identifiers and figures. */
  mono?: boolean;
  /** How this column renders in card mode: a label/value pair, or full width with no label. */
  mobileLayout?: TableCellLayout;
}

/** The tag's emphasis colour, per the Badge/Tag tone taxonomy. */
export type TagTone = 'neutral' | 'primary' | 'success' | 'warning' | 'danger';

/** The side bar's colour. Narrower than Tone: a toast reports an outcome, and there is no informational outcome a toast should interrupt for. */
export type ToastTone = 'neutral' | 'success' | 'danger' | 'gold';

/** What state a value IS in right now, as against how it moved. Badge's vocabulary, so one set of tone names covers the system rather than a second set that is nearly the same. */
export type Tone = 'neutral' | 'accent' | 'gold' | 'success' | 'warning' | 'danger' | 'info';

/** When Input runs `validate`: on blur, or on every change. */
export type ValidateOn = 'blur' | 'change';
