/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { Shell } from "./Shell.js";
import { Card } from "../../components/display/Card.js";
import { Badge } from "../../components/display/Badge.js";
import { Tag } from "../../components/display/Tag.js";
import { StatCard } from "../../components/display/StatCard.js";
import { Button } from "../../components/forms/Button.js";
import { Icon } from "./Icon.js";
const METRICS = [
  { k: "Active projects", v: "12" },
  { k: "Deployments (7d)", v: "48" },
  { k: "Average uptime", v: "99.98%", tone: "success" },
  { k: "Incidents", v: "2", tone: "danger" }
];
const PROJECTS = [
  { name: "Customer portal", client: "Aurora Bank", status: ["success", "Deployed"], build: "#4821", when: "2h ago", tags: ["React", "Node", "AWS"] },
  { name: "Billing engine", client: "Nebula Retail", status: ["warning", "In review"], build: "#1190", when: "40 min ago", tags: ["Go", "PostgreSQL"] },
  { name: "Field app", client: "Terra Log", status: ["info", "QA"], build: "#0327", when: "yesterday", tags: ["Flutter", "gRPC"] },
  { name: "Payment gateway", client: "Aurora Bank", status: ["danger", "Down"], build: "#0918", when: "8 min ago", tags: ["Rust", "Kafka"] },
  { name: "Analytics dashboard", client: "Vela Media", status: ["success", "Deployed"], build: "#2204", when: "3h ago", tags: ["TypeScript", "ClickHouse"] },
  { name: "Internal CRM", client: "Dravensoft", status: ["success", "Deployed"], build: "#7781", when: "1d ago", tags: ["Next.js"] }
];
export function DashboardScreen({ onNav, onOpenProject }) {
  return React.createElement(Shell, {
    active: "dashboard",
    onNav,
    title: "Projects",
    actions: React.createElement(Button, {
      variant: "primary",
      size: "sm",
      icon: React.createElement(Icon, {
        name: "plus",
        size: "var(--icon-md)"
      })
    }, "New project")
  }, React.createElement("div", {
    style: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "calc(var(--sp-1) * 4)", marginBottom: "calc(var(--sp-1) * 7)" }
  }, METRICS.map((m) => React.createElement(StatCard, {
    key: m.k,
    label: m.k,
    value: m.v,
    tone: m.tone
  }))), React.createElement("div", {
    style: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "calc(var(--sp-1) * 4)" }
  }, PROJECTS.map((p) => React.createElement("div", {
    key: p.name,
    onClick: () => onOpenProject && onOpenProject(p),
    style: { cursor: "pointer" }
  }, React.createElement(Card, {
    accent: p.status[0] === "danger",
    style: { height: "100%" },
    eyebrow: p.client,
    title: p.name,
    action: React.createElement(Badge, {
      tone: p.status[0],
      dot: true
    }, p.status[1])
  }, React.createElement("div", {
    style: { display: "flex", gap: "calc(var(--sp-1) * 2)", flexWrap: "wrap", margin: "calc(var(--sp-1) * 1) 0 calc(var(--sp-1) * 4)" }
  }, p.tags.map((t) => React.createElement(Tag, {
    key: t
  }, t))), React.createElement("div", {
    style: { display: "flex", justifyContent: "space-between", alignItems: "center", borderTop: "var(--bw) solid var(--color-base-300)", paddingTop: "calc(var(--sp-1) * 3.5)" }
  }, React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", color: "var(--gold)" }
  }, "build ", p.build), React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", color: "var(--mute)" }
  }, p.when)))))));
}
