/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
const MAP = {
  grid: "squares-four",
  rocket: "rocket-launch",
  activity: "pulse",
  settings: "gear-six",
  bell: "bell",
  search: "magnifying-glass",
  plus: "plus",
  more: "dots-three-vertical",
  revert: "arrow-counter-clockwise",
  check: "check",
  arrow: "arrow-right"
};
const CLS = { bold: "ph-bold", regular: "ph", fill: "ph-fill", duotone: "ph-duotone" };
export function Icon({ name, size = "var(--icon-lg)", weight = "bold", style }) {
  const ph = MAP[name] || name;
  return React.createElement("i", {
    className: (CLS[weight] || CLS.bold) + " ph-" + ph,
    style: { fontSize: size, lineHeight: "var(--dz-lh)", display: "inline-flex", ...style }
  });
}
