/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { dismissDefault, dismissActionable } from "../../tokens.generated.js";
import { LoginScreen } from "./LoginScreen.js";
import { DashboardScreen } from "./DashboardScreen.js";
import { ProjectScreen } from "./ProjectScreen.js";
import { Toast } from "../../components/feedback/Toast.js";
function App() {
  const [screen, setScreen] = React.useState("login");
  const [project, setProject] = React.useState(null);
  const [toasts, setToasts] = React.useState([]);
  const pushToast = (t) => {
    const id = Math.random();
    setToasts((ts) => [...ts, { ...t, id }]);
    if (t.persist)
      return;
    setTimeout(() => setToasts((ts) => ts.filter((x) => x.id !== id)), t.action ? dismissActionable : dismissDefault);
  };
  const nav = (id) => {
    if (id === "dashboard") {
      setScreen("dashboard");
      setProject(null);
    } else
      setScreen("dashboard");
  };
  let view;
  if (screen === "login") {
    view = React.createElement(LoginScreen, {
      onLogin: () => setScreen("dashboard")
    });
  } else if (screen === "project") {
    view = React.createElement(ProjectScreen, {
      onNav: nav,
      project,
      onToast: () => pushToast({ tone: "success", title: "Deployment in progress", message: "build #4822 → production" })
    });
  } else {
    view = React.createElement(DashboardScreen, {
      onNav: nav,
      onOpenProject: (p) => {
        setProject(p);
        setScreen("project");
      }
    });
  }
  return React.createElement(React.Fragment, null, view, React.createElement("div", {
    className: "toast-wrap"
  }, toasts.map((t) => React.createElement(Toast, {
    key: t.id,
    tone: t.tone,
    title: t.title,
    message: t.message,
    onClose: () => setToasts((ts) => ts.filter((x) => x.id !== t.id))
  }))));
}
createRoot(document.getElementById("root")).render(React.createElement(App, null));
