/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
import { Shell } from "./Shell.js";
import { Card } from "../../components/display/Card.js";
import { Badge } from "../../components/display/Badge.js";
import { Tag } from "../../components/display/Tag.js";
import { Table } from "../../components/display/Table.js";
import { ActivityFeed } from "../../components/display/ActivityFeed.js";
import { Tabs } from "../../components/navigation/Tabs.js";
import { Button } from "../../components/forms/Button.js";
import { Switch } from "../../components/forms/Switch.js";
import { Dialog } from "../../components/feedback/Dialog.js";
import { Icon } from "./Icon.js";
const DEPLOYS = [
  { build: "#4821", env: "Production", status: ["success", "Active"], author: "CI · main", dur: "3m 41s" },
  { build: "#4820", env: "Staging", status: ["success", "OK"], author: "ana@", dur: "3m 12s" },
  { build: "#4818", env: "Production", status: ["neutral", "Rolled back"], author: "CI · main", dur: "4m 02s" },
  { build: "#4815", env: "QA", status: ["danger", "Failed"], author: "diego@", dur: "1m 08s" }
];
const DEPLOY_COLUMNS = [
  { key: "build", header: "Build", mono: true, width: "calc(var(--sp-1) * 24)" },
  { key: "env", header: "Environment" },
  { key: "status", header: "Status", render: (s) => React.createElement(Badge, {
    tone: s[0],
    dot: true
  }, s[1]) },
  { key: "author", header: "Author" },
  { key: "dur", header: "Duration", mono: true },
  { key: "actions", header: "", mobileLayout: "block", render: () => React.createElement(Button, {
    variant: "ghost",
    size: "sm"
  }, "Details") }
];
const ACTIVITY = [
  { id: 1, actor: "ana@", action: "approved the release", target: "build #4821", time: "2h ago" },
  { id: 2, actor: "CI", action: "deployed to production", target: "build #4821", time: "2h ago" },
  { id: 3, actor: "diego@", action: "opened incident", target: "checkout latency", time: "3h ago" },
  { id: 4, actor: "nora@", action: "merged", target: "PR #338 · session cache", time: "5h ago" }
];
export function ProjectScreen({ onNav, project, onToast }) {
  const p = project || { name: "Customer portal", client: "Aurora Bank", tags: ["React", "Node", "AWS"] };
  const [tab, setTab] = useState("Deployments");
  const [open, setOpen] = useState(false);
  const [auto, setAuto] = useState(true);
  const deploy = () => {
    setOpen(false);
    onToast && onToast();
  };
  return React.createElement(Shell, {
    active: "dashboard",
    onNav,
    title: p.name,
    actions: React.createElement(Button, {
      variant: "primary",
      size: "sm",
      icon: React.createElement(Icon, {
        name: "rocket",
        size: "var(--icon-md)"
      }),
      onClick: () => setOpen(true)
    }, "Deploy")
  }, React.createElement("div", {
    style: { display: "flex", alignItems: "center", gap: "calc(var(--sp-1) * 3)", marginBottom: "calc(var(--sp-1) * 5)" }
  }, React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", letterSpacing: "var(--ls-field-label)", textTransform: "uppercase", color: "var(--mute)" }
  }, p.client), React.createElement(Badge, {
    tone: "success",
    dot: true
  }, "Deployed"), (p.tags || []).map((t) => React.createElement(Tag, {
    key: t
  }, t))), React.createElement(Tabs, {
    tabs: ["Overview", "Deployments", "Activity", "Settings"],
    value: tab,
    onChange: setTab,
    style: { marginBottom: "calc(var(--sp-1) * 5.5)" }
  }), tab === "Deployments" && React.createElement(Table, {
    columns: DEPLOY_COLUMNS,
    rows: DEPLOYS,
    getRowKey: (d) => d.build
  }), tab === "Activity" && React.createElement(Card, null, React.createElement(ActivityFeed, {
    items: ACTIVITY
  })), tab === "Overview" && React.createElement("div", {
    style: { display: "grid", gridTemplateColumns: "2fr 1fr", gap: "calc(var(--sp-1) * 4)" }
  }, React.createElement(Card, {
    eyebrow: "Status",
    title: "Service health"
  }, React.createElement("div", {
    style: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "calc(var(--sp-1) * 4)" }
  }, [["Uptime", "99.98%", "var(--success)"], ["p95", "186 ms", "var(--bone)"], ["Errors", "0.02%", "var(--gold)"]].map(([k, v, c]) => React.createElement("div", {
    key: k
  }, React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-xs)", letterSpacing: "var(--ls-field-label)", textTransform: "uppercase", color: "var(--mute)" }
  }, k), React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-black)", fontSize: "var(--fs-h3)", color: c, marginTop: "calc(var(--sp-1) * 1.5)" }
  }, v))))), React.createElement(Card, {
    eyebrow: "Delivery",
    title: "Next milestone"
  }, React.createElement("div", {
    style: { fontSize: "var(--dz-text)", color: "var(--bone-dim)", lineHeight: "var(--lh-body)" }
  }, "Release 2.5 — SEPA gateway."), React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", color: "var(--gold)", marginTop: "calc(var(--sp-1) * 2.5)" }
  }, "in 6 days"))), tab === "Settings" && React.createElement(Card, {
    title: "Automation",
    style: { maxWidth: "calc(var(--sp-1) * 130)" }
  }, React.createElement("div", {
    style: { display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 4.5)" }
  }, React.createElement(Switch, {
    state: auto,
    onFuncOn: () => setAuto(true),
    onFuncOff: () => setAuto(false),
    label: "Auto-deploy on approval"
  }), React.createElement(Switch, {
    state: false,
    label: "Notify Slack on every release"
  }), React.createElement(Switch, {
    state: true,
    label: "Require 2 approvals for production"
  }))), React.createElement(Dialog, {
    open,
    onClose: () => setOpen(false),
    eyebrow: "Confirm",
    title: "Deploy to production",
    footer: React.createElement(React.Fragment, null, React.createElement(Button, {
      variant: "ghost",
      onClick: () => setOpen(false)
    }, "Cancel"), React.createElement(Button, {
      variant: "primary",
      icon: React.createElement(Icon, {
        name: "rocket",
        size: "var(--icon-md)"
      }),
      onClick: deploy
    }, "Deploy #4822"))
  }, "You'll publish build ", React.createElement("b", {
    style: { color: "var(--gold)", fontFamily: "var(--font-mono)" }
  }, "#4822"), " of ", React.createElement("b", {
    style: { color: "var(--bone)" }
  }, p.name), " to all ", p.client, " users. You can roll back at any time."));
}
