/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { AppLogo } from "../../components/brand/AppLogo.js";
import { Avatar } from "../../components/display/Avatar.js";
import { IconButton } from "../../components/forms/IconButton.js";
import { ThemeToggle } from "../../components/forms/ThemeToggle.js";
import { Icon } from "./Icon.js";
import { PageHead } from "../../components/navigation/PageHead.js";
import { SideNav } from "../../components/navigation/SideNav.js";
const NAV = [
  { id: "dashboard", icon: React.createElement(Icon, {
    name: "grid",
    size: "var(--icon-lg)"
  }), label: "Projects", href: "#projects" },
  { id: "deploys", icon: React.createElement(Icon, {
    name: "rocket",
    size: "var(--icon-lg)"
  }), label: "Deployments", href: "#deploys" },
  { id: "activity", icon: React.createElement(Icon, {
    name: "activity",
    size: "var(--icon-lg)"
  }), label: "Activity", href: "#activity" },
  { id: "settings", icon: React.createElement(Icon, {
    name: "settings",
    size: "var(--icon-lg)"
  }), label: "Settings", href: "#settings" }
];
export function Shell({ active = "dashboard", onNav, title, actions, children }) {
  return React.createElement("div", {
    style: { display: "grid", gridTemplateColumns: "var(--layout-sidebar) 1fr", minHeight: "100%", background: "var(--bg)" }
  }, React.createElement("aside", {
    style: { borderRight: "var(--bw) solid var(--color-base-300)", padding: "calc(var(--sp-1) * 6) calc(var(--sp-1) * 4)", display: "flex", flexDirection: "column", gap: "calc(var(--sp-1) * 1)" }
  }, React.createElement("div", {
    style: { display: "flex", padding: "0 calc(var(--sp-1) * 2) calc(var(--sp-1) * 5.5)" }
  }, React.createElement(AppLogo, {
    size: "sm",
    mark: React.createElement("img", {
      src: "../../../../assets/rotor-crimson.svg",
      alt: ""
    }),
    name: "Draven",
    dim: "soft"
  })), React.createElement(SideNav, {
    ariaLabel: "Primary",
    items: NAV,
    active,
    onNav: (id, event) => {
      event.preventDefault();
      if (onNav)
        onNav(id);
    }
  }), React.createElement("div", {
    style: { marginTop: "auto", display: "flex", alignItems: "center", gap: "calc(var(--sp-1) * 2.5)", padding: "calc(var(--sp-1) * 3) calc(var(--sp-1) * 2) 0", borderTop: "var(--bw) solid var(--color-base-300)" }
  }, React.createElement(Avatar, {
    name: "Ana Torres",
    size: "sm",
    status: "online"
  }), React.createElement("div", {
    style: { lineHeight: "var(--lh-snug)" }
  }, React.createElement("div", {
    style: { fontSize: "var(--dz-text-md)", color: "var(--bone-dim)", fontFamily: "var(--font-body)" }
  }, "Ana Torres"), React.createElement("div", {
    style: { fontSize: "var(--dz-text-xs)", color: "var(--mute)", fontFamily: "var(--font-mono)" }
  }, "Delivery Lead")))), React.createElement("main", {
    style: { display: "flex", flexDirection: "column", minWidth: 0 }
  }, React.createElement("header", {
    style: { padding: "calc(var(--sp-1) * 5) calc(var(--sp-1) * 8)", borderBottom: "var(--bw) solid var(--color-base-300)" }
  }, React.createElement(PageHead, {
    title,
    style: { marginBottom: 0, alignItems: "center" },
    actions: React.createElement(React.Fragment, null, actions, React.createElement(IconButton, {
      label: "Search"
    }, React.createElement(Icon, {
      name: "search"
    })), React.createElement(IconButton, {
      label: "Notifications"
    }, React.createElement(Icon, {
      name: "bell"
    })), React.createElement(ThemeToggle, null))
  })), React.createElement("div", {
    style: { padding: "calc(var(--sp-1) * 8)", flex: 1, overflow: "auto" }
  }, children)));
}
