/* Exercises the gate against a temporary tree rather than the repository, so a
 * real file moving does not silently change what these assertions prove. */

import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  MAX_DOCUMENT_CHARS, HEADER_MAX_LINES, SIZE_EXEMPT,
  documentSizeProblems, commentRuleProblems, zeroScanProblems,
  isGenerated, allowsHeader,
} from './check-docs.mjs';

function tree(files) {
  const root = mkdtempSync(join(tmpdir(), 'arena-docs-'));
  for (const [path, body] of Object.entries(files)) {
    const full = join(root, path);
    mkdirSync(join(full, '..'), { recursive: true });
    writeFileSync(full, body);
  }
  return root;
}

test('a document over the limit is reported with its size', () => {
  const root = tree({ 'README.md': 'x'.repeat(MAX_DOCUMENT_CHARS + 1) });
  const { problems } = documentSizeProblems(root);
  assert.equal(problems.length, 1);
  assert.match(problems[0], /README\.md: 60001 characters/);
  rmSync(root, { recursive: true });
});

test('a document exactly at the limit passes', () => {
  const root = tree({ 'README.md': 'x'.repeat(MAX_DOCUMENT_CHARS) });
  assert.deepEqual(documentSizeProblems(root).problems, []);
  rmSync(root, { recursive: true });
});

test('DOUBTS.md and docs/ are exempt from the size limit', () => {
  const over = 'x'.repeat(MAX_DOCUMENT_CHARS + 1);
  const root = tree({ 'DOUBTS.md': over, 'docs/superpowers/specs/a.md': over });
  assert.deepEqual(documentSizeProblems(root).problems, []);
  assert.deepEqual(SIZE_EXEMPT[0], 'DOUBTS.md');
  rmSync(root, { recursive: true });
});

test('a framework source carrying any comment is a problem', () => {
  const root = tree({ 'frameworks/react/components/a/A.jsx': '// nope\nexport const A = 1;\n' });
  const { problems } = commentRuleProblems(root);
  assert.equal(problems.length, 1);
  assert.match(problems[0], /only scripts and tests may/);
  rmSync(root, { recursive: true });
});

test('a framework source with no comments passes', () => {
  const root = tree({ 'frameworks/react/components/a/A.jsx': 'export const A = 1;\n' });
  assert.deepEqual(commentRuleProblems(root).problems, []);
  rmSync(root, { recursive: true });
});

test('a script may carry one header, and a second comment is a problem', () => {
  const root = tree({ 'scripts/a.mjs': '/* header */\nconst a = 1;\n// second\n' });
  const { problems } = commentRuleProblems(root);
  assert.equal(problems.length, 1);
  assert.match(problems[0], /a second comment/);
  rmSync(root, { recursive: true });
});

test('a header over the line limit is reported with its length', () => {
  const header = `/*${'\n *'.repeat(HEADER_MAX_LINES)} */`;
  const root = tree({ 'scripts/a.mjs': `${header}\nconst a = 1;\n` });
  const { problems } = commentRuleProblems(root);
  assert.equal(problems.length, 1);
  assert.match(problems[0], new RegExp(`header is ${HEADER_MAX_LINES + 1} lines`));
  rmSync(root, { recursive: true });
});

test("a script's one comment must be the header, not buried mid-file", () => {
  const root = tree({ 'scripts/a.mjs': 'const a = 1;\n// late\n' });
  const { problems } = commentRuleProblems(root);
  assert.equal(problems.length, 1);
  assert.match(problems[0], /must be the file header/);
  rmSync(root, { recursive: true });
});

test('a test file gets the header allowance wherever it sits', () => {
  const root = tree({
    'frameworks/react/components/a/A.test.jsx': '/* header */\nconst a = 1;\n',
    'frameworks/angular/test/Harness.ts': '/* header */\nconst b = 1;\n',
  });
  assert.deepEqual(commentRuleProblems(root).problems, []);
  rmSync(root, { recursive: true });
});

test('a @ts- pragma is a directive, not the file\'s one allowed comment', () => {
  const root = tree({
    'frameworks/angular/components/a/A.ts': '// @ts-expect-error -- needed\nconst a = 1;\n',
  });
  assert.deepEqual(commentRuleProblems(root).problems, []);
  rmSync(root, { recursive: true });
});

test('a generated file is never read, however many comments it carries', () => {
  const root = tree({
    'frameworks/react/Tokens.generated.js': '// one\n// two\nexport const a = 1;\n',
    'frameworks/tailwind/components/a/A.manifest.ts': '// one\nexport const a = 1;\n',
    'frameworks/angular/B.ts': '/* GENERATED by build-x.mjs */\n// two\nconst b = 1;\n',
  });
  assert.deepEqual(commentRuleProblems(root).problems, []);
  rmSync(root, { recursive: true });
});

test('a .js beside a .jsx is build output and is not read', () => {
  const root = tree({
    'frameworks/react/components/a/A.jsx': 'export const A = 1;\n',
    'frameworks/react/components/a/A.js': '// compiled\nexport const A = 1;\n',
  });
  assert.deepEqual(commentRuleProblems(root).problems, []);
  rmSync(root, { recursive: true });
});

test('the vendor bundle is skipped as a directory', () => {
  const root = tree({ 'frameworks/react/vendor/React.js': '// bundled\nexport default 1;\n' });
  assert.deepEqual(commentRuleProblems(root).problems, []);
  rmSync(root, { recursive: true });
});

test('build/ is skipped at the root only, so the scripts phase directory of that name is still read', () => {
  const overLong = `/* ${'x\n * '.repeat(HEADER_MAX_LINES + 2)} */\nconst a = 1;\n`;
  const root = tree({
    'build/angular-test/Emitted.js': overLong,
    'scripts/build/react/build-demos.mjs': overLong,
  });
  const { problems } = commentRuleProblems(root);
  assert.equal(problems.length, 1);
  assert.match(problems[0], /scripts\/build\/react\/build-demos\.mjs/);
  rmSync(root, { recursive: true });
});

test('isGenerated recognises all three markers', () => {
  assert.equal(isGenerated('a/B.generated.ts', ''), true);
  assert.equal(isGenerated('a/B.manifest.ts', ''), true);
  assert.equal(isGenerated('a/B.ts', '/* GENERATED by x.mjs */'), true);
  assert.equal(isGenerated('a/B.ts', 'const a = 1;'), false);
});

test('allowsHeader covers scripts, a .test. infix and a test/ directory', () => {
  assert.equal(allowsHeader(join('scripts', 'a.mjs')), true);
  assert.equal(allowsHeader(join('frameworks', 'react', 'a', 'A.test.jsx')), true);
  assert.equal(allowsHeader(join('frameworks', 'angular', 'test', 'Harness.ts')), true);
  assert.equal(allowsHeader(join('frameworks', 'react', 'a', 'A.jsx')), false);
});

test('a walk that reaches nothing is a failure, not a vacuous pass', () => {
  assert.deepEqual(zeroScanProblems({ documents: 1, sources: 1 }), []);
  assert.match(zeroScanProblems({ documents: 0, sources: 1 })[0], /no \.md files at all/);
  assert.match(zeroScanProblems({ documents: 1, sources: 0 })[0], /no source files at all/);
  assert.equal(zeroScanProblems({ documents: 0, sources: 0 }).length, 2);
});
