/* Covers check-generated.mjs. The git-backed halves take an injected runner, so a
 * case can state a tracked/ignored pair without a repository behind it. */

import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import {
  UNMARKED, UNTRACKED, matches, claimsGeneration,
  unmarkedProblems, trackingProblems, unmarkedCoverageProblems,
} from './check-generated.mjs';

function tree(files) {
  const root = mkdtempSync(join(tmpdir(), 'arena-generated-'));
  for (const [rel, body] of Object.entries(files)) {
    const path = join(root, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
  }
  return root;
}

const runner = ({ tracked = [], ignored = [] }) => (args) => {
  if (args[0] === 'ls-files') return tracked;
  if (args[0] === 'check-ignore') return ignored.includes(args[2]) ? [args[2]] : [];
  return [];
};

test('the two unmarked outputs are named by literal value, with a reason each', () => {
  assert.deepEqual(Object.keys(UNMARKED).sort(), ['assets/fonts/*.woff2', 'intro/support.js']);
  for (const [name, reason] of Object.entries(UNMARKED)) {
    assert.ok(reason.length > 40, `${name} carries no real reason`);
  }
});

test('every ignore pattern carries a reason, and each names a real tree', () => {
  assert.deepEqual(Object.keys(UNTRACKED).sort(), [
    'frameworks/react/components/**/*.generated.js',
    'frameworks/react/ui-kits/**/*.generated.js',
    'frameworks/react/vendor/*.generated.js',
    'frameworks/tailwind/Utilities.generated.css',
  ]);
  for (const [name, reason] of Object.entries(UNTRACKED)) {
    assert.ok(reason.length > 40, `${name} carries no real reason`);
  }
});

test('matches treats * as one segment and **/ as any depth', () => {
  assert.equal(matches('a/*.generated.js', 'a/B.generated.js'), true);
  assert.equal(matches('a/*.generated.js', 'a/b/C.generated.js'), false);
  assert.equal(matches('a/**/*.generated.js', 'a/b/c/D.generated.js'), true);
  assert.equal(matches('a/**/*.generated.js', 'a/B.generated.js'), true);
  assert.equal(matches('assets/fonts/*.woff2', 'assets/fonts/archivo-400.woff2'), true);
  assert.equal(matches('assets/fonts/*.woff2', 'assets/other/archivo-400.woff2'), false);
});

test('a claim of generation counts only as the file header', () => {
  assert.equal(claimsGeneration('/* GENERATED by x.mjs */\nconst a = 1;\n'), true);
  assert.equal(claimsGeneration('// GENERATED from dc-runtime\nconst a = 1;\n'), true);
  assert.equal(claimsGeneration("export const B = '/* GENERATED by x.mjs */';\n"), false);
  assert.equal(claimsGeneration('const a = 1;\n/* GENERATED by x.mjs */\n'), false);
});

test('an output claiming generation without the infix is a problem; UNMARKED excuses it', () => {
  const root = tree({
    'frameworks/react/A.js': '/* GENERATED by x.mjs */\nexport const a = 1;\n',
    'intro/support.js': '// GENERATED from dc-runtime/src/*.ts\nconst a = 1;\n',
    'frameworks/react/B.generated.js': '/* GENERATED by x.mjs */\nexport const b = 1;\n',
  });
  const problems = unmarkedProblems(root);
  assert.equal(problems.length, 1);
  assert.match(problems[0], /frameworks\/react\/A\.js/);
  rmSync(root, { recursive: true });
});

test('a .generated. file that is neither tracked nor ignored reaches no clone', () => {
  const root = tree({ 'frameworks/react/A.generated.js': 'export const a = 1;\n' });
  const problems = trackingProblems(root, runner({}));
  assert.equal(problems.length, 1 + Object.keys(UNTRACKED).length,
    'the orphan, plus every UNTRACKED pattern this bare tree leaves unclaimed');
  assert.match(problems[0], /neither tracked nor ignored/);
  rmSync(root, { recursive: true });
});

test('an ignored .generated. file with no UNTRACKED entry is a problem', () => {
  const root = tree({ 'frameworks/react/vendor/React.generated.js': 'export default 1;\n' });
  const rel = 'frameworks/react/vendor/React.generated.js';
  assert.deepEqual(
    trackingProblems(root, runner({ ignored: [rel] })).filter((p) => p.startsWith(rel)),
    [],
    'the shipped UNTRACKED table already covers the vendor bundle',
  );
  rmSync(root, { recursive: true });
});

test('a file both ignored and in the index is reported, since the index wins silently', () => {
  const root = tree({ 'frameworks/react/vendor/React.generated.js': 'export default 1;\n' });
  const rel = 'frameworks/react/vendor/React.generated.js';
  const problems = trackingProblems(root, runner({ tracked: [rel], ignored: [rel] }));
  assert.ok(problems.some((p) => /still in the index/.test(p)));
  rmSync(root, { recursive: true });
});

test('an UNMARKED entry matching no tracked file is stale and fails', () => {
  assert.equal(unmarkedCoverageProblems('.', runner({
    tracked: ['intro/support.js', 'assets/fonts/archivo-400.woff2'],
  })).length, 0);
  const stale = unmarkedCoverageProblems('.', runner({ tracked: ['intro/support.js'] }));
  assert.equal(stale.length, 1);
  assert.match(stale[0], /assets\/fonts\/\*\.woff2/);
});
