/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { Button } from "../forms/Button.js";
export function ErrorState({ icon, title = "Something went wrong", message, code, retryLabel, onRetry, secondaryAction }) {
  return React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
      gap: "calc(var(--sp-1) * 3)",
      padding: "calc(var(--sp-1) * 14) calc(var(--sp-1) * 8)",
      border: "var(--bw) solid var(--danger)",
      borderRadius: "var(--r-lg)",
      background: "var(--danger-soft)"
    }
  }, icon && React.createElement("div", {
    style: { fontSize: "var(--icon-xl)", color: "var(--danger)", lineHeight: "var(--dz-lh)" }
  }, React.createElement("i", {
    className: icon,
    "aria-hidden": "true"
  })), React.createElement("div", {
    style: { fontFamily: "var(--font-display)", fontWeight: "var(--fw-extrabold)", fontSize: "var(--fs-h4)", color: "var(--bone)" }
  }, title), message && React.createElement("div", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--fs-md)", color: "var(--bone-dim)", maxWidth: "46ch", lineHeight: "var(--lh-body)" }
  }, message), code && React.createElement("code", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", color: "var(--mute)", background: "color-mix(in oklab, var(--color-base-100) 30%, transparent)", padding: "calc(var(--sp-1) * 1) calc(var(--sp-1) * 2.5)", borderRadius: "var(--r-xs)" }
  }, code), React.createElement("div", {
    style: { display: "flex", gap: "calc(var(--sp-1) * 2.5)", marginTop: "calc(var(--sp-1) * 1.5)" }
  }, retryLabel && React.createElement(Button, {
    variant: "primary",
    onClick: onRetry
  }, retryLabel), secondaryAction));
}
