/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
import { useContainerWidth } from "../../use-container-width.js";
import { resolveColors, niceMax, ticks, barPath, srOnly, PAD, CHART_HEIGHT } from "./chart-internals.js";
import { chartBarGap, chartBarRadius } from "../../tokens.generated.js";
export function BarChart({
  labels,
  values,
  seriesLabel,
  slot,
  slots,
  tone,
  valueSuffix
}) {
  if (!labels)
    throw new Error("BarChart: `labels` is required");
  if (!values)
    throw new Error("BarChart: `values` is required");
  const [ref, measured] = useContainerWidth();
  const [hover, setHover] = useState(null);
  const width = measured ?? 600;
  const height = CHART_HEIGHT;
  const n = values.length;
  const fmt = (v) => `${v}${valueSuffix ?? ""}`;
  const colors = resolveColors({ slot, slots, tone, count: n });
  const max = niceMax(Math.max(0, ...values));
  const iw = Math.max(1, width - PAD.l - PAD.r);
  const ih = Math.max(1, height - PAD.t - PAD.b);
  const step = iw / Math.max(1, n);
  const bw = Math.max(1, step - chartBarGap);
  const yOf = (v) => PAD.t + ih - Math.max(0, v) / max * ih;
  const baseline = PAD.t + ih;
  const name = seriesLabel ? `${seriesLabel} — bar chart` : "Bar chart";
  return React.createElement("div", {
    ref,
    style: { position: "relative", width: "100%", height }
  }, React.createElement("svg", {
    width: "100%",
    height,
    role: "img",
    "aria-label": name,
    onMouseLeave: () => setHover(null),
    style: { display: "block", overflow: "visible" }
  }, ticks(max).map((t, i) => React.createElement("g", {
    key: i
  }, React.createElement("line", {
    x1: PAD.l,
    x2: width - PAD.r,
    y1: yOf(t),
    y2: yOf(t),
    stroke: "var(--border)",
    style: { strokeWidth: "var(--bw)" }
  }), React.createElement("text", {
    x: PAD.l - 8,
    y: yOf(t),
    textAnchor: "end",
    dominantBaseline: "middle",
    fill: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    style: { fontSize: "var(--dz-text-2xs)" }
  }, fmt(t)))), React.createElement("line", {
    x1: PAD.l,
    x2: width - PAD.r,
    y1: baseline,
    y2: baseline,
    stroke: "var(--line-strong)",
    style: { strokeWidth: "var(--bw)" }
  }), values.map((v, i) => {
    const x = PAD.l + i * step + (step - bw) / 2;
    const y = yOf(v);
    return React.createElement("g", {
      key: i
    }, React.createElement("path", {
      d: barPath(x, y, bw, baseline - y, chartBarRadius),
      fill: colors[i],
      opacity: hover === null || hover === i ? 1 : 0.55,
      style: { transition: "opacity var(--dur-fast) var(--ease-out)" }
    }), React.createElement("rect", {
      x: PAD.l + i * step,
      y: PAD.t,
      width: step,
      height: ih,
      fill: "transparent",
      onMouseEnter: () => setHover(i)
    }));
  }), values.map((_, i) => React.createElement("text", {
    key: i,
    x: PAD.l + i * step + step / 2,
    y: height - 8,
    textAnchor: "middle",
    fill: "var(--text-muted)",
    fontFamily: "var(--font-body)",
    style: { fontSize: "var(--fs-xs)" }
  }, labels[i] ?? ""))), hover !== null && values[hover] !== undefined && React.createElement("div", {
    style: {
      position: "absolute",
      left: PAD.l + hover * step + step / 2,
      top: `calc(${yOf(values[hover])}px - var(--sp-2))`,
      transform: "translate(-50%,-100%)",
      pointerEvents: "none",
      whiteSpace: "nowrap",
      background: "var(--bg-raised)",
      border: "var(--bw) solid var(--border-strong)",
      borderRadius: "var(--r-sm)",
      boxShadow: "var(--shadow-2)",
      padding: "calc(var(--sp-1) * 1.5) calc(var(--sp-1) * 2.5)"
    }
  }, React.createElement("div", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--dz-text-xs)", color: "var(--mute)" }
  }, labels[hover]), React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-md)", color: "var(--bone)" }
  }, fmt(values[hover]))), React.createElement("table", {
    style: srOnly
  }, React.createElement("caption", null, name), React.createElement("thead", null, React.createElement("tr", null, React.createElement("th", null, "Category"), React.createElement("th", null, seriesLabel || "Value"))), React.createElement("tbody", null, values.map((v, i) => React.createElement("tr", {
    key: i
  }, React.createElement("th", {
    scope: "row"
  }, labels[i]), React.createElement("td", null, fmt(v)))))));
}
