/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React from "react";
import { createRoot } from "react-dom/client";
import { ChartCard } from "../../components/charts/ChartCard.js";
import { BarChart } from "../../components/charts/BarChart.js";
import { LineChart } from "../../components/charts/LineChart.js";
import { DoughnutChart } from "../../components/charts/DoughnutChart.js";
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
function Demo() {
  return React.createElement("div", null, React.createElement("div", {
    className: "sub"
  }, "Identity — the categorical ramp, assigned in order"), React.createElement("div", {
    className: "grid"
  }, React.createElement(ChartCard, {
    title: "Deploys per day"
  }, React.createElement(BarChart, {
    labels: days,
    values: [12, 19, 9, 22, 17, 4, 6],
    seriesLabel: "Deploys"
  })), React.createElement(ChartCard, {
    title: "Requests by service"
  }, React.createElement(BarChart, {
    labels: ["Web", "API", "Worker", "Static"],
    values: [420, 310, 140, 90],
    slots: [1, 2, 3, 4],
    seriesLabel: "rps"
  })), React.createElement(ChartCard, {
    title: "p95 latency"
  }, React.createElement(LineChart, {
    labels: days,
    values: [120, 138, 131, 142, 180, 164, 150],
    seriesLabel: "p95",
    slot: 5,
    area: true,
    valueSuffix: " ms"
  })), React.createElement(ChartCard, {
    title: "Traffic share"
  }, React.createElement(DoughnutChart, {
    labels: ["Web", "API", "Worker", "Static"],
    values: [420, 310, 140, 90],
    seriesLabel: "Traffic",
    valueSuffix: " rps"
  }))), React.createElement("div", {
    className: "sub"
  }, "Meaning — opt-in, only when the series IS a state"), React.createElement("div", {
    className: "grid"
  }, React.createElement(ChartCard, {
    title: "Failed builds"
  }, React.createElement(BarChart, {
    labels: days,
    values: [1, 0, 3, 1, 5, 0, 0],
    tone: "danger",
    seriesLabel: "Failed"
  })), React.createElement(ChartCard, {
    title: "Error rate"
  }, React.createElement(LineChart, {
    labels: days,
    values: [0.4, 0.3, 1.2, 0.6, 2.1, 0.5, 0.4],
    tone: "danger",
    seriesLabel: "Error rate",
    area: true,
    valueSuffix: "%"
  }))));
}
createRoot(document.getElementById("root")).render(React.createElement(Demo, null));
