/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
import { useContainerWidth } from "../../use-container-width.js";
import { resolveColors, arcPath, srOnly, CHART_HEIGHT } from "./chart-internals.js";
import { chartLegendMin, chartLegendMax, chartLegendGap } from "../../tokens.generated.js";
export function DoughnutChart({ labels = [], values = [], slots, valueFormatter, style, ...rest }) {
  const [ref, measured] = useContainerWidth();
  const [hover, setHover] = useState(null);
  const width = measured ?? 600;
  const height = CHART_HEIGHT;
  const n = values.length;
  const fmt = valueFormatter || ((v) => String(v));
  const colors = resolveColors({ slots: slots ?? Array.from({ length: n }, (_, i) => i + 1), count: n });
  const total = values.reduce((a, b) => a + Math.max(0, b), 0);
  const legendW = Math.min(chartLegendMax, Math.max(chartLegendMin, width * 0.34));
  const plotW = Math.max(1, width - legendW - chartLegendGap);
  const cx = plotW / 2;
  const cy = height / 2;
  const rOuter = Math.max(1, Math.min(plotW, height) / 2 - 8);
  const rInner = rOuter * 0.62;
  let angle = -Math.PI / 2;
  const segments = values.map((v, i) => {
    const share = total > 0 ? Math.max(0, v) / total : 0;
    const a0 = angle;
    const a1 = angle + share * Math.PI * 2;
    angle = a1;
    return { i, a0, a1, share };
  });
  return React.createElement("div", {
    ref,
    style: { position: "relative", width: "100%", height, display: "flex", gap: "var(--chart-legend-gap)", ...style },
    ...rest
  }, React.createElement("svg", {
    width: plotW,
    height,
    role: "img",
    "aria-label": "Doughnut chart",
    onMouseLeave: () => setHover(null),
    style: { display: "block", flexShrink: 0 }
  }, segments.map(({ i, a0, a1 }) => a1 > a0 && React.createElement("path", {
    key: i,
    d: arcPath(cx, cy, rOuter, rInner, a0, a1),
    fill: colors[i],
    stroke: "var(--surface-card)",
    opacity: hover === null || hover === i ? 1 : 0.55,
    onMouseEnter: () => setHover(i),
    style: { transition: "opacity var(--dur-fast) var(--ease-out)", strokeWidth: "var(--bw-strong)" }
  })), hover !== null && segments[hover] && React.createElement("text", {
    x: cx,
    y: cy,
    textAnchor: "middle",
    dominantBaseline: "middle",
    fill: "var(--bone)",
    fontFamily: "var(--font-mono)",
    style: { fontSize: "var(--dz-text-lg)" }
  }, Math.round(segments[hover].share * 100), "%")), React.createElement("div", {
    style: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", justifyContent: "center", gap: "calc(var(--sp-1) * 1.5)", overflow: "auto" }
  }, labels.map((l, i) => React.createElement("div", {
    key: i,
    onMouseEnter: () => setHover(i),
    onMouseLeave: () => setHover(null),
    style: { display: "flex", alignItems: "center", gap: "calc(var(--sp-1) * 2)", opacity: hover === null || hover === i ? 1 : 0.55 }
  }, React.createElement("span", {
    "aria-hidden": "true",
    style: { width: "calc(var(--sp-1) * 2.5)", height: "calc(var(--sp-1) * 2.5)", borderRadius: "var(--r-xs)", background: colors[i], flexShrink: 0 }
  }), React.createElement("span", {
    style: {
      flex: 1,
      minWidth: 0,
      fontFamily: "var(--font-body)",
      fontSize: "var(--dz-text-sm)",
      color: "var(--text-body)",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap"
    }
  }, l), React.createElement("span", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-sm)", color: "var(--mute)" }
  }, fmt(values[i]))))), React.createElement("table", {
    style: srOnly
  }, React.createElement("caption", null, "Doughnut chart"), React.createElement("thead", null, React.createElement("tr", null, React.createElement("th", null, "Category"), React.createElement("th", null, "Value"))), React.createElement("tbody", null, values.map((v, i) => React.createElement("tr", {
    key: i
  }, React.createElement("th", {
    scope: "row"
  }, labels[i]), React.createElement("td", null, fmt(v)))))));
}
