/* GENERATED by scripts/build-demos.mjs — edit the .jsx sibling, not this file.
 * Bun.Transpiler, classic JSX (React.createElement). See build-demos.mjs
 * for the full rationale. */
import React, { useState } from "react";
import { useContainerWidth } from "../../use-container-width.js";
import { resolveColors, niceMax, ticks, srOnly, PAD, CHART_HEIGHT } from "./chart-internals.js";
import { chartPointR, chartPointRHover } from "../../tokens.generated.js";
export function LineChart({
  labels,
  values,
  seriesLabel,
  slot,
  tone,
  area = false,
  valueSuffix
}) {
  if (!labels)
    throw new Error("LineChart: `labels` is required");
  if (!values)
    throw new Error("LineChart: `values` is required");
  const [ref, measured] = useContainerWidth();
  const [hover, setHover] = useState(null);
  const width = measured ?? 600;
  const height = CHART_HEIGHT;
  const n = values.length;
  const fmt = (v) => `${v}${valueSuffix ?? ""}`;
  const color = resolveColors({ slot, tone, count: 1 })[0];
  const max = niceMax(Math.max(0, ...values));
  const iw = Math.max(1, width - PAD.l - PAD.r);
  const ih = Math.max(1, height - PAD.t - PAD.b);
  const xOf = (i) => PAD.l + (n <= 1 ? iw / 2 : iw / (n - 1) * i);
  const yOf = (v) => PAD.t + ih - Math.max(0, v) / max * ih;
  const baseline = PAD.t + ih;
  const points = values.map((v, i) => `${xOf(i)},${yOf(v)}`).join(" ");
  const areaPath = n ? `M${xOf(0)},${baseline} L${values.map((v, i) => `${xOf(i)},${yOf(v)}`).join(" L")} L${xOf(n - 1)},${baseline} Z` : "";
  const name = seriesLabel ? `${seriesLabel} — line chart` : "Line chart";
  const onMove = (e) => {
    if (!n)
      return;
    const box = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - box.left;
    let best = 0;
    for (let i = 1;i < n; i++)
      if (Math.abs(xOf(i) - x) < Math.abs(xOf(best) - x))
        best = i;
    setHover(best);
  };
  return React.createElement("div", {
    ref,
    style: { position: "relative", width: "100%", height }
  }, React.createElement("svg", {
    width: "100%",
    height,
    role: "img",
    "aria-label": name,
    style: { display: "block", overflow: "visible" }
  }, ticks(max).map((t, i) => React.createElement("g", {
    key: i
  }, React.createElement("line", {
    x1: PAD.l,
    x2: width - PAD.r,
    y1: yOf(t),
    y2: yOf(t),
    stroke: "var(--border)",
    style: { strokeWidth: "var(--bw)" }
  }), React.createElement("text", {
    x: PAD.l - 8,
    y: yOf(t),
    textAnchor: "end",
    dominantBaseline: "middle",
    fill: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    style: { fontSize: "var(--dz-text-2xs)" }
  }, fmt(t)))), React.createElement("line", {
    x1: PAD.l,
    x2: width - PAD.r,
    y1: baseline,
    y2: baseline,
    stroke: "var(--line-strong)",
    style: { strokeWidth: "var(--bw)" }
  }), area && n > 0 && React.createElement("path", {
    d: areaPath,
    fill: `color-mix(in oklab, ${color} 18%, transparent)`,
    stroke: "none"
  }), hover !== null && React.createElement("line", {
    x1: xOf(hover),
    x2: xOf(hover),
    y1: PAD.t,
    y2: baseline,
    stroke: "var(--border-strong)",
    style: { strokeWidth: "var(--bw)" },
    strokeDasharray: "3 3"
  }), n > 1 && React.createElement("polyline", {
    points,
    fill: "none",
    stroke: color,
    style: { strokeWidth: "var(--bw-strong)" },
    strokeLinejoin: "round",
    strokeLinecap: "round"
  }), values.map((v, i) => React.createElement("circle", {
    key: i,
    cx: xOf(i),
    cy: yOf(v),
    r: hover === i ? chartPointRHover : chartPointR,
    fill: color,
    stroke: "var(--surface-card)",
    style: { strokeWidth: "var(--bw-strong)" }
  })), labels.map((l, i) => React.createElement("text", {
    key: i,
    x: xOf(i),
    y: height - 8,
    textAnchor: "middle",
    fill: "var(--text-muted)",
    fontFamily: "var(--font-body)",
    style: { fontSize: "var(--fs-xs)" }
  }, l)), React.createElement("rect", {
    x: PAD.l,
    y: PAD.t,
    width: iw,
    height: ih,
    fill: "transparent",
    onMouseMove: onMove,
    onMouseLeave: () => setHover(null)
  })), hover !== null && values[hover] !== undefined && React.createElement("div", {
    style: {
      position: "absolute",
      left: xOf(hover),
      top: `calc(${yOf(values[hover])}px - calc(var(--sp-1) * 2.5))`,
      transform: "translate(-50%,-100%)",
      pointerEvents: "none",
      whiteSpace: "nowrap",
      background: "var(--bg-raised)",
      border: "var(--bw) solid var(--border-strong)",
      borderRadius: "var(--r-sm)",
      boxShadow: "var(--shadow-2)",
      padding: "calc(var(--sp-1) * 1.5) calc(var(--sp-1) * 2.5)"
    }
  }, React.createElement("div", {
    style: { fontFamily: "var(--font-body)", fontSize: "var(--dz-text-xs)", color: "var(--mute)" }
  }, labels[hover]), React.createElement("div", {
    style: { fontFamily: "var(--font-mono)", fontSize: "var(--dz-text-md)", color: "var(--bone)" }
  }, fmt(values[hover]))), React.createElement("table", {
    style: srOnly
  }, React.createElement("caption", null, name), React.createElement("thead", null, React.createElement("tr", null, React.createElement("th", null, "Point"), React.createElement("th", null, seriesLabel || "Value"))), React.createElement("tbody", null, values.map((v, i) => React.createElement("tr", {
    key: i
  }, React.createElement("th", {
    scope: "row"
  }, labels[i]), React.createElement("td", null, fmt(v)))))));
}
